
package views;

// Se importan las librerías a utilizar.
import views.tables.*;
import lib.SupportFunctions;

/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class CinemaRoomManagement extends javax.swing.JFrame {

    // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;
    
    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();
    
    /**
     * Constructor del gestor de empleados.
     */
    public CinemaRoomManagement() {
        initComponents();
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        clearCinemaRoomSearch();
        
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCinemaManagement = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        sepTittle = new javax.swing.JSeparator();
        lblSucursalName = new javax.swing.JLabel();
        btnChangeBranch = new javax.swing.JButton();
        panContainerCinemaRoom = new javax.swing.JPanel();
        panConsultList = new javax.swing.JPanel();
        scpCinemaRoomList = new javax.swing.JScrollPane();
        tblCinemaRoomList = new javax.swing.JTable();
        txtSearchIdCinemaRoom = new javax.swing.JTextField();
        sepSearchIdEmployee = new javax.swing.JSeparator();
        btnSearchCinemaRoom = new javax.swing.JButton();
        btnClearSearchCinemaRoom = new javax.swing.JButton();
        panCRUD = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblIdCinemaRoom = new javax.swing.JLabel();
        lblFilaCinemaRoom = new javax.swing.JLabel();
        lblColumCinemaRoom = new javax.swing.JLabel();
        lblBranchCinemaRoom = new javax.swing.JLabel();
        txtIdCinemaRoom = new javax.swing.JTextField();
        txtFilaCinemaRoom = new javax.swing.JTextField();
        txtColumnCinemaRoom = new javax.swing.JTextField();
        cmbBranchCinemaRoom = new javax.swing.JComboBox<>();
        btnClearCinemaRoom = new javax.swing.JButton();
        btnRegisterModifyCinemaRoom = new javax.swing.JButton();
        btnBackCinemaRoom = new javax.swing.JButton();
        btnDeleteCinemaRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panCinemaManagement.setBackground(new java.awt.Color(249, 249, 249));
        panCinemaManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 0, 145)));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.setPreferredSize(new java.awt.Dimension(215, 40));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsTopBarLayout.createSequentialGroup()
                .addGroup(panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMin)
                    .addComponent(btnExit))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lblTittle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle.setText("Gestión de salas");
        lblTittle.setToolTipText("");

        sepTittle.setBackground(new java.awt.Color(249, 249, 249));
        sepTittle.setForeground(new java.awt.Color(239, 232, 244));

        lblSucursalName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName.setText("Sucursal ");

        btnChangeBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnChangeBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shopIcon.png"))); // NOI18N
        btnChangeBranch.setToolTipText("Cambiar Sucursal");
        btnChangeBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChangeBranch.setContentAreaFilled(false);
        btnChangeBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeBranch.setFocusPainted(false);
        btnChangeBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChangeBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseMoved(evt);
            }
        });
        btnChangeBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseExited(evt);
            }
        });

        panContainerCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        panContainerCinemaRoom.setLayout(new java.awt.CardLayout());

        panConsultList.setBackground(new java.awt.Color(249, 249, 249));

        tblCinemaRoomList.setBackground(new java.awt.Color(249, 249, 249));
        tblCinemaRoomList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Sucursal", "Flias", "Columnas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCinemaRoomList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblCinemaRoomList.setSelectionBackground(new java.awt.Color(75, 0, 145));
        tblCinemaRoomList.getTableHeader().setReorderingAllowed(false);
        tblCinemaRoomList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCinemaRoomListMouseClicked(evt);
            }
        });
        scpCinemaRoomList.setViewportView(tblCinemaRoomList);

        txtSearchIdCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchIdCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchIdCinemaRoom.setText("Codigo de la sala");
        txtSearchIdCinemaRoom.setBorder(null);
        txtSearchIdCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchIdCinemaRoomMouseClicked(evt);
            }
        });
        txtSearchIdCinemaRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIdCinemaRoomActionPerformed(evt);
            }
        });
        txtSearchIdCinemaRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdCinemaRoomKeyTyped(evt);
            }
        });

        sepSearchIdEmployee.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdEmployee.setForeground(new java.awt.Color(75, 0, 145));

        btnSearchCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchCinemaRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchCinemaRoom.setToolTipText(" Buscar");
        btnSearchCinemaRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchCinemaRoom.setContentAreaFilled(false);
        btnSearchCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCinemaRoom.setFocusPainted(false);
        btnSearchCinemaRoom.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchCinemaRoomMouseMoved(evt);
            }
        });
        btnSearchCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchCinemaRoomMouseExited(evt);
            }
        });

        btnClearSearchCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchCinemaRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchCinemaRoom.setToolTipText("Limpiar");
        btnClearSearchCinemaRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchCinemaRoom.setContentAreaFilled(false);
        btnClearSearchCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchCinemaRoom.setFocusPainted(false);
        btnClearSearchCinemaRoom.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchCinemaRoomMouseMoved(evt);
            }
        });
        btnClearSearchCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchCinemaRoomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panConsultListLayout = new javax.swing.GroupLayout(panConsultList);
        panConsultList.setLayout(panConsultListLayout);
        panConsultListLayout.setHorizontalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sepSearchIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnSearchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearSearchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpCinemaRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        panConsultListLayout.setVerticalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearSearchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                            .addComponent(txtSearchIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(sepSearchIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSearchCinemaRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scpCinemaRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        panContainerCinemaRoom.add(panConsultList, "card2");

        panCRUD.setBackground(new java.awt.Color(249, 249, 249));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Datos del empleado");
        lblTittle1.setToolTipText("");

        lblIdCinemaRoom.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblIdCinemaRoom.setForeground(new java.awt.Color(28, 0, 63));
        lblIdCinemaRoom.setText("Código:");
        lblIdCinemaRoom.setToolTipText("");

        lblFilaCinemaRoom.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblFilaCinemaRoom.setForeground(new java.awt.Color(28, 0, 63));
        lblFilaCinemaRoom.setText("Fila:");
        lblFilaCinemaRoom.setToolTipText("");

        lblColumCinemaRoom.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblColumCinemaRoom.setForeground(new java.awt.Color(28, 0, 63));
        lblColumCinemaRoom.setText("Columna:");
        lblColumCinemaRoom.setToolTipText("");

        lblBranchCinemaRoom.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblBranchCinemaRoom.setForeground(new java.awt.Color(28, 0, 63));
        lblBranchCinemaRoom.setText("Sucursal:");
        lblBranchCinemaRoom.setToolTipText("");

        txtIdCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        txtIdCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdCinemaRoom.setText("Código de la Sucursal");
        txtIdCinemaRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));
        txtIdCinemaRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCinemaRoomActionPerformed(evt);
            }
        });

        txtFilaCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        txtFilaCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilaCinemaRoom.setText("Fila");
        txtFilaCinemaRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtColumnCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        txtColumnCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtColumnCinemaRoom.setText("Columna");
        txtColumnCinemaRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        cmbBranchCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        cmbBranchCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbBranchCinemaRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar una Sucursal - ", "Cines de Venezuela" }));
        cmbBranchCinemaRoom.setBorder(null);
        cmbBranchCinemaRoom.setLightWeightPopupEnabled(false);

        btnClearCinemaRoom.setBackground(new java.awt.Color(239, 232, 244));
        btnClearCinemaRoom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearCinemaRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnClearCinemaRoom.setText("Limpiar");
        btnClearCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearCinemaRoom.setBorderPainted(false);
        btnClearCinemaRoom.setContentAreaFilled(false);
        btnClearCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearCinemaRoom.setFocusPainted(false);
        btnClearCinemaRoom.setOpaque(true);
        btnClearCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearCinemaRoomMouseMoved(evt);
            }
        });
        btnClearCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearCinemaRoomMouseExited(evt);
            }
        });

        btnRegisterModifyCinemaRoom.setBackground(new java.awt.Color(239, 232, 244));
        btnRegisterModifyCinemaRoom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterModifyCinemaRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterModifyCinemaRoom.setText("@Registrar/Actualizar");
        btnRegisterModifyCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterModifyCinemaRoom.setBorderPainted(false);
        btnRegisterModifyCinemaRoom.setContentAreaFilled(false);
        btnRegisterModifyCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterModifyCinemaRoom.setFocusPainted(false);
        btnRegisterModifyCinemaRoom.setOpaque(true);
        btnRegisterModifyCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterModifyCinemaRoomMouseMoved(evt);
            }
        });
        btnRegisterModifyCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterModifyCinemaRoomMouseExited(evt);
            }
        });

        btnBackCinemaRoom.setBackground(new java.awt.Color(239, 232, 244));
        btnBackCinemaRoom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBackCinemaRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnBackCinemaRoom.setText("Atrás");
        btnBackCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackCinemaRoom.setBorderPainted(false);
        btnBackCinemaRoom.setContentAreaFilled(false);
        btnBackCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackCinemaRoom.setFocusPainted(false);
        btnBackCinemaRoom.setOpaque(true);
        btnBackCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBackCinemaRoomMouseMoved(evt);
            }
        });
        btnBackCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackCinemaRoomMouseExited(evt);
            }
        });

        btnDeleteCinemaRoom.setBackground(new java.awt.Color(239, 232, 244));
        btnDeleteCinemaRoom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteCinemaRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteCinemaRoom.setText("Eliminar");
        btnDeleteCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteCinemaRoom.setBorderPainted(false);
        btnDeleteCinemaRoom.setContentAreaFilled(false);
        btnDeleteCinemaRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteCinemaRoom.setFocusPainted(false);
        btnDeleteCinemaRoom.setOpaque(true);
        btnDeleteCinemaRoom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeleteCinemaRoomMouseMoved(evt);
            }
        });
        btnDeleteCinemaRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteCinemaRoomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panCRUDLayout = new javax.swing.GroupLayout(panCRUD);
        panCRUD.setLayout(panCRUDLayout);
        panCRUDLayout.setHorizontalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addComponent(lblIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblColumCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColumnCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(btnBackCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegisterModifyCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(lblFilaCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilaCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblBranchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBranchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panCRUDLayout.setVerticalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblColumCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtColumnCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilaCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBranchCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilaCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterModifyCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panContainerCinemaRoom.add(panCRUD, "card2");

        javax.swing.GroupLayout panCinemaManagementLayout = new javax.swing.GroupLayout(panCinemaManagement);
        panCinemaManagement.setLayout(panCinemaManagementLayout);
        panCinemaManagementLayout.setHorizontalGroup(
            panCinemaManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addComponent(sepTittle)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCinemaManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCinemaManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panContainerCinemaRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panCinemaManagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        panCinemaManagementLayout.setVerticalGroup(
            panCinemaManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCinemaManagementLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCinemaManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCinemaManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainerCinemaRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCinemaManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCinemaManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
        btnChangeBranch.addActionListener(evt);
        btnSearchCinemaRoom.addActionListener(evt);
        btnClearSearchCinemaRoom.addActionListener(evt);
        
        // CRUD
        btnBackCinemaRoom.addActionListener(evt);
        btnClearCinemaRoom.addActionListener(evt);
        btnDeleteCinemaRoom.addActionListener(evt);
        btnRegisterModifyCinemaRoom.addActionListener(evt);
        
    }
    
    /**
     * Método que permite activar los eventos del escuchador Mouse.
     * @param evt parámetro que se activa cuando el Mouse reacciona a algo.
     */
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        tblCinemaRoomList.addMouseListener(evt);
        
    }
    
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Métodos para manipular tablas ">
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel de Client Management.
     */
    public void clearCinemaRoomSearch(){
        
        txtSearchIdCinemaRoom.setText("Código de la sala");
        clearCinemaRoomTable(tblCinemaRoomList);
    }
     /**
     * Método que retorna los valores iniciales de un JTable.
     * @param table parámetro JTable.
     */
    public void clearCinemaRoomTable(javax.swing.JTable table){
        this.table.buildCinemaRoomTable(table, null);
    }
    
    /**
     * Método para indicar el valor de una columna en un JTable.
     * @param column 
     */
    public void setColumnTable(int column){
        this.column = column;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la columna.
     */
    public int getColumnTable(){
        return column;
    }
    
    /**
     * Método para indicar el valor de una fila en un JTable.
     * @param row 
     */
    public void setRowTable(int row){
        this.row = row;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la fila.
     */
    public int getRowTable(){
        return row;
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Limpiar vista ">
    /**
     * Método para devolver a los valores por defecto a los elementos de la view.
     */
    public void clearView(){
               
        btnBackCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnBackCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnChangeBranch.setForeground(new java.awt.Color(0,0,0));
        btnChangeBranch.setBackground(new java.awt.Color(239,232,244));
        
        btnClearCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnClearCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        btnClearSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearSearchCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnClearSearchCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        btnDeleteCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnDeleteCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        btnRegisterModifyCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        btnSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnSearchCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnSearchCinemaRoom.setBackground(new java.awt.Color(239,232,244));
        
        cmbBranchCinemaRoom.setSelectedIndex(0);
        
        txtIdCinemaRoom.setText("Codigo de la sala");
        txtFilaCinemaRoom.setText("Fila de la sala");
        txtColumnCinemaRoom.setText("Columna de la sala");
        
        // Búsqueda
        txtSearchIdCinemaRoom.setText("Cédula del cliente");
        
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Top Bar ">
    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void btnChangeBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseMoved
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChangeBranchMouseMoved

    private void btnChangeBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseExited
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChangeBranchMouseExited

    //</editor-fold>
    
    
    private void tblCinemaRoomListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCinemaRoomListMouseClicked
        setColumnTable(tblCinemaRoomList.getColumnModel().getColumnIndexAtX(evt.getX()));
        setRowTable(evt.getY()/tblCinemaRoomList.getRowHeight());
    }//GEN-LAST:event_tblCinemaRoomListMouseClicked

    //<editor-fold defaultstate="collapsed" desc=" Search CinemaRoom ">
    private void txtSearchIdCinemaRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchIdCinemaRoomMouseClicked
        txtSearchIdCinemaRoom.setText("");
    }//GEN-LAST:event_txtSearchIdCinemaRoomMouseClicked

    private void txtSearchIdCinemaRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIdCinemaRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIdCinemaRoomActionPerformed

    private void txtSearchIdCinemaRoomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdCinemaRoomKeyTyped
        /*if(txtSearchIdEmployee.getText().length() < 10)
        support.integerPositiveKeyTyped(evt);
        else
        evt.consume();*/
    }//GEN-LAST:event_txtSearchIdCinemaRoomKeyTyped

    private void btnSearchCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCinemaRoomMouseMoved
        btnSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchCinemaRoomMouseMoved

    private void btnSearchCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCinemaRoomMouseExited
        btnSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchCinemaRoomMouseExited

    private void btnClearSearchCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchCinemaRoomMouseMoved
        btnClearSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchCinemaRoomMouseMoved

    private void btnClearSearchCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchCinemaRoomMouseExited
        btnClearSearchCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchCinemaRoomMouseExited

    private void txtIdCinemaRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCinemaRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCinemaRoomActionPerformed

    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" CRUD CinemaRoom">
    private void btnClearCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearCinemaRoomMouseMoved
        btnClearCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnClearCinemaRoom.setForeground(new java.awt.Color(255,255,255));
        btnClearCinemaRoom.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnClearCinemaRoomMouseMoved

    private void btnClearCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearCinemaRoomMouseExited
        btnClearCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnClearCinemaRoom.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnClearCinemaRoomMouseExited

    private void btnRegisterModifyCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyCinemaRoomMouseMoved
        btnRegisterModifyCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnRegisterModifyCinemaRoom.setForeground(new java.awt.Color(255,255,255));
        btnRegisterModifyCinemaRoom.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnRegisterModifyCinemaRoomMouseMoved

    private void btnRegisterModifyCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyCinemaRoomMouseExited
        btnRegisterModifyCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyCinemaRoom.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnRegisterModifyCinemaRoomMouseExited

    private void btnBackCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCinemaRoomMouseMoved
        btnBackCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnBackCinemaRoom.setForeground(new java.awt.Color(255,255,255));
        btnBackCinemaRoom.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnBackCinemaRoomMouseMoved

    private void btnBackCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCinemaRoomMouseExited
        btnBackCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnBackCinemaRoom.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnBackCinemaRoomMouseExited

    private void btnDeleteCinemaRoomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCinemaRoomMouseMoved
        btnDeleteCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnDeleteCinemaRoom.setForeground(new java.awt.Color(255,255,255));
        btnDeleteCinemaRoom.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnDeleteCinemaRoomMouseMoved

    private void btnDeleteCinemaRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCinemaRoomMouseExited
        btnDeleteCinemaRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteCinemaRoom.setForeground(new java.awt.Color(0,0,0));
        btnDeleteCinemaRoom.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnDeleteCinemaRoomMouseExited
    //</editor-fold>
  
    //<editor-fold defaultstate="collapsed" desc=" Declaración de variables ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBackCinemaRoom;
    public javax.swing.JButton btnChangeBranch;
    public javax.swing.JButton btnClearCinemaRoom;
    public javax.swing.JButton btnClearSearchCinemaRoom;
    public javax.swing.JButton btnDeleteCinemaRoom;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnRegisterModifyCinemaRoom;
    public javax.swing.JButton btnSearchCinemaRoom;
    public javax.swing.JComboBox<String> cmbBranchCinemaRoom;
    private javax.swing.JLabel lblBranchCinemaRoom;
    private javax.swing.JLabel lblColumCinemaRoom;
    private javax.swing.JLabel lblFilaCinemaRoom;
    private javax.swing.JLabel lblIdCinemaRoom;
    public javax.swing.JLabel lblSucursalName;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panCRUD;
    private javax.swing.JPanel panCinemaManagement;
    public javax.swing.JPanel panConsultList;
    public javax.swing.JPanel panContainerCinemaRoom;
    private javax.swing.JScrollPane scpCinemaRoomList;
    private javax.swing.JSeparator sepSearchIdEmployee;
    private javax.swing.JSeparator sepTittle;
    public javax.swing.JTable tblCinemaRoomList;
    public javax.swing.JTextField txtColumnCinemaRoom;
    public javax.swing.JTextField txtFilaCinemaRoom;
    public javax.swing.JTextField txtIdCinemaRoom;
    public javax.swing.JTextField txtSearchIdCinemaRoom;
    // End of variables declaration//GEN-END:variables

    //</editor-fold>
    
}
