
package views;

// Se importan las librerías a utilizar.
import views.tables.*;
import lib.SupportFunctions;

/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class ClientManagement extends javax.swing.JFrame {
    
    // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;
    
    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();
    
    /**
     * Constructor del gestor de empleados.
     */
    public ClientManagement() {
        initComponents();
        
         // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        clearClientSearch();
        
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panClientManagement = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        sepTittle = new javax.swing.JSeparator();
        lblSucursalName = new javax.swing.JLabel();
        btnChangeBranch = new javax.swing.JButton();
        panContainerClient = new javax.swing.JPanel();
        panCRUD = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblEmailClient = new javax.swing.JLabel();
        lblLastNameClient = new javax.swing.JLabel();
        lblNameClient = new javax.swing.JLabel();
        lblPhoneClient = new javax.swing.JLabel();
        lblDirectionClient = new javax.swing.JLabel();
        lblIdClient = new javax.swing.JLabel();
        dchBirthClient = new com.toedter.calendar.JDateChooser();
        lblBirthClient = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        txtNameClient = new javax.swing.JTextField();
        txtLastNameClient = new javax.swing.JTextField();
        txtDirectionClient = new javax.swing.JTextField();
        txtPhoneClient = new javax.swing.JTextField();
        btnClearClient = new javax.swing.JButton();
        btnRegisterModifyClient = new javax.swing.JButton();
        btnBackClient = new javax.swing.JButton();
        btnDeleteClient = new javax.swing.JButton();
        txtEmailClient = new javax.swing.JTextField();
        panConsultList = new javax.swing.JPanel();
        scpClientList = new javax.swing.JScrollPane();
        tblClientList = new javax.swing.JTable();
        txtSearchIdClient = new javax.swing.JTextField();
        sepSearchIdClient = new javax.swing.JSeparator();
        txtSearchNameClient = new javax.swing.JTextField();
        btnSearchClient = new javax.swing.JButton();
        sepSearchNameClient = new javax.swing.JSeparator();
        btnClearSearchClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panClientManagement.setBackground(new java.awt.Color(249, 249, 249));
        panClientManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 0, 145)));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.setPreferredSize(new java.awt.Dimension(215, 40));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsTopBarLayout.createSequentialGroup()
                .addGroup(panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMin)
                    .addComponent(btnExit))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lblTittle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle.setText("Gestión de Clientes");
        lblTittle.setToolTipText("");

        sepTittle.setBackground(new java.awt.Color(249, 249, 249));
        sepTittle.setForeground(new java.awt.Color(239, 232, 244));

        lblSucursalName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName.setText("Sucursal ");

        btnChangeBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnChangeBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shopIcon.png"))); // NOI18N
        btnChangeBranch.setToolTipText("Cambiar Sucursal");
        btnChangeBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChangeBranch.setContentAreaFilled(false);
        btnChangeBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeBranch.setFocusPainted(false);
        btnChangeBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChangeBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseMoved(evt);
            }
        });
        btnChangeBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseExited(evt);
            }
        });
        btnChangeBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBranchActionPerformed(evt);
            }
        });

        panContainerClient.setBackground(new java.awt.Color(249, 249, 249));
        panContainerClient.setLayout(new java.awt.CardLayout());

        panCRUD.setBackground(new java.awt.Color(249, 249, 249));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Datos del cliente");
        lblTittle1.setToolTipText("");

        lblEmailClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEmailClient.setForeground(new java.awt.Color(28, 0, 63));
        lblEmailClient.setText("Correo:");
        lblEmailClient.setToolTipText("");

        lblLastNameClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLastNameClient.setForeground(new java.awt.Color(28, 0, 63));
        lblLastNameClient.setText("Apellido:");
        lblLastNameClient.setToolTipText("");

        lblNameClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblNameClient.setForeground(new java.awt.Color(28, 0, 63));
        lblNameClient.setText("Nombre:");
        lblNameClient.setToolTipText("");

        lblPhoneClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblPhoneClient.setForeground(new java.awt.Color(28, 0, 63));
        lblPhoneClient.setText("Teléfono:");
        lblPhoneClient.setToolTipText("");

        lblDirectionClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblDirectionClient.setForeground(new java.awt.Color(28, 0, 63));
        lblDirectionClient.setText("Dirección:");
        lblDirectionClient.setToolTipText("");

        lblIdClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblIdClient.setForeground(new java.awt.Color(28, 0, 63));
        lblIdClient.setText("Cédula:");
        lblIdClient.setToolTipText("");

        dchBirthClient.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient.setDateFormatString("yyyy-MM-dd");
        dchBirthClient.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient.setOpaque(false);

        lblBirthClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblBirthClient.setForeground(new java.awt.Color(28, 0, 63));
        lblBirthClient.setText("Fecha de nacimiento:");
        lblBirthClient.setToolTipText("");

        txtIdClient.setBackground(new java.awt.Color(249, 249, 249));
        txtIdClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdClient.setText("Cédula del cliente");
        txtIdClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtNameClient.setBackground(new java.awt.Color(249, 249, 249));
        txtNameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNameClient.setText("Nombre del cliente");
        txtNameClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtLastNameClient.setBackground(new java.awt.Color(249, 249, 249));
        txtLastNameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLastNameClient.setText("Apellido del cliente");
        txtLastNameClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtDirectionClient.setBackground(new java.awt.Color(249, 249, 249));
        txtDirectionClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDirectionClient.setText("Dirección del cliente");
        txtDirectionClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtPhoneClient.setBackground(new java.awt.Color(249, 249, 249));
        txtPhoneClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneClient.setText("Teléfono del cliente");
        txtPhoneClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));
        txtPhoneClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneClientActionPerformed(evt);
            }
        });

        btnClearClient.setBackground(new java.awt.Color(239, 232, 244));
        btnClearClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearClient.setForeground(new java.awt.Color(0, 0, 0));
        btnClearClient.setText("Limpiar");
        btnClearClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearClient.setBorderPainted(false);
        btnClearClient.setContentAreaFilled(false);
        btnClearClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearClient.setFocusPainted(false);
        btnClearClient.setOpaque(true);
        btnClearClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearClientMouseMoved(evt);
            }
        });
        btnClearClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearClientMouseExited(evt);
            }
        });
        btnClearClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearClientActionPerformed(evt);
            }
        });

        btnRegisterModifyClient.setBackground(new java.awt.Color(239, 232, 244));
        btnRegisterModifyClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterModifyClient.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterModifyClient.setText("@Registrar/Actualizar");
        btnRegisterModifyClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterModifyClient.setBorderPainted(false);
        btnRegisterModifyClient.setContentAreaFilled(false);
        btnRegisterModifyClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterModifyClient.setFocusPainted(false);
        btnRegisterModifyClient.setOpaque(true);
        btnRegisterModifyClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterModifyClientMouseMoved(evt);
            }
        });
        btnRegisterModifyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterModifyClientMouseExited(evt);
            }
        });

        btnBackClient.setBackground(new java.awt.Color(239, 232, 244));
        btnBackClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBackClient.setForeground(new java.awt.Color(0, 0, 0));
        btnBackClient.setText("Atrás");
        btnBackClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackClient.setBorderPainted(false);
        btnBackClient.setContentAreaFilled(false);
        btnBackClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackClient.setFocusPainted(false);
        btnBackClient.setOpaque(true);
        btnBackClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBackClientMouseMoved(evt);
            }
        });
        btnBackClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackClientMouseExited(evt);
            }
        });

        btnDeleteClient.setBackground(new java.awt.Color(239, 232, 244));
        btnDeleteClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteClient.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteClient.setText("Eliminar");
        btnDeleteClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteClient.setBorderPainted(false);
        btnDeleteClient.setContentAreaFilled(false);
        btnDeleteClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteClient.setFocusPainted(false);
        btnDeleteClient.setOpaque(true);
        btnDeleteClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeleteClientMouseMoved(evt);
            }
        });
        btnDeleteClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteClientMouseExited(evt);
            }
        });

        txtEmailClient.setBackground(new java.awt.Color(249, 249, 249));
        txtEmailClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailClient.setText("Correo del cliente");
        txtEmailClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        javax.swing.GroupLayout panCRUDLayout = new javax.swing.GroupLayout(panCRUD);
        panCRUD.setLayout(panCRUDLayout);
        panCRUDLayout.setHorizontalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addComponent(btnBackClient, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearClient, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegisterModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLastNameClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panCRUDLayout.createSequentialGroup()
                                        .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panCRUDLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                                                .addComponent(lblBirthClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dchBirthClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                                                .addComponent(lblEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panCRUDLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(23, 23, 23))
        );
        panCRUDLayout.setVerticalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBirthClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dchBirthClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        lblTittle1.getAccessibleContext().setAccessibleName("Datos del Cliente");
        dchBirthClient.getAccessibleContext().setAccessibleDescription("");

        panContainerClient.add(panCRUD, "card2");

        panConsultList.setBackground(new java.awt.Color(249, 249, 249));

        tblClientList.setBackground(new java.awt.Color(249, 249, 249));
        tblClientList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre y Apellido", "Dirección", "Correo", "Telefono", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblClientList.setSelectionBackground(new java.awt.Color(75, 0, 145));
        tblClientList.getTableHeader().setReorderingAllowed(false);
        tblClientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientListMouseClicked(evt);
            }
        });
        scpClientList.setViewportView(tblClientList);

        txtSearchIdClient.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchIdClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchIdClient.setText("   Cédula del cliente");
        txtSearchIdClient.setBorder(null);
        txtSearchIdClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchIdClientMouseClicked(evt);
            }
        });
        txtSearchIdClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdClientKeyTyped(evt);
            }
        });

        sepSearchIdClient.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdClient.setForeground(new java.awt.Color(75, 0, 145));

        txtSearchNameClient.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchNameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchNameClient.setText("Nombre y apellido del Cliente");
        txtSearchNameClient.setBorder(null);
        txtSearchNameClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchNameClientMouseClicked(evt);
            }
        });
        txtSearchNameClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchNameClientKeyTyped(evt);
            }
        });

        btnSearchClient.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchClient.setToolTipText(" Buscar");
        btnSearchClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchClient.setContentAreaFilled(false);
        btnSearchClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchClient.setFocusPainted(false);
        btnSearchClient.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchClientMouseMoved(evt);
            }
        });
        btnSearchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchClientMouseExited(evt);
            }
        });

        sepSearchNameClient.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchNameClient.setForeground(new java.awt.Color(75, 0, 145));

        btnClearSearchClient.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchClient.setToolTipText("Limpiar");
        btnClearSearchClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchClient.setContentAreaFilled(false);
        btnClearSearchClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchClient.setFocusPainted(false);
        btnClearSearchClient.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchClientMouseMoved(evt);
            }
        });
        btnClearSearchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchClientMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panConsultListLayout = new javax.swing.GroupLayout(panConsultList);
        panConsultList.setLayout(panConsultListLayout);
        panConsultListLayout.setHorizontalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpClientList)
                .addContainerGap())
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchIdClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepSearchIdClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                        .addComponent(txtSearchNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                        .addComponent(sepSearchNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addComponent(btnSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClearSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        panConsultListLayout.setVerticalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepSearchNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addGroup(panConsultListLayout.createSequentialGroup()
                                .addComponent(sepSearchIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpClientList, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        panContainerClient.add(panConsultList, "card2");

        javax.swing.GroupLayout panClientManagementLayout = new javax.swing.GroupLayout(panClientManagement);
        panClientManagement.setLayout(panClientManagementLayout);
        panClientManagementLayout.setHorizontalGroup(
            panClientManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addComponent(sepTittle)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panClientManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panClientManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panContainerClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panClientManagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        panClientManagementLayout.setVerticalGroup(
            panClientManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClientManagementLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panClientManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panClientManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainerClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panClientManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panClientManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
        btnChangeBranch.addActionListener(evt);
        btnSearchClient.addActionListener(evt);
        btnClearSearchClient.addActionListener(evt);
        
        // CRUD
        btnBackClient.addActionListener(evt);
        btnClearClient.addActionListener(evt);
        btnDeleteClient.addActionListener(evt);
        btnRegisterModifyClient.addActionListener(evt);
        
    }
    
    /**
     * Método que permite activar los eventos del escuchador Mouse.
     * @param evt parámetro que se activa cuando el Mouse reacciona a algo.
     */
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        tblClientList.addMouseListener(evt);
        
    }
    
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Métodos para manipular tablas ">
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel de Client Management.
     */
    public void clearClientSearch(){
        
        txtSearchIdClient.setText("Cédula del cliente");
        txtSearchNameClient.setText("Nombre y apellido del cliente");
        clearClientTable(tblClientList);
    }
     /**
     * Método que retorna los valores iniciales de un JTable.
     * @param table parámetro JTable.
     */
    public void clearClientTable(javax.swing.JTable table){
        this.table.buildClientTable(table, null);
    }
    
    /**
     * Método para indicar el valor de una columna en un JTable.
     * @param column 
     */
    public void setColumnTable(int column){
        this.column = column;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la columna.
     */
    public int getColumnTable(){
        return column;
    }
    
    /**
     * Método para indicar el valor de una fila en un JTable.
     * @param row 
     */
    public void setRowTable(int row){
        this.row = row;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la fila.
     */
    public int getRowTable(){
        return row;
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Limpiar vista ">
    /**
     * Método para devolver a los valores por defecto a los elementos de la view.
     */
    public void clearView(){
               
        btnBackClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackClient.setForeground(new java.awt.Color(0,0,0));
        btnBackClient.setBackground(new java.awt.Color(239,232,244));
        
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnChangeBranch.setForeground(new java.awt.Color(0,0,0));
        btnChangeBranch.setBackground(new java.awt.Color(239,232,244));
        
        btnClearClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearClient.setForeground(new java.awt.Color(0,0,0));
        btnClearClient.setBackground(new java.awt.Color(239,232,244));
        
        btnClearSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearSearchClient.setForeground(new java.awt.Color(0,0,0));
        btnClearSearchClient.setBackground(new java.awt.Color(239,232,244));
        
        btnDeleteClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteClient.setForeground(new java.awt.Color(0,0,0));
        btnDeleteClient.setBackground(new java.awt.Color(239,232,244));
        
        btnRegisterModifyClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyClient.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyClient.setBackground(new java.awt.Color(239,232,244));
        
        btnSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnSearchClient.setForeground(new java.awt.Color(0,0,0));
        btnSearchClient.setBackground(new java.awt.Color(239,232,244));
        
        
        dchBirthClient.setDate(null);
        
        txtIdClient.setText("Cedula del cliente");
        txtNameClient.setText("Nombre del cliente");
        txtLastNameClient.setText("Apellido del cliente");
        txtEmailClient.setText("Correo electrónico del cliente");
        txtDirectionClient.setText("Dirección del Empleado");
        txtPhoneClient.setText("Teléfono del cliente");
        
        // Búsqueda
        txtSearchIdClient.setText("Cédula del cliente");
        txtSearchNameClient.setText("Nombre y apellido del cliente");
        
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Top Bar ">
    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void btnChangeBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseMoved
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChangeBranchMouseMoved

    private void btnChangeBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseExited
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChangeBranchMouseExited
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Search Employee ">
    private void tblClientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientListMouseClicked
        setColumnTable(tblClientList.getColumnModel().getColumnIndexAtX(evt.getX()));
        setRowTable(evt.getY()/tblClientList.getRowHeight());
    }//GEN-LAST:event_tblClientListMouseClicked

    private void txtSearchIdClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchIdClientMouseClicked
        txtSearchIdClient.setText("");
    }//GEN-LAST:event_txtSearchIdClientMouseClicked

    private void txtSearchIdClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdClientKeyTyped
        /*if(txtSearchIdEmployee.getText().length() < 10)
        support.integerPositiveKeyTyped(evt);
        else
        evt.consume();*/
    }//GEN-LAST:event_txtSearchIdClientKeyTyped

    private void txtSearchNameClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchNameClientMouseClicked
        txtSearchNameClient.setText("");
    }//GEN-LAST:event_txtSearchNameClientMouseClicked

    private void txtSearchNameClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameClientKeyTyped
        //support.alphabetKeyTyped(evt);
    }//GEN-LAST:event_txtSearchNameClientKeyTyped

    private void btnSearchClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClientMouseMoved
        btnSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchClientMouseMoved

    private void btnSearchClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClientMouseExited
        btnSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchClientMouseExited

    private void btnClearSearchClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchClientMouseMoved
        btnClearSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchClientMouseMoved

    private void btnClearSearchClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchClientMouseExited
        btnClearSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchClientMouseExited
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" CRUD Client">
    private void btnDeleteClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteClientMouseExited
        btnDeleteClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteClient.setForeground(new java.awt.Color(0,0,0));
        btnDeleteClient.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnDeleteClientMouseExited

    private void btnDeleteClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteClientMouseMoved
        btnDeleteClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnDeleteClient.setForeground(new java.awt.Color(255,255,255));
        btnDeleteClient.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnDeleteClientMouseMoved

    private void btnBackClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackClientMouseExited
        btnBackClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackClient.setForeground(new java.awt.Color(0,0,0));
        btnBackClient.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnBackClientMouseExited

    private void btnBackClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackClientMouseMoved
        btnBackClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnBackClient.setForeground(new java.awt.Color(255,255,255));
        btnBackClient.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnBackClientMouseMoved

    private void btnRegisterModifyClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyClientMouseExited
        btnRegisterModifyClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyClient.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyClient.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnRegisterModifyClientMouseExited

    private void btnRegisterModifyClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyClientMouseMoved
        btnRegisterModifyClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnRegisterModifyClient.setForeground(new java.awt.Color(255,255,255));
        btnRegisterModifyClient.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnRegisterModifyClientMouseMoved

    private void btnClearClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearClientMouseExited
        btnClearClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearClient.setForeground(new java.awt.Color(0,0,0));
        btnClearClient.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnClearClientMouseExited

    private void btnClearClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearClientMouseMoved
        btnClearClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnClearClient.setForeground(new java.awt.Color(255,255,255));
        btnClearClient.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnClearClientMouseMoved

    private void txtPhoneClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneClientActionPerformed

    private void btnClearClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearClientActionPerformed

    private void btnChangeBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeBranchActionPerformed
    //</editor-fold>
 
    //<editor-fold defaultstate="collapsed" desc=" Declaración de variables ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBackClient;
    public javax.swing.JButton btnChangeBranch;
    public javax.swing.JButton btnClearClient;
    public javax.swing.JButton btnClearSearchClient;
    public javax.swing.JButton btnDeleteClient;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnRegisterModifyClient;
    public javax.swing.JButton btnSearchClient;
    public com.toedter.calendar.JDateChooser dchBirthClient;
    private javax.swing.JLabel lblBirthClient;
    private javax.swing.JLabel lblDirectionClient;
    private javax.swing.JLabel lblEmailClient;
    private javax.swing.JLabel lblIdClient;
    private javax.swing.JLabel lblLastNameClient;
    private javax.swing.JLabel lblNameClient;
    private javax.swing.JLabel lblPhoneClient;
    public javax.swing.JLabel lblSucursalName;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panCRUD;
    private javax.swing.JPanel panClientManagement;
    public javax.swing.JPanel panConsultList;
    public javax.swing.JPanel panContainerClient;
    private javax.swing.JScrollPane scpClientList;
    private javax.swing.JSeparator sepSearchIdClient;
    private javax.swing.JSeparator sepSearchNameClient;
    private javax.swing.JSeparator sepTittle;
    public javax.swing.JTable tblClientList;
    public javax.swing.JTextField txtDirectionClient;
    public javax.swing.JTextField txtEmailClient;
    public javax.swing.JTextField txtIdClient;
    public javax.swing.JTextField txtLastNameClient;
    public javax.swing.JTextField txtNameClient;
    public javax.swing.JTextField txtPhoneClient;
    public javax.swing.JTextField txtSearchIdClient;
    public javax.swing.JTextField txtSearchNameClient;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
