
package views;

import views.tables.Table;
import lib.SupportFunctions;

/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class ConsultList extends javax.swing.JFrame {

    // Variables de apoyo para conocer la ubicación de la aplicación.
    int xx = 0, xy = 0;
    
    // Variables de soporte para el uso de tablas.
    int column = 0, row = 0;
    
    // Se instancia la clase de soporte Table.
    Table table = new Table();
    
    // Se instancia la clase de soporte.
    private SupportFunctions suport;
    
    /**
     * Creates new form ConsultList
     */
    public ConsultList() 
    {
        // Inicializa todas las variables (o mejor dicho componentes) que usa el JFrame.
        initComponents();
        
        // Se instancia la clase de soporte.
        suport = new SupportFunctions();
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());

                
    }
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
     /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt)
    {
        btnAdd.addActionListener(evt);
        btnSearch.addActionListener(evt);
        btnMin.addActionListener(evt);
        btnExit.addActionListener(evt);
    }
    /**
     * Método que permite activar los eventos del escuchador Mouse.
     * @param evt parámetro que se activa cuando el Mouse reacciona a algo.
     */
    public void addMouseEvents(java.awt.event.MouseListener evt)
    {
        tblConsultBranchList.addMouseListener(evt);
        tblEmployee.addMouseListener(evt);
    }
    //</editor-fold>
    

                    




        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panConsultation = new javax.swing.JPanel();
        lblConsultList = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblEntityName = new javax.swing.JLabel();
        panTableConsultList = new javax.swing.JPanel();
        panTableConsultCinemaRoomList = new javax.swing.JPanel();
        spcConsultCinemaRoomList = new javax.swing.JScrollPane();
        tblConsultCinemaRoomList = new javax.swing.JTable();
        panTableConsultEnterpriseList = new javax.swing.JPanel();
        scpConsultEnterpriseList = new javax.swing.JScrollPane();
        tblConsultEnterpriseList = new javax.swing.JTable();
        panTableConsultClientList = new javax.swing.JPanel();
        scpConsultClientList = new javax.swing.JScrollPane();
        tblConsultClientList = new javax.swing.JTable();
        panTableConsultCandytList = new javax.swing.JPanel();
        scpConsultCandytList = new javax.swing.JScrollPane();
        tblConsultCandyList = new javax.swing.JTable();
        panTableConsultEmployeeList = new javax.swing.JPanel();
        scpConsultEmployeeList = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        panTableConsultFilmList = new javax.swing.JPanel();
        scpConsultFilmList = new javax.swing.JScrollPane();
        tblConsultFilmList = new javax.swing.JTable();
        panTableConsultBranchList = new javax.swing.JPanel();
        scpConsultBranchList = new javax.swing.JScrollPane();
        tblConsultBranchList = new javax.swing.JTable();
        panFilter = new javax.swing.JPanel();
        panFilterCinemaRoom = new javax.swing.JPanel();
        cmbFilterCinemaRoom = new javax.swing.JComboBox<>();
        panFilterEnterprise = new javax.swing.JPanel();
        cmbFilterEnterprise = new javax.swing.JComboBox<>();
        panFilterClient = new javax.swing.JPanel();
        cmbFilterClient = new javax.swing.JComboBox<>();
        panFilterCandy = new javax.swing.JPanel();
        cmbFilterCandy = new javax.swing.JComboBox<>();
        panFilterEmployee = new javax.swing.JPanel();
        cmbFilterEmployee = new javax.swing.JComboBox<>();
        panFilterFilm = new javax.swing.JPanel();
        cmbFilterFilm = new javax.swing.JComboBox<>();
        panFilterBranch = new javax.swing.JPanel();
        cmbFilterBranch = new javax.swing.JComboBox<>();
        panAdd = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        panSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        panTopBar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panConsultation.setBackground(new java.awt.Color(249, 249, 249));
        panConsultation.setAlignmentX(0.0F);
        panConsultation.setAlignmentY(0.0F);

        lblConsultList.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblConsultList.setForeground(new java.awt.Color(28, 0, 63));
        lblConsultList.setText("Consultar listado de ");

        txtSearch.setBackground(new java.awt.Color(249, 249, 249));
        txtSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblEntityName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEntityName.setForeground(new java.awt.Color(28, 0, 63));
        lblEntityName.setText("@");

        panTableConsultList.setBackground(new java.awt.Color(249, 249, 249));
        panTableConsultList.setLayout(new java.awt.CardLayout());

        tblConsultCinemaRoomList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultCinemaRoomList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fila", "Columna", "Cod Sucursal", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spcConsultCinemaRoomList.setViewportView(tblConsultCinemaRoomList);

        javax.swing.GroupLayout panTableConsultCinemaRoomListLayout = new javax.swing.GroupLayout(panTableConsultCinemaRoomList);
        panTableConsultCinemaRoomList.setLayout(panTableConsultCinemaRoomListLayout);
        panTableConsultCinemaRoomListLayout.setHorizontalGroup(
            panTableConsultCinemaRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTableConsultCinemaRoomListLayout.createSequentialGroup()
                .addComponent(spcConsultCinemaRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panTableConsultCinemaRoomListLayout.setVerticalGroup(
            panTableConsultCinemaRoomListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spcConsultCinemaRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultCinemaRoomList, "card3");

        tblConsultEnterpriseList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultEnterpriseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Correo", "Precio Boleto", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpConsultEnterpriseList.setViewportView(tblConsultEnterpriseList);

        javax.swing.GroupLayout panTableConsultEnterpriseListLayout = new javax.swing.GroupLayout(panTableConsultEnterpriseList);
        panTableConsultEnterpriseList.setLayout(panTableConsultEnterpriseListLayout);
        panTableConsultEnterpriseListLayout.setHorizontalGroup(
            panTableConsultEnterpriseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultEnterpriseList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultEnterpriseListLayout.setVerticalGroup(
            panTableConsultEnterpriseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultEnterpriseList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultEnterpriseList, "card4");

        panTableConsultClientList.setName(""); // NOI18N

        tblConsultClientList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultClientList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Direccion", "Correo", "Telefono", "Tipo", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpConsultClientList.setViewportView(tblConsultClientList);

        javax.swing.GroupLayout panTableConsultClientListLayout = new javax.swing.GroupLayout(panTableConsultClientList);
        panTableConsultClientList.setLayout(panTableConsultClientListLayout);
        panTableConsultClientListLayout.setHorizontalGroup(
            panTableConsultClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultClientList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultClientListLayout.setVerticalGroup(
            panTableConsultClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultClientList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultClientList, "card5");

        tblConsultCandyList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultCandyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpConsultCandytList.setViewportView(tblConsultCandyList);

        javax.swing.GroupLayout panTableConsultCandytListLayout = new javax.swing.GroupLayout(panTableConsultCandytList);
        panTableConsultCandytList.setLayout(panTableConsultCandytListLayout);
        panTableConsultCandytListLayout.setHorizontalGroup(
            panTableConsultCandytListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultCandytList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultCandytListLayout.setVerticalGroup(
            panTableConsultCandytListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultCandytList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultCandytList, "card6");

        tblEmployee.setBackground(new java.awt.Color(249, 249, 249));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Cargo", "Sucursal", "Nombre", "Apellido", "Telefono", "Dirección", "Nacimiento", "Ingreso", "Correo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEmployee.setSelectionBackground(new java.awt.Color(75, 0, 145));
        tblEmployee.getTableHeader().setReorderingAllowed(false);
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        scpConsultEmployeeList.setViewportView(tblEmployee);

        javax.swing.GroupLayout panTableConsultEmployeeListLayout = new javax.swing.GroupLayout(panTableConsultEmployeeList);
        panTableConsultEmployeeList.setLayout(panTableConsultEmployeeListLayout);
        panTableConsultEmployeeListLayout.setHorizontalGroup(
            panTableConsultEmployeeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultEmployeeList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultEmployeeListLayout.setVerticalGroup(
            panTableConsultEmployeeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultEmployeeList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultEmployeeList, "card7");

        panTableConsultFilmList.setBackground(new java.awt.Color(249, 249, 249));

        tblConsultFilmList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultFilmList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Sipnosis", "Duracion", "Tipo", "Clasificacion", "Fecha Estreno", "", ""
            }
        ));
        scpConsultFilmList.setViewportView(tblConsultFilmList);

        javax.swing.GroupLayout panTableConsultFilmListLayout = new javax.swing.GroupLayout(panTableConsultFilmList);
        panTableConsultFilmList.setLayout(panTableConsultFilmListLayout);
        panTableConsultFilmListLayout.setHorizontalGroup(
            panTableConsultFilmListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultFilmList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultFilmListLayout.setVerticalGroup(
            panTableConsultFilmListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultFilmList, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        panTableConsultList.add(panTableConsultFilmList, "card8");

        panTableConsultBranchList.setBackground(new java.awt.Color(249, 249, 249));

        tblConsultBranchList.setBackground(new java.awt.Color(249, 249, 249));
        tblConsultBranchList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Ciudad", "Dirección", "Telefono", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsultBranchList.setSelectionBackground(new java.awt.Color(75, 0, 145));
        scpConsultBranchList.setViewportView(tblConsultBranchList);

        javax.swing.GroupLayout panTableConsultBranchListLayout = new javax.swing.GroupLayout(panTableConsultBranchList);
        panTableConsultBranchList.setLayout(panTableConsultBranchListLayout);
        panTableConsultBranchListLayout.setHorizontalGroup(
            panTableConsultBranchListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultBranchList, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        panTableConsultBranchListLayout.setVerticalGroup(
            panTableConsultBranchListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConsultBranchList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panTableConsultList.add(panTableConsultBranchList, "card2");

        panFilter.setLayout(new java.awt.CardLayout());

        cmbFilterCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterCinemaRoom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterCinemaRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Filas", "Columnas" }));

        javax.swing.GroupLayout panFilterCinemaRoomLayout = new javax.swing.GroupLayout(panFilterCinemaRoom);
        panFilterCinemaRoom.setLayout(panFilterCinemaRoomLayout);
        panFilterCinemaRoomLayout.setHorizontalGroup(
            panFilterCinemaRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterCinemaRoom, 0, 0, Short.MAX_VALUE)
        );
        panFilterCinemaRoomLayout.setVerticalGroup(
            panFilterCinemaRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFilterCinemaRoomLayout.createSequentialGroup()
                .addComponent(cmbFilterCinemaRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panFilter.add(panFilterCinemaRoom, "card3");

        cmbFilterEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre" }));

        javax.swing.GroupLayout panFilterEnterpriseLayout = new javax.swing.GroupLayout(panFilterEnterprise);
        panFilterEnterprise.setLayout(panFilterEnterpriseLayout);
        panFilterEnterpriseLayout.setHorizontalGroup(
            panFilterEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterEnterprise, 0, 0, Short.MAX_VALUE)
        );
        panFilterEnterpriseLayout.setVerticalGroup(
            panFilterEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterEnterprise)
        );

        panFilter.add(panFilterEnterprise, "card4");

        cmbFilterClient.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre", "Dirección" }));
        cmbFilterClient.setBorder(null);

        javax.swing.GroupLayout panFilterClientLayout = new javax.swing.GroupLayout(panFilterClient);
        panFilterClient.setLayout(panFilterClientLayout);
        panFilterClientLayout.setHorizontalGroup(
            panFilterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panFilterClientLayout.setVerticalGroup(
            panFilterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterClient)
        );

        panFilter.add(panFilterClient, "card5");

        cmbFilterCandy.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterCandy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterCandy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre", "Dirección" }));
        cmbFilterCandy.setBorder(null);

        javax.swing.GroupLayout panFilterCandyLayout = new javax.swing.GroupLayout(panFilterCandy);
        panFilterCandy.setLayout(panFilterCandyLayout);
        panFilterCandyLayout.setHorizontalGroup(
            panFilterCandyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterCandy, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panFilterCandyLayout.setVerticalGroup(
            panFilterCandyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterCandy)
        );

        panFilter.add(panFilterCandy, "card6");

        cmbFilterEmployee.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre", "Dirección" }));
        cmbFilterEmployee.setBorder(null);

        javax.swing.GroupLayout panFilterEmployeeLayout = new javax.swing.GroupLayout(panFilterEmployee);
        panFilterEmployee.setLayout(panFilterEmployeeLayout);
        panFilterEmployeeLayout.setHorizontalGroup(
            panFilterEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panFilterEmployeeLayout.setVerticalGroup(
            panFilterEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterEmployee)
        );

        panFilter.add(panFilterEmployee, "card7");

        cmbFilterFilm.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterFilm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre", "Dirección" }));
        cmbFilterFilm.setBorder(null);

        javax.swing.GroupLayout panFilterFilmLayout = new javax.swing.GroupLayout(panFilterFilm);
        panFilterFilm.setLayout(panFilterFilmLayout);
        panFilterFilmLayout.setHorizontalGroup(
            panFilterFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panFilterFilmLayout.setVerticalGroup(
            panFilterFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterFilm)
        );

        panFilter.add(panFilterFilm, "card8");

        cmbFilterBranch.setBackground(new java.awt.Color(249, 249, 249));
        cmbFilterBranch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFilterBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar - ", "Codigo", "Nombre", "Dirección" }));
        cmbFilterBranch.setBorder(null);

        javax.swing.GroupLayout panFilterBranchLayout = new javax.swing.GroupLayout(panFilterBranch);
        panFilterBranch.setLayout(panFilterBranchLayout);
        panFilterBranchLayout.setHorizontalGroup(
            panFilterBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterBranch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panFilterBranchLayout.setVerticalGroup(
            panFilterBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbFilterBranch, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panFilter.add(panFilterBranch, "card2");

        panAdd.setBackground(new java.awt.Color(249, 249, 249));
        panAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));

        btnAdd.setBackground(new java.awt.Color(249, 249, 249));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/addIcon.png"))); // NOI18N
        btnAdd.setToolTipText("Agregar");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAdd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAddMouseMoved(evt);
            }
        });
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panAddLayout = new javax.swing.GroupLayout(panAdd);
        panAdd.setLayout(panAddLayout);
        panAddLayout.setHorizontalGroup(
            panAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panAddLayout.setVerticalGroup(
            panAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAddLayout.createSequentialGroup()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panSearch.setBackground(new java.awt.Color(249, 249, 249));
        panSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        panSearch.setMaximumSize(new java.awt.Dimension(52, 52));
        panSearch.setMinimumSize(new java.awt.Dimension(0, 50));
        panSearch.setPreferredSize(new java.awt.Dimension(52, 52));

        btnSearch.setBackground(new java.awt.Color(249, 249, 249));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnSearch.setToolTipText(" Buscar");
        btnSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setFocusPainted(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchMouseMoved(evt);
            }
        });
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panSearchLayout = new javax.swing.GroupLayout(panSearch);
        panSearch.setLayout(panSearchLayout);
        panSearchLayout.setHorizontalGroup(
            panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panSearchLayout.setVerticalGroup(
            panSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchLayout.createSequentialGroup()
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panTopBarMouseDragged(evt);
            }
        });
        panTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panTopBarMouseReleased(evt);
            }
        });

        btnMin.setText("Min");

        btnExit.setText("Sal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panTopBarLayout = new javax.swing.GroupLayout(panTopBar);
        panTopBar.setLayout(panTopBarLayout);
        panTopBarLayout.setHorizontalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTopBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panTopBarLayout.setVerticalGroup(
            panTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panConsultationLayout = new javax.swing.GroupLayout(panConsultation);
        panConsultation.setLayout(panConsultationLayout);
        panConsultationLayout.setHorizontalGroup(
            panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultationLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblConsultList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntityName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panConsultationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panTableConsultList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panConsultationLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panConsultationLayout.setVerticalGroup(
            panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultationLayout.createSequentialGroup()
                .addComponent(panTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntityName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConsultationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addGroup(panConsultationLayout.createSequentialGroup()
                                .addComponent(panAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panConsultationLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panConsultationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearch)
                            .addComponent(panFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTableConsultList, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panConsultation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panConsultation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseMoved
        panAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnAddMouseMoved

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        panAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnSearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseMoved
        panSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchMouseMoved

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        panSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchMouseExited

    
    //<editor-fold defaultstate="collapsed" desc=" TopBar ">
    //<editor-fold defaultstate="collapsed" desc=" Explicación sobre la Barra Superior y los Botónes que la componen ">
    /*
     * ========================================================================
     * 
     * Barra Superior:
     * - Se configura el apartado de la barra superior de la aplicación como la
     *   movibilidad y transparencia de la app.
     *
     * Botónes de la Barra Superior:
     * - Se efectuán las caraterísticas visuales que poseen los botones de la 
     *   barra superior (Minimizar y Cerrar), tal como color de fondo y funcio-
     *   nalidades.
     *
     * ========================================================================
     */
    //</editor-fold>
   
    // Si se mantiene el click pulsado y se mueve a través de la pantalla.    
    private void panTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseDragged
//<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método permite mover la aplicación por toda la pantalla del
         * computador del usuario.
         */
        
        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.
        
        // Se ubica la aplicación en la nueva ubicación.
        this.setLocation(x - xx, y - xy);    }//GEN-LAST:event_panTopBarMouseDragged
    // Si se mantiene el click pulsado en la barra superior.
    private void panTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMousePressed
            //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método posee dos características:
         *      1) La opacidad de la aplicación disminuye un 20%.
         *      2) Se obtiene la ubicación del Mouse en el momento.
         */
        
        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);
        
        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panTopBarMousePressed
    // Si se deja de presionar el click sobre la barra superior.

    private void panTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panTopBarMouseReleased
//<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método devuelve la opacidad de la aplicación a su valor base.
         */
        
        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);    }//GEN-LAST:event_panTopBarMouseReleased

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmployeeMouseClicked
     //</editor-fold>   
    
    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbFilterBranch;
    private javax.swing.JComboBox<String> cmbFilterCandy;
    private javax.swing.JComboBox<String> cmbFilterCinemaRoom;
    private javax.swing.JComboBox<String> cmbFilterClient;
    private javax.swing.JComboBox<String> cmbFilterEmployee;
    private javax.swing.JComboBox<String> cmbFilterEnterprise;
    private javax.swing.JComboBox<String> cmbFilterFilm;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConsultList;
    public javax.swing.JLabel lblEntityName;
    public javax.swing.JPanel panAdd;
    public javax.swing.JPanel panConsultation;
    public javax.swing.JPanel panFilter;
    public javax.swing.JPanel panFilterBranch;
    private javax.swing.JPanel panFilterCandy;
    public javax.swing.JPanel panFilterCinemaRoom;
    private javax.swing.JPanel panFilterClient;
    public javax.swing.JPanel panFilterEmployee;
    public javax.swing.JPanel panFilterEnterprise;
    private javax.swing.JPanel panFilterFilm;
    public javax.swing.JPanel panSearch;
    public javax.swing.JPanel panTableConsultBranchList;
    public javax.swing.JPanel panTableConsultCandytList;
    public javax.swing.JPanel panTableConsultCinemaRoomList;
    public javax.swing.JPanel panTableConsultClientList;
    public javax.swing.JPanel panTableConsultEmployeeList;
    public javax.swing.JPanel panTableConsultEnterpriseList;
    public javax.swing.JPanel panTableConsultFilmList;
    public javax.swing.JPanel panTableConsultList;
    public javax.swing.JPanel panTopBar;
    private javax.swing.JScrollPane scpConsultBranchList;
    private javax.swing.JScrollPane scpConsultCandytList;
    private javax.swing.JScrollPane scpConsultClientList;
    private javax.swing.JScrollPane scpConsultEmployeeList;
    private javax.swing.JScrollPane scpConsultEnterpriseList;
    private javax.swing.JScrollPane scpConsultFilmList;
    private javax.swing.JScrollPane spcConsultCinemaRoomList;
    private javax.swing.JTable tblConsultBranchList;
    private javax.swing.JTable tblConsultCandyList;
    private javax.swing.JTable tblConsultCinemaRoomList;
    private javax.swing.JTable tblConsultClientList;
    private javax.swing.JTable tblConsultEnterpriseList;
    private javax.swing.JTable tblConsultFilmList;
    public javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
