
package views;

// Se importan las librerías a utilizar.
import views.tables.*;
import lib.SupportFunctions;

/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class EmployeeManagement extends javax.swing.JFrame {

    // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;
    
    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();
    
    /**
     * Constructor del gestor de empleados.
     */
    public EmployeeManagement() {
        
         // Inicializa todas las variables (o mejor dicho componentes) que usa el JFrame.
        initComponents();
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        // Se limpia la view inicial.
        clearEmployeeSearch();
        
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEmployeeManagement = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        sepTittle = new javax.swing.JSeparator();
        lblSucursalName = new javax.swing.JLabel();
        btnChangeBranch = new javax.swing.JButton();
        panContainerEmployee = new javax.swing.JPanel();
        panConsultList = new javax.swing.JPanel();
        scpEmployeeList = new javax.swing.JScrollPane();
        tblEmployeeList = new javax.swing.JTable();
        txtSearchIdEmployee = new javax.swing.JTextField();
        sepSearchIdEmployee = new javax.swing.JSeparator();
        txtSearchNameEmployee = new javax.swing.JTextField();
        btnSearchEmployee = new javax.swing.JButton();
        sepSearchNameEmployee = new javax.swing.JSeparator();
        cmbSearchJobEmployee = new javax.swing.JComboBox<>();
        btnClearSearchEmployee = new javax.swing.JButton();
        panCRUD = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblIdEmployee = new javax.swing.JLabel();
        lblLastNameEmployee = new javax.swing.JLabel();
        lblNameEmployee = new javax.swing.JLabel();
        lblEmailEmployee = new javax.swing.JLabel();
        lblPhoneEmployee = new javax.swing.JLabel();
        lblBranchEmployee = new javax.swing.JLabel();
        lblJobEmployee = new javax.swing.JLabel();
        lblDirectionEmployee = new javax.swing.JLabel();
        dchBirthEmployee = new com.toedter.calendar.JDateChooser();
        lblBirthEmployee = new javax.swing.JLabel();
        lblEntranceDateEmployee = new javax.swing.JLabel();
        dchEntranceDateEmployee = new com.toedter.calendar.JDateChooser();
        lblPicture = new javax.swing.JLabel();
        lblPictureEmployee = new javax.swing.JLabel();
        txtIdEmployee = new javax.swing.JTextField();
        txtNameEmployee = new javax.swing.JTextField();
        txtLastNameEmployee = new javax.swing.JTextField();
        txtDirectionEmployee = new javax.swing.JTextField();
        txtPhoneEmployee = new javax.swing.JTextField();
        txtEmailEmployee = new javax.swing.JTextField();
        cmbJobEmployee = new javax.swing.JComboBox<>();
        cmbBranchEmployee = new javax.swing.JComboBox<>();
        btnChargePicture = new javax.swing.JButton();
        btnClearPicture = new javax.swing.JButton();
        btnClearEmployee = new javax.swing.JButton();
        btnRegisterModifyEmployee = new javax.swing.JButton();
        btnBackEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panEmployeeManagement.setBackground(new java.awt.Color(249, 249, 249));
        panEmployeeManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 0, 145)));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.setPreferredSize(new java.awt.Dimension(215, 40));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsTopBarLayout.createSequentialGroup()
                .addGroup(panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMin)
                    .addComponent(btnExit))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lblTittle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle.setText("Gestión de empleados");
        lblTittle.setToolTipText("");

        sepTittle.setBackground(new java.awt.Color(249, 249, 249));
        sepTittle.setForeground(new java.awt.Color(239, 232, 244));

        lblSucursalName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName.setText("Sucursal ");

        btnChangeBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnChangeBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shopIcon.png"))); // NOI18N
        btnChangeBranch.setToolTipText("Cambiar Sucursal");
        btnChangeBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChangeBranch.setContentAreaFilled(false);
        btnChangeBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeBranch.setFocusPainted(false);
        btnChangeBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChangeBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseMoved(evt);
            }
        });
        btnChangeBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseExited(evt);
            }
        });

        panContainerEmployee.setBackground(new java.awt.Color(249, 249, 249));
        panContainerEmployee.setLayout(new java.awt.CardLayout());

        panConsultList.setBackground(new java.awt.Color(249, 249, 249));

        tblEmployeeList.setBackground(new java.awt.Color(249, 249, 249));
        tblEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre y Apellido", "Sucursal", "Cargo", "Consultar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployeeList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblEmployeeList.setSelectionBackground(new java.awt.Color(75, 0, 145));
        tblEmployeeList.getTableHeader().setReorderingAllowed(false);
        tblEmployeeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeListMouseClicked(evt);
            }
        });
        scpEmployeeList.setViewportView(tblEmployeeList);
        if (tblEmployeeList.getColumnModel().getColumnCount() > 0) {
            tblEmployeeList.getColumnModel().getColumn(4).setResizable(false);
            tblEmployeeList.getColumnModel().getColumn(4).setPreferredWidth(32);
        }

        txtSearchIdEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchIdEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchIdEmployee.setText("Cédula del empleado");
        txtSearchIdEmployee.setBorder(null);
        txtSearchIdEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchIdEmployeeMouseClicked(evt);
            }
        });
        txtSearchIdEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdEmployeeKeyTyped(evt);
            }
        });

        sepSearchIdEmployee.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdEmployee.setForeground(new java.awt.Color(75, 0, 145));

        txtSearchNameEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchNameEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchNameEmployee.setText("Nombre y apellido del empleado");
        txtSearchNameEmployee.setBorder(null);
        txtSearchNameEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchNameEmployeeMouseClicked(evt);
            }
        });
        txtSearchNameEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchNameEmployeeKeyTyped(evt);
            }
        });

        btnSearchEmployee.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchEmployee.setToolTipText(" Buscar");
        btnSearchEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchEmployee.setContentAreaFilled(false);
        btnSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEmployee.setFocusPainted(false);
        btnSearchEmployee.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchEmployeeMouseMoved(evt);
            }
        });
        btnSearchEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchEmployeeMouseExited(evt);
            }
        });

        sepSearchNameEmployee.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchNameEmployee.setForeground(new java.awt.Color(75, 0, 145));

        cmbSearchJobEmployee.setBackground(new java.awt.Color(249, 249, 249));
        cmbSearchJobEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSearchJobEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar un cargo -", "Gerente", "Coordinador de áreas comúnes", "Vendedor de golosinas", "Vendedor de boletos", "Personal de limpieza" }));
        cmbSearchJobEmployee.setBorder(null);
        cmbSearchJobEmployee.setLightWeightPopupEnabled(false);

        btnClearSearchEmployee.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchEmployee.setToolTipText("Limpiar");
        btnClearSearchEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchEmployee.setContentAreaFilled(false);
        btnClearSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchEmployee.setFocusPainted(false);
        btnClearSearchEmployee.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployeeMouseMoved(evt);
            }
        });
        btnClearSearchEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panConsultListLayout = new javax.swing.GroupLayout(panConsultList);
        panConsultList.setLayout(panConsultListLayout);
        panConsultListLayout.setHorizontalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scpEmployeeList))
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sepSearchIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchNameEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtSearchNameEmployee))
                        .addGap(29, 29, 29)
                        .addComponent(cmbSearchJobEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panConsultListLayout.setVerticalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearchEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSearchJobEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClearSearchEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                                .addComponent(txtSearchNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panConsultListLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtSearchIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdEmployee)
                            .addComponent(sepSearchNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(scpEmployeeList, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        panContainerEmployee.add(panConsultList, "card2");

        panCRUD.setBackground(new java.awt.Color(249, 249, 249));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Datos del empleado");
        lblTittle1.setToolTipText("");

        lblIdEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblIdEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblIdEmployee.setText("Cédula:");
        lblIdEmployee.setToolTipText("");

        lblLastNameEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblLastNameEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblLastNameEmployee.setText("Apellido:");
        lblLastNameEmployee.setToolTipText("");

        lblNameEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblNameEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblNameEmployee.setText("Nombre:");
        lblNameEmployee.setToolTipText("");

        lblEmailEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEmailEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblEmailEmployee.setText("Correo electrónico:");
        lblEmailEmployee.setToolTipText("");

        lblPhoneEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblPhoneEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblPhoneEmployee.setText("Teléfono:");
        lblPhoneEmployee.setToolTipText("");

        lblBranchEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblBranchEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblBranchEmployee.setText("Sucursal:");
        lblBranchEmployee.setToolTipText("");

        lblJobEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblJobEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblJobEmployee.setText("Cargo:");
        lblJobEmployee.setToolTipText("");

        lblDirectionEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblDirectionEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblDirectionEmployee.setText("Dirección:");
        lblDirectionEmployee.setToolTipText("");

        dchBirthEmployee.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthEmployee.setDateFormatString("yyyy-MM-dd");
        dchBirthEmployee.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthEmployee.setOpaque(false);

        lblBirthEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblBirthEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblBirthEmployee.setText("Fecha de nacimiento:");
        lblBirthEmployee.setToolTipText("");

        lblEntranceDateEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEntranceDateEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblEntranceDateEmployee.setText("Fecha de ingreso:");
        lblEntranceDateEmployee.setToolTipText("");

        dchEntranceDateEmployee.setBackground(new java.awt.Color(249, 249, 249));
        dchEntranceDateEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchEntranceDateEmployee.setDateFormatString("yyyy-MM-dd");
        dchEntranceDateEmployee.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchEntranceDateEmployee.setMaxSelectableDate(new java.util.Date(253370782897000L));
        dchEntranceDateEmployee.setOpaque(false);

        lblPicture.setForeground(new java.awt.Color(239, 239, 239));
        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setText("Inserte foto");
        lblPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));

        lblPictureEmployee.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblPictureEmployee.setForeground(new java.awt.Color(28, 0, 63));
        lblPictureEmployee.setText("Foto de perfil:");
        lblPictureEmployee.setToolTipText("");

        txtIdEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtIdEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEmployee.setText("Cédula del empleado");
        txtIdEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtNameEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtNameEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNameEmployee.setText("Nombre del empleado");
        txtNameEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtLastNameEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtLastNameEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLastNameEmployee.setText("Apellido del empleado");
        txtLastNameEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtDirectionEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtDirectionEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDirectionEmployee.setText("Dirección del empleado");
        txtDirectionEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtPhoneEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtPhoneEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneEmployee.setText("Teléfono del empleado");
        txtPhoneEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtEmailEmployee.setBackground(new java.awt.Color(249, 249, 249));
        txtEmailEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailEmployee.setText("Correo electrónico del empleado");
        txtEmailEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        cmbJobEmployee.setBackground(new java.awt.Color(249, 249, 249));
        cmbJobEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbJobEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar un cargo - ", "Gerente", "Coordinador de áreas comúnes", "Vendedor de golosinas", "Vendedor de boletos", "Personal de limpieza" }));
        cmbJobEmployee.setBorder(null);
        cmbJobEmployee.setLightWeightPopupEnabled(false);

        cmbBranchEmployee.setBackground(new java.awt.Color(249, 249, 249));
        cmbBranchEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbBranchEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " - Seleccionar una Sucursal - ", "Cines de Venezuela" }));
        cmbBranchEmployee.setBorder(null);
        cmbBranchEmployee.setLightWeightPopupEnabled(false);

        btnChargePicture.setBackground(new java.awt.Color(249, 249, 249));
        btnChargePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnChargePicture.setToolTipText("Cargar");
        btnChargePicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChargePicture.setContentAreaFilled(false);
        btnChargePicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChargePicture.setFocusPainted(false);
        btnChargePicture.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChargePicture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChargePictureMouseMoved(evt);
            }
        });
        btnChargePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChargePictureMouseExited(evt);
            }
        });

        btnClearPicture.setBackground(new java.awt.Color(249, 249, 249));
        btnClearPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnClearPicture.setToolTipText("Eliminar");
        btnClearPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearPicture.setContentAreaFilled(false);
        btnClearPicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearPicture.setFocusPainted(false);
        btnClearPicture.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearPicture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearPictureMouseMoved(evt);
            }
        });
        btnClearPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearPictureMouseExited(evt);
            }
        });

        btnClearEmployee.setBackground(new java.awt.Color(239, 232, 244));
        btnClearEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnClearEmployee.setText("Limpiar");
        btnClearEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearEmployee.setBorderPainted(false);
        btnClearEmployee.setContentAreaFilled(false);
        btnClearEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearEmployee.setFocusPainted(false);
        btnClearEmployee.setOpaque(true);
        btnClearEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearEmployeeMouseMoved(evt);
            }
        });
        btnClearEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearEmployeeMouseExited(evt);
            }
        });

        btnRegisterModifyEmployee.setBackground(new java.awt.Color(239, 232, 244));
        btnRegisterModifyEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterModifyEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterModifyEmployee.setText("@Registrar/Actualizar");
        btnRegisterModifyEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterModifyEmployee.setBorderPainted(false);
        btnRegisterModifyEmployee.setContentAreaFilled(false);
        btnRegisterModifyEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterModifyEmployee.setFocusPainted(false);
        btnRegisterModifyEmployee.setOpaque(true);
        btnRegisterModifyEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterModifyEmployeeMouseMoved(evt);
            }
        });
        btnRegisterModifyEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterModifyEmployeeMouseExited(evt);
            }
        });

        btnBackEmployee.setBackground(new java.awt.Color(239, 232, 244));
        btnBackEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBackEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnBackEmployee.setText("Atrás");
        btnBackEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackEmployee.setBorderPainted(false);
        btnBackEmployee.setContentAreaFilled(false);
        btnBackEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackEmployee.setFocusPainted(false);
        btnBackEmployee.setOpaque(true);
        btnBackEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBackEmployeeMouseMoved(evt);
            }
        });
        btnBackEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackEmployeeMouseExited(evt);
            }
        });

        btnDeleteEmployee.setBackground(new java.awt.Color(239, 232, 244));
        btnDeleteEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteEmployee.setText("Eliminar");
        btnDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteEmployee.setBorderPainted(false);
        btnDeleteEmployee.setContentAreaFilled(false);
        btnDeleteEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteEmployee.setFocusPainted(false);
        btnDeleteEmployee.setOpaque(true);
        btnDeleteEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeleteEmployeeMouseMoved(evt);
            }
        });
        btnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panCRUDLayout = new javax.swing.GroupLayout(panCRUD);
        panCRUD.setLayout(panCRUDLayout);
        panCRUDLayout.setHorizontalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblLastNameEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDirectionEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPhoneEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblIdEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDirectionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(lblBirthEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dchBirthEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJobEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbJobEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEntranceDateEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblBranchEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPictureEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchEntranceDateEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBranchEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChargePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClearPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addComponent(btnBackEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegisterModifyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        panCRUDLayout.setVerticalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(btnChargePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDirectionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirectionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBranchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBranchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJobEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJobEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPictureEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dchBirthEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBirthEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dchEntranceDateEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEntranceDateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterModifyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        panContainerEmployee.add(panCRUD, "card2");

        javax.swing.GroupLayout panEmployeeManagementLayout = new javax.swing.GroupLayout(panEmployeeManagement);
        panEmployeeManagement.setLayout(panEmployeeManagementLayout);
        panEmployeeManagementLayout.setHorizontalGroup(
            panEmployeeManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addComponent(sepTittle)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEmployeeManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEmployeeManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panContainerEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panEmployeeManagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        panEmployeeManagementLayout.setVerticalGroup(
            panEmployeeManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmployeeManagementLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEmployeeManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEmployeeManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainerEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEmployeeManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEmployeeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" Métodos para manipular tablas ">
    
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel de Employee Management.
     */
    public void clearEmployeeSearch(){
        
        txtSearchIdEmployee.setText("Cédula del empleado");
        txtSearchNameEmployee.setText("Nombre y apellido del empleado");
        cmbSearchJobEmployee.setSelectedIndex(0);
        clearEmployeeTable(tblEmployeeList);
        
    }
 
    /**
     * Método que retorna los valores iniciales de un JTable.
     * @param table parámetro JTable.
     */
    public void clearEmployeeTable(javax.swing.JTable table){
        this.table.buildEmployeeTable(table, null);
    }

    /**
     * Método para indicar el valor de una columna en un JTable.
     * @param column 
     */
    public void setColumnTable(int column){
        this.column = column;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la columna.
     */
    public int getColumnTable(){
        return column;
    }
    
    /**
     * Método para indicar el valor de una fila en un JTable.
     * @param row 
     */
    public void setRowTable(int row){
        this.row = row;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la fila.
     */
    public int getRowTable(){
        return row;
    }
    
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
        btnChangeBranch.addActionListener(evt);
        btnSearchEmployee.addActionListener(evt);
        btnClearSearchEmployee.addActionListener(evt);
        
        // CRUD
        btnBackEmployee.addActionListener(evt);
        btnChargePicture.addActionListener(evt);
        btnClearEmployee.addActionListener(evt);
        btnClearPicture.addActionListener(evt);
        btnDeleteEmployee.addActionListener(evt);
        btnRegisterModifyEmployee.addActionListener(evt);
        
    }
    
    /**
     * Método que permite activar los eventos del escuchador Mouse.
     * @param evt parámetro que se activa cuando el Mouse reacciona a algo.
     */
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        tblEmployeeList.addMouseListener(evt);
        
    }
    
    //</editor-fold>
    
    /**
     * Método para devolver a los valores por defecto a los elementos de la view.
     */
    public void clearView(){
               
        btnBackEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackEmployee.setForeground(new java.awt.Color(0,0,0));
        btnBackEmployee.setBackground(new java.awt.Color(239,232,244));
        
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnChangeBranch.setForeground(new java.awt.Color(0,0,0));
        btnChangeBranch.setBackground(new java.awt.Color(239,232,244));
        
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnChargePicture.setForeground(new java.awt.Color(0,0,0));
        btnChargePicture.setBackground(new java.awt.Color(239,232,244));
        
        btnClearEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearEmployee.setForeground(new java.awt.Color(0,0,0));
        btnClearEmployee.setBackground(new java.awt.Color(239,232,244));
        
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearPicture.setForeground(new java.awt.Color(0,0,0));
        btnClearPicture.setBackground(new java.awt.Color(239,232,244));
        
        btnClearSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearSearchEmployee.setForeground(new java.awt.Color(0,0,0));
        btnClearSearchEmployee.setBackground(new java.awt.Color(239,232,244));
        
        btnDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteEmployee.setForeground(new java.awt.Color(0,0,0));
        btnDeleteEmployee.setBackground(new java.awt.Color(239,232,244));
        
        btnRegisterModifyEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyEmployee.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyEmployee.setBackground(new java.awt.Color(239,232,244));
        
        btnSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnSearchEmployee.setForeground(new java.awt.Color(0,0,0));
        btnSearchEmployee.setBackground(new java.awt.Color(239,232,244));
        
        cmbBranchEmployee.setSelectedIndex(0);
        cmbJobEmployee.setSelectedIndex(0);
        cmbSearchJobEmployee.setSelectedIndex(0);
        
        dchBirthEmployee.setDate(null);
        dchEntranceDateEmployee.setDate(null);
        
        txtDirectionEmployee.setText("Dirección del Empleado");
        txtEmailEmployee.setText("Correo electrónico del empleado");
        txtIdEmployee.setText("Cédula del empleado");
        txtLastNameEmployee.setText("Apellido del empleado");
        txtNameEmployee.setText("Nombre del empleado");
        txtPhoneEmployee.setText("Teléfono del empleado");
        
        // Búsqueda
        txtSearchIdEmployee.setText("Cédula del empleado");
        txtSearchNameEmployee.setText("Nombre y apellido del empleado");
        
    }
    
    //<editor-fold defaultstate="collapsed" desc=" Top Bar ">
    
    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnChangeBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseMoved
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChangeBranchMouseMoved

    private void btnChangeBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseExited
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChangeBranchMouseExited

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método posee dos características:
         *      1) La opacidad de la aplicación disminuye un 20%.
         *      2) Se obtiene la ubicación del Mouse en el momento.
         */
        
        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);
        
        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método devuelve la opacidad de la aplicación a su valor base.
         */
        
        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
         * Este método permite mover la aplicación por toda la pantalla del
         * computador del usuario.
         */
        
        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.
        
        // Se ubica la aplicación en la nueva ubicación.
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Search Employee ">
    
    private void txtSearchIdEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchIdEmployeeMouseClicked
        txtSearchIdEmployee.setText("");
    }//GEN-LAST:event_txtSearchIdEmployeeMouseClicked

    private void txtSearchIdEmployeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdEmployeeKeyTyped
        /*if(txtSearchIdEmployee.getText().length() < 10)
            support.integerPositiveKeyTyped(evt);
        else
            evt.consume();*/
    }//GEN-LAST:event_txtSearchIdEmployeeKeyTyped

    private void txtSearchNameEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchNameEmployeeMouseClicked
        txtSearchNameEmployee.setText("");
    }//GEN-LAST:event_txtSearchNameEmployeeMouseClicked

    private void txtSearchNameEmployeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameEmployeeKeyTyped
        //support.alphabetKeyTyped(evt);
    }//GEN-LAST:event_txtSearchNameEmployeeKeyTyped

    private void btnSearchEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployeeMouseMoved
        btnSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchEmployeeMouseMoved

    private void btnSearchEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployeeMouseExited
        btnSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchEmployeeMouseExited

    private void btnClearSearchEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployeeMouseMoved
        btnClearSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchEmployeeMouseMoved

    private void btnClearSearchEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployeeMouseExited
        btnClearSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchEmployeeMouseExited

    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" CRUD Employee">
    
    private void btnChargePictureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargePictureMouseMoved
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChargePictureMouseMoved

    private void btnChargePictureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargePictureMouseExited
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChargePictureMouseExited

    private void btnClearPictureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearPictureMouseMoved
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearPictureMouseMoved

    private void btnClearPictureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearPictureMouseExited
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearPictureMouseExited

    private void btnClearEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEmployeeMouseMoved
        btnClearEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnClearEmployee.setForeground(new java.awt.Color(255,255,255));
        btnClearEmployee.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnClearEmployeeMouseMoved

    private void btnClearEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEmployeeMouseExited
        btnClearEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearEmployee.setForeground(new java.awt.Color(0,0,0));
        btnClearEmployee.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnClearEmployeeMouseExited

    private void btnRegisterModifyEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyEmployeeMouseMoved
        btnRegisterModifyEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnRegisterModifyEmployee.setForeground(new java.awt.Color(255,255,255));
        btnRegisterModifyEmployee.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnRegisterModifyEmployeeMouseMoved

    private void btnRegisterModifyEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyEmployeeMouseExited
        btnRegisterModifyEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyEmployee.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyEmployee.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnRegisterModifyEmployeeMouseExited

    private void btnBackEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackEmployeeMouseMoved
        btnBackEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnBackEmployee.setForeground(new java.awt.Color(255,255,255));
        btnBackEmployee.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnBackEmployeeMouseMoved

    private void btnBackEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackEmployeeMouseExited
        btnBackEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackEmployee.setForeground(new java.awt.Color(0,0,0));
        btnBackEmployee.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnBackEmployeeMouseExited

    private void btnDeleteEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeMouseMoved
        btnDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnDeleteEmployee.setForeground(new java.awt.Color(255,255,255));
        btnDeleteEmployee.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnDeleteEmployeeMouseMoved

    private void btnDeleteEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeMouseExited
        btnDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteEmployee.setForeground(new java.awt.Color(0,0,0));
        btnDeleteEmployee.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnDeleteEmployeeMouseExited

    private void tblEmployeeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeListMouseClicked
        setColumnTable(tblEmployeeList.getColumnModel().getColumnIndexAtX(evt.getX()));
        setRowTable(evt.getY()/tblEmployeeList.getRowHeight());
    }//GEN-LAST:event_tblEmployeeListMouseClicked

    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Declaración de variables ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBackEmployee;
    public javax.swing.JButton btnChangeBranch;
    public javax.swing.JButton btnChargePicture;
    public javax.swing.JButton btnClearEmployee;
    public javax.swing.JButton btnClearPicture;
    public javax.swing.JButton btnClearSearchEmployee;
    public javax.swing.JButton btnDeleteEmployee;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnRegisterModifyEmployee;
    public javax.swing.JButton btnSearchEmployee;
    public javax.swing.JComboBox<String> cmbBranchEmployee;
    public javax.swing.JComboBox<String> cmbJobEmployee;
    public javax.swing.JComboBox<String> cmbSearchJobEmployee;
    public com.toedter.calendar.JDateChooser dchBirthEmployee;
    public com.toedter.calendar.JDateChooser dchEntranceDateEmployee;
    private javax.swing.JLabel lblBirthEmployee;
    private javax.swing.JLabel lblBranchEmployee;
    private javax.swing.JLabel lblDirectionEmployee;
    private javax.swing.JLabel lblEmailEmployee;
    private javax.swing.JLabel lblEntranceDateEmployee;
    private javax.swing.JLabel lblIdEmployee;
    private javax.swing.JLabel lblJobEmployee;
    private javax.swing.JLabel lblLastNameEmployee;
    private javax.swing.JLabel lblNameEmployee;
    private javax.swing.JLabel lblPhoneEmployee;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPictureEmployee;
    public javax.swing.JLabel lblSucursalName;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panCRUD;
    public javax.swing.JPanel panConsultList;
    public javax.swing.JPanel panContainerEmployee;
    private javax.swing.JPanel panEmployeeManagement;
    private javax.swing.JScrollPane scpEmployeeList;
    private javax.swing.JSeparator sepSearchIdEmployee;
    private javax.swing.JSeparator sepSearchNameEmployee;
    private javax.swing.JSeparator sepTittle;
    public javax.swing.JTable tblEmployeeList;
    public javax.swing.JTextField txtDirectionEmployee;
    public javax.swing.JTextField txtEmailEmployee;
    public javax.swing.JTextField txtIdEmployee;
    public javax.swing.JTextField txtLastNameEmployee;
    public javax.swing.JTextField txtNameEmployee;
    public javax.swing.JTextField txtPhoneEmployee;
    public javax.swing.JTextField txtSearchIdEmployee;
    public javax.swing.JTextField txtSearchNameEmployee;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
