/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;
// Se importan las librerías a utilizar.
import views.tables.*;
import lib.SupportFunctions;

/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class EnterpriseManagement extends javax.swing.JFrame {
// Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;
    
    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();
    
    /**
     * Constructor del gestor de empresas.
     */
    public EnterpriseManagement() {
        // Inicializa todas las variables (o mejor dicho componentes) que usa el JFrame.
        initComponents();
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        // Se limpia la view inicial.
        clearEnterpriseSearch();
        
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEnterpriseManagement = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        sepTittle = new javax.swing.JSeparator();
        lblSucursalName = new javax.swing.JLabel();
        btnChangeBranch = new javax.swing.JButton();
        panContainerEnterprise = new javax.swing.JPanel();
        panConsultList = new javax.swing.JPanel();
        scpEnterpriseList = new javax.swing.JScrollPane();
        tblEnterpriseList = new javax.swing.JTable();
        txtSearchIdEnterprise = new javax.swing.JTextField();
        sepSearchIdEnterprise = new javax.swing.JSeparator();
        txtSearchNameEnterprise = new javax.swing.JTextField();
        btnSearchEnterprise = new javax.swing.JButton();
        sepSearchNameEnterprise = new javax.swing.JSeparator();
        btnClearSearchEnterprise = new javax.swing.JButton();
        panCRUD = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblIdEnterprise = new javax.swing.JLabel();
        lblDescriptionEnterprise = new javax.swing.JLabel();
        lblNameEnterprise = new javax.swing.JLabel();
        lblPriceTicketEnterprise = new javax.swing.JLabel();
        lblEmailEnterprise = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblPictureEnterprise = new javax.swing.JLabel();
        txtIdEnterprise = new javax.swing.JTextField();
        txtNameEnterprise = new javax.swing.JTextField();
        txtDescriptionEnterprise = new javax.swing.JTextField();
        txtEmailEnterprise = new javax.swing.JTextField();
        txtPriceTicketEnterprise = new javax.swing.JTextField();
        btnChargePicture = new javax.swing.JButton();
        btnClearPicture = new javax.swing.JButton();
        btnClearEnterprise = new javax.swing.JButton();
        btnRegisterModifyEnterprise = new javax.swing.JButton();
        btnBackEnterprise = new javax.swing.JButton();
        btnDeleteEnterprise = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panEnterpriseManagement.setBackground(new java.awt.Color(249, 249, 249));
        panEnterpriseManagement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 0, 145)));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.setPreferredSize(new java.awt.Dimension(215, 40));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(14, 14, 14))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonsTopBarLayout.createSequentialGroup()
                .addGroup(panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMin)
                    .addComponent(btnExit))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lblTittle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle.setText("Gestión de empresa");
        lblTittle.setToolTipText("");

        sepTittle.setBackground(new java.awt.Color(249, 249, 249));
        sepTittle.setForeground(new java.awt.Color(239, 232, 244));

        lblSucursalName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName.setText("Sucursal ");

        btnChangeBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnChangeBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/shopIcon.png"))); // NOI18N
        btnChangeBranch.setToolTipText("Cambiar Sucursal");
        btnChangeBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChangeBranch.setContentAreaFilled(false);
        btnChangeBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeBranch.setFocusPainted(false);
        btnChangeBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChangeBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseMoved(evt);
            }
        });
        btnChangeBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeBranchMouseExited(evt);
            }
        });

        panContainerEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        panContainerEnterprise.setLayout(new java.awt.CardLayout());

        panConsultList.setBackground(new java.awt.Color(249, 249, 249));

        tblEnterpriseList.setBackground(new java.awt.Color(249, 249, 249));
        tblEnterpriseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Correo", "Precio Boleto", "Consultar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnterpriseList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblEnterpriseList.setSelectionBackground(new java.awt.Color(75, 0, 145));
        tblEnterpriseList.getTableHeader().setReorderingAllowed(false);
        tblEnterpriseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnterpriseListMouseClicked(evt);
            }
        });
        scpEnterpriseList.setViewportView(tblEnterpriseList);
        if (tblEnterpriseList.getColumnModel().getColumnCount() > 0) {
            tblEnterpriseList.getColumnModel().getColumn(5).setResizable(false);
        }

        txtSearchIdEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchIdEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchIdEnterprise.setText("Codigo de la empresa");
        txtSearchIdEnterprise.setBorder(null);
        txtSearchIdEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchIdEnterpriseMouseClicked(evt);
            }
        });
        txtSearchIdEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIdEnterpriseActionPerformed(evt);
            }
        });
        txtSearchIdEnterprise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdEnterpriseKeyTyped(evt);
            }
        });

        sepSearchIdEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdEnterprise.setForeground(new java.awt.Color(75, 0, 145));

        txtSearchNameEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchNameEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchNameEnterprise.setText("Nombre de la empresa");
        txtSearchNameEnterprise.setBorder(null);
        txtSearchNameEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchNameEnterpriseMouseClicked(evt);
            }
        });
        txtSearchNameEnterprise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchNameEnterpriseKeyTyped(evt);
            }
        });

        btnSearchEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchEnterprise.setToolTipText(" Buscar");
        btnSearchEnterprise.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchEnterprise.setContentAreaFilled(false);
        btnSearchEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEnterprise.setFocusPainted(false);
        btnSearchEnterprise.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchEnterpriseMouseMoved(evt);
            }
        });
        btnSearchEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchEnterpriseMouseExited(evt);
            }
        });

        sepSearchNameEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchNameEnterprise.setForeground(new java.awt.Color(75, 0, 145));

        btnClearSearchEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchEnterprise.setToolTipText("Limpiar");
        btnClearSearchEnterprise.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchEnterprise.setContentAreaFilled(false);
        btnClearSearchEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchEnterprise.setFocusPainted(false);
        btnClearSearchEnterprise.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchEnterpriseMouseMoved(evt);
            }
        });
        btnClearSearchEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchEnterpriseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panConsultListLayout = new javax.swing.GroupLayout(panConsultList);
        panConsultList.setLayout(panConsultListLayout);
        panConsultListLayout.setHorizontalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scpEnterpriseList))
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sepSearchIdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchIdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchNameEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtSearchNameEnterprise))
                        .addGap(279, 279, 279)
                        .addComponent(btnSearchEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearSearchEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panConsultListLayout.setVerticalGroup(
            panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultListLayout.createSequentialGroup()
                .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultListLayout.createSequentialGroup()
                                .addComponent(txtSearchNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panConsultListLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtSearchIdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdEnterprise)
                            .addComponent(sepSearchNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panConsultListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panConsultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearSearchEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(scpEnterpriseList, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        panContainerEnterprise.add(panConsultList, "card2");

        panCRUD.setBackground(new java.awt.Color(249, 249, 249));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Datos de la empresa");
        lblTittle1.setToolTipText("");

        lblIdEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblIdEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblIdEnterprise.setText("Codigo:");
        lblIdEnterprise.setToolTipText("");

        lblDescriptionEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblDescriptionEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblDescriptionEnterprise.setText("Descripcion:");
        lblDescriptionEnterprise.setToolTipText("");

        lblNameEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblNameEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblNameEnterprise.setText("Nombre:");
        lblNameEnterprise.setToolTipText("");

        lblPriceTicketEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblPriceTicketEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblPriceTicketEnterprise.setText("Precio Boleto:");
        lblPriceTicketEnterprise.setToolTipText("");

        lblEmailEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEmailEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblEmailEnterprise.setText("Correo:");
        lblEmailEnterprise.setToolTipText("");

        lblPicture.setForeground(new java.awt.Color(239, 239, 239));
        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setText("Inserte foto");
        lblPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 239, 239), 1, true));

        lblPictureEnterprise.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblPictureEnterprise.setForeground(new java.awt.Color(28, 0, 63));
        lblPictureEnterprise.setText("Logo de la empresa:");
        lblPictureEnterprise.setToolTipText("");

        txtIdEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtIdEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEnterprise.setText("Codigo de la empresa");
        txtIdEnterprise.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtNameEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtNameEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNameEnterprise.setText("Nombre de la empresa");
        txtNameEnterprise.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtDescriptionEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtDescriptionEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescriptionEnterprise.setText("Descripcion de la empresa");
        txtDescriptionEnterprise.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtEmailEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtEmailEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmailEnterprise.setText("Correo electronico de la empresa");
        txtEmailEnterprise.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        txtPriceTicketEnterprise.setBackground(new java.awt.Color(249, 249, 249));
        txtPriceTicketEnterprise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPriceTicketEnterprise.setText("Precio base boleto de funciones");
        txtPriceTicketEnterprise.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(75, 0, 145)));

        btnChargePicture.setBackground(new java.awt.Color(249, 249, 249));
        btnChargePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnChargePicture.setToolTipText("Cargar");
        btnChargePicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnChargePicture.setContentAreaFilled(false);
        btnChargePicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChargePicture.setFocusPainted(false);
        btnChargePicture.setPreferredSize(new java.awt.Dimension(50, 50));
        btnChargePicture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChargePictureMouseMoved(evt);
            }
        });
        btnChargePicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChargePictureMouseExited(evt);
            }
        });

        btnClearPicture.setBackground(new java.awt.Color(249, 249, 249));
        btnClearPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnClearPicture.setToolTipText("Eliminar");
        btnClearPicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearPicture.setContentAreaFilled(false);
        btnClearPicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearPicture.setFocusPainted(false);
        btnClearPicture.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearPicture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearPictureMouseMoved(evt);
            }
        });
        btnClearPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearPictureMouseExited(evt);
            }
        });

        btnClearEnterprise.setBackground(new java.awt.Color(239, 232, 244));
        btnClearEnterprise.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClearEnterprise.setText("Limpiar");
        btnClearEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearEnterprise.setBorderPainted(false);
        btnClearEnterprise.setContentAreaFilled(false);
        btnClearEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearEnterprise.setFocusPainted(false);
        btnClearEnterprise.setOpaque(true);
        btnClearEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearEnterpriseMouseMoved(evt);
            }
        });
        btnClearEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearEnterpriseMouseExited(evt);
            }
        });

        btnRegisterModifyEnterprise.setBackground(new java.awt.Color(239, 232, 244));
        btnRegisterModifyEnterprise.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterModifyEnterprise.setText("@Registrar/Actualizar");
        btnRegisterModifyEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterModifyEnterprise.setBorderPainted(false);
        btnRegisterModifyEnterprise.setContentAreaFilled(false);
        btnRegisterModifyEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterModifyEnterprise.setFocusPainted(false);
        btnRegisterModifyEnterprise.setOpaque(true);
        btnRegisterModifyEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterModifyEnterpriseMouseMoved(evt);
            }
        });
        btnRegisterModifyEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterModifyEnterpriseMouseExited(evt);
            }
        });

        btnBackEnterprise.setBackground(new java.awt.Color(239, 232, 244));
        btnBackEnterprise.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBackEnterprise.setText("Atrás");
        btnBackEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackEnterprise.setBorderPainted(false);
        btnBackEnterprise.setContentAreaFilled(false);
        btnBackEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackEnterprise.setFocusPainted(false);
        btnBackEnterprise.setOpaque(true);
        btnBackEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBackEnterpriseMouseMoved(evt);
            }
        });
        btnBackEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackEnterpriseMouseExited(evt);
            }
        });
        btnBackEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEnterpriseActionPerformed(evt);
            }
        });

        btnDeleteEnterprise.setBackground(new java.awt.Color(239, 232, 244));
        btnDeleteEnterprise.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeleteEnterprise.setText("Eliminar");
        btnDeleteEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeleteEnterprise.setBorderPainted(false);
        btnDeleteEnterprise.setContentAreaFilled(false);
        btnDeleteEnterprise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteEnterprise.setFocusPainted(false);
        btnDeleteEnterprise.setOpaque(true);
        btnDeleteEnterprise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeleteEnterpriseMouseMoved(evt);
            }
        });
        btnDeleteEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteEnterpriseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panCRUDLayout = new javax.swing.GroupLayout(panCRUD);
        panCRUD.setLayout(panCRUDLayout);
        panCRUDLayout.setHorizontalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCRUDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addComponent(btnBackEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegisterModifyEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblDescriptionEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEmailEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPriceTicketEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblIdEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPriceTicketEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescriptionEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGap(454, 454, 454)
                                .addComponent(lblPictureEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChargePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClearPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panCRUDLayout.setVerticalGroup(
            panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCRUDLayout.createSequentialGroup()
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNameEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCRUDLayout.createSequentialGroup()
                                .addComponent(btnChargePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescriptionEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescriptionEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPriceTicketEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPriceTicketEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPictureEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(panCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterModifyEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        panContainerEnterprise.add(panCRUD, "card2");

        javax.swing.GroupLayout panEnterpriseManagementLayout = new javax.swing.GroupLayout(panEnterpriseManagement);
        panEnterpriseManagement.setLayout(panEnterpriseManagementLayout);
        panEnterpriseManagementLayout.setHorizontalGroup(
            panEnterpriseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
            .addComponent(sepTittle)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEnterpriseManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEnterpriseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panContainerEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panEnterpriseManagementLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        panEnterpriseManagementLayout.setVerticalGroup(
            panEnterpriseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEnterpriseManagementLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEnterpriseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEnterpriseManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSucursalName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContainerEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEnterpriseManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panEnterpriseManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc=" Métodos para manipular tablas ">
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel de Enterprise Management.
     */
    public void clearEnterpriseSearch(){
        
        txtSearchIdEnterprise.setText("Codigo de la empresa");
        txtSearchNameEnterprise.setText("Nombre de la empresa");
        //cmbSearchJobEmployee.setSelectedIndex(0);
        clearEnterpriseTable(tblEnterpriseList);
        
    }
 
    /**
     * Método que retorna los valores iniciales de un JTable.
     * @param table parámetro JTable.
     */
    public void clearEnterpriseTable(javax.swing.JTable table){
        this.table.buildEnterpriseTable(table, null);
    }

    /**
     * Método para indicar el valor de una columna en un JTable.
     * @param column 
     */
    public void setColumnTable(int column){
        this.column = column;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la columna.
     */
    public int getColumnTable(){
        return column;
    }
    
    /**
     * Método para indicar el valor de una fila en un JTable.
     * @param row 
     */
    public void setRowTable(int row){
        this.row = row;
    }
    
    /**
     * Método para obtener el valor de una columna en un JTable.
     * @return el valor de la fila.
     */
    public int getRowTable(){
        return row;
    }
    
    
      //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
       // btnChangeBranch.addActionListener(evt);
        btnSearchEnterprise.addActionListener(evt);
        btnClearSearchEnterprise.addActionListener(evt);
        
        // CRUD
        btnBackEnterprise.addActionListener(evt);
        btnChargePicture.addActionListener(evt);
        btnClearEnterprise.addActionListener(evt);
        btnClearPicture.addActionListener(evt);
        btnDeleteEnterprise.addActionListener(evt);
        btnRegisterModifyEnterprise.addActionListener(evt);
        
    }
    
    /**
     * Método que permite activar los eventos del escuchador Mouse.
     * @param evt parámetro que se activa cuando el Mouse reacciona a algo.
     */
    public void addMouseEvents(java.awt.event.MouseListener evt){
        
        tblEnterpriseList.addMouseListener(evt);
        
    }
    
     //</editor-fold>
    
/**
     * Método para devolver a los valores por defecto a los elementos de la view.
     */
    public void clearView(){
               
        btnBackEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnBackEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        //btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        //btnChangeBranch.setForeground(new java.awt.Color(0,0,0));
        //btnChangeBranch.setBackground(new java.awt.Color(239,232,244));
        
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnChargePicture.setForeground(new java.awt.Color(0,0,0));
        btnChargePicture.setBackground(new java.awt.Color(239,232,244));
        
        btnClearEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnClearEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearPicture.setForeground(new java.awt.Color(0,0,0));
        btnClearPicture.setBackground(new java.awt.Color(239,232,244));
        
        btnClearSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearSearchEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnClearSearchEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        btnDeleteEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnDeleteEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        btnRegisterModifyEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        btnSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnSearchEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnSearchEnterprise.setBackground(new java.awt.Color(239,232,244));
        
        //cmbBranchEmployee.setSelectedIndex(0);
        //cmbJobEmployee.setSelectedIndex(0);
        //cmbSearchJobEmployee.setSelectedIndex(0);
        
        //dchBirthEmployee.setDate(null);
        //dchEntranceDateEmployee.setDate(null);
        
        txtIdEnterprise.setText("Codigo de la empresa");
        txtNameEnterprise.setText("Nombre de la empresa");
        txtDescriptionEnterprise.setText("Descripcion de la empresa");
        txtEmailEnterprise.setText("Correo electronico de la empresa");
        txtPriceTicketEnterprise.setText("Precio base boleto de funciones");
        
        // Búsqueda
        txtSearchIdEnterprise.setText("Código de la empresa");
        txtSearchNameEnterprise.setText("Nombre de la empresa");
        
    }
    //<editor-fold defaultstate="collapsed" desc=" Top Bar "> 
    
    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        xx = evt.getX(); // Ubicación con respecto al eje X.
        xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void btnChangeBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseMoved
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChangeBranchMouseMoved

    private void btnChangeBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeBranchMouseExited
        btnChangeBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChangeBranchMouseExited
//</editor-fold>
    /*
    private void tblEnterpriseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnterpriseListMouseClicked
        setColumnTable(tblEnterpriseList.getColumnModel().getColumnIndexAtX(evt.getX()));
        setRowTable(evt.getY()/tblEnterpriseList.getRowHeight());
    }//GEN-LAST:event_tblEnterpriseListMouseClicked
    */
//<editor-fold defaultstate="collapsed" desc=" Search Enterprise ">
    private void txtSearchIdEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchIdEnterpriseMouseClicked
        txtSearchIdEnterprise.setText("");
    }//GEN-LAST:event_txtSearchIdEnterpriseMouseClicked

    private void txtSearchIdEnterpriseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdEnterpriseKeyTyped
        /*if(txtSearchIdEmployee.getText().length() < 10)
        support.integerPositiveKeyTyped(evt);
        else
        evt.consume();*/
    }//GEN-LAST:event_txtSearchIdEnterpriseKeyTyped

    private void txtSearchNameEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchNameEnterpriseMouseClicked
        txtSearchNameEnterprise.setText("");
    }//GEN-LAST:event_txtSearchNameEnterpriseMouseClicked

    private void txtSearchNameEnterpriseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameEnterpriseKeyTyped
        //support.alphabetKeyTyped(evt);
    }//GEN-LAST:event_txtSearchNameEnterpriseKeyTyped

    private void btnSearchEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEnterpriseMouseMoved
        btnSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchEnterpriseMouseMoved

    private void btnSearchEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEnterpriseMouseExited
        btnSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchEnterpriseMouseExited

    private void btnClearSearchEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEnterpriseMouseMoved
        btnClearSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchEnterpriseMouseMoved

    private void btnClearSearchEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEnterpriseMouseExited
        btnClearSearchEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchEnterpriseMouseExited
//</editor-fold>
 
//<editor-fold defaultstate="collapsed" desc=" CRUD Enterprise">   
    private void btnChargePictureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargePictureMouseMoved
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnChargePictureMouseMoved

    private void btnChargePictureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChargePictureMouseExited
        btnChargePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnChargePictureMouseExited

    private void btnClearPictureMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearPictureMouseMoved
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearPictureMouseMoved

    private void btnClearPictureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearPictureMouseExited
        btnClearPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearPictureMouseExited

    private void btnClearEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEnterpriseMouseMoved
        btnClearEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnClearEnterprise.setForeground(new java.awt.Color(255,255,255));
        btnClearEnterprise.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnClearEnterpriseMouseMoved

    private void btnClearEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearEnterpriseMouseExited
        btnClearEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnClearEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnClearEnterprise.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnClearEnterpriseMouseExited

    private void btnRegisterModifyEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyEnterpriseMouseMoved
        btnRegisterModifyEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnRegisterModifyEnterprise.setForeground(new java.awt.Color(255,255,255));
        btnRegisterModifyEnterprise.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnRegisterModifyEnterpriseMouseMoved

    private void btnRegisterModifyEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterModifyEnterpriseMouseExited
        btnRegisterModifyEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterModifyEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnRegisterModifyEnterprise.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnRegisterModifyEnterpriseMouseExited

    private void btnBackEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackEnterpriseMouseMoved
        btnBackEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnBackEnterprise.setForeground(new java.awt.Color(255,255,255));
        btnBackEnterprise.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnBackEnterpriseMouseMoved

    private void btnBackEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackEnterpriseMouseExited
        btnBackEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnBackEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnBackEnterprise.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnBackEnterpriseMouseExited

    private void btnDeleteEnterpriseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEnterpriseMouseMoved
        btnDeleteEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnDeleteEnterprise.setForeground(new java.awt.Color(255,255,255));
        btnDeleteEnterprise.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnDeleteEnterpriseMouseMoved

    private void btnDeleteEnterpriseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEnterpriseMouseExited
        btnDeleteEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnDeleteEnterprise.setForeground(new java.awt.Color(0,0,0));
        btnDeleteEnterprise.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnDeleteEnterpriseMouseExited
 
    private void tblEnterpriseListMouseClicked(java.awt.event.MouseEvent evt) {
    setColumnTable(tblEnterpriseList.getColumnModel().getColumnIndexAtX(evt.getX()));
        setRowTable(evt.getY()/tblEnterpriseList.getRowHeight());
    }
//</editor-fold>
    
    /*
    private void txtSearchIdEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIdEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIdEnterpriseActionPerformed

    private void txtIdEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEnterpriseActionPerformed

    private void btnBackEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackEnterpriseActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterpriseManagement().setVisible(true);
            }
        });
    }
//<editor-fold defaultstate="collapsed" desc=" Declaración de variables ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBackEnterprise;
    public javax.swing.JButton btnChangeBranch;
    public javax.swing.JButton btnChargePicture;
    public javax.swing.JButton btnClearEnterprise;
    public javax.swing.JButton btnClearPicture;
    public javax.swing.JButton btnClearSearchEnterprise;
    public javax.swing.JButton btnDeleteEnterprise;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnRegisterModifyEnterprise;
    public javax.swing.JButton btnSearchEnterprise;
    private javax.swing.JLabel lblDescriptionEnterprise;
    private javax.swing.JLabel lblEmailEnterprise;
    private javax.swing.JLabel lblIdEnterprise;
    private javax.swing.JLabel lblNameEnterprise;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPictureEnterprise;
    private javax.swing.JLabel lblPriceTicketEnterprise;
    public javax.swing.JLabel lblSucursalName;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panCRUD;
    public javax.swing.JPanel panConsultList;
    public javax.swing.JPanel panContainerEnterprise;
    public javax.swing.JPanel panEnterpriseManagement;
    private javax.swing.JScrollPane scpEnterpriseList;
    private javax.swing.JSeparator sepSearchIdEnterprise;
    private javax.swing.JSeparator sepSearchNameEnterprise;
    private javax.swing.JSeparator sepTittle;
    public javax.swing.JTable tblEnterpriseList;
    public javax.swing.JTextField txtDescriptionEnterprise;
    public javax.swing.JTextField txtEmailEnterprise;
    public javax.swing.JTextField txtIdEnterprise;
    public javax.swing.JTextField txtNameEnterprise;
    public javax.swing.JTextField txtPriceTicketEnterprise;
    public javax.swing.JTextField txtSearchIdEnterprise;
    public javax.swing.JTextField txtSearchNameEnterprise;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
