
package views;

import javax.swing.JTable;
import lib.SupportFunctions;
import views.tables.Table;


/**
 *
 * @author Michael Montero
 */
public class ListReports extends javax.swing.JFrame {

     // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;    

    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();   

    /**
     * Constructor del gestor de empleados.
     */
    public ListReports() {
initComponents();                
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);        
        
        // Muestra el JFrame.
        setVisible(true);        
                
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
        }

        //<editor-fold defaultstate="collapsed" desc=" Listado 1">
   public JTable getTblListClientsFrequent()
   {       
        return tblListClientsFrequent;
    }
    public void setTblListClientsFrequent(JTable tblListClientsFrequent) {
        this.tblListClientsFrequent = tblListClientsFrequent;
    } 
     //</editor-fold>
    
   //<editor-fold defaultstate="collapsed" desc=" Metodo de prueba">

   /* public void centrarColocarTamaño(JTable table,int i) 
    {
       // this.tblListClientsFrequent = tblListClientsFrequent;
    } */
     //</editor-fold>
    
        //<editor-fold defaultstate="collapsed" desc=" Listado 2">
   public JTable getTblCandyExpense()
   {       
        return tblListCandyExpenseClient;
    }
    public void setTblCandyExpense(JTable tblListCandyExpenseClient) {
        this.tblListCandyExpenseClient = tblListCandyExpenseClient;
    } 
     //</editor-fold>
    
        //<editor-fold defaultstate="collapsed" desc=" Listado 3">
   public JTable getTblListSpecialPass()
   {       
        return tblListSpecialPass;
    }
    public void setTblListSpecialPass(JTable tblListSpecialPass) {
        this.tblListSpecialPass = tblListSpecialPass;
    } 
     //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
        btnSearchClient.addActionListener(evt);
        btnClearFiltro.addActionListener(evt);
        btnSearchClient1.addActionListener(evt);
        btnClearFiltro1.addActionListener(evt);
        btnSearchClient2.addActionListener(evt);
        btnClearFiltro2.addActionListener(evt);
        
        // CRUD        
    }
         //</editor-fold>

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panReport = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panInfo = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblSucursalName1 = new javax.swing.JLabel();
        panContent = new javax.swing.JPanel();
        panListClientsFrequent = new javax.swing.JPanel();
        panSearch = new javax.swing.JPanel();
        panSearchAdmin = new javax.swing.JPanel();
        dchdate1Client = new com.toedter.calendar.JDateChooser();
        dchdate2Client = new com.toedter.calendar.JDateChooser();
        sepSearchIdBranch1 = new javax.swing.JSeparator();
        sepSearchIdBranch2 = new javax.swing.JSeparator();
        btnSearchClient = new javax.swing.JButton();
        btnClearFiltro = new javax.swing.JButton();
        panList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListClientsFrequent = new javax.swing.JTable();
        panListCandyExpenseClient = new javax.swing.JPanel();
        panSearch1 = new javax.swing.JPanel();
        panSearchAdmin1 = new javax.swing.JPanel();
        cmbOrderMonto = new javax.swing.JComboBox<>();
        cmbOrderCant = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearchClient2 = new javax.swing.JButton();
        btnClearFiltro2 = new javax.swing.JButton();
        sepSearchIdBranch3 = new javax.swing.JSeparator();
        sepSearchIdBranch4 = new javax.swing.JSeparator();
        panList1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListCandyExpenseClient = new javax.swing.JTable();
        panListSpecialPass = new javax.swing.JPanel();
        panSearch2 = new javax.swing.JPanel();
        panSearchAdmin2 = new javax.swing.JPanel();
        cmbSelecMes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSearchClient1 = new javax.swing.JButton();
        btnClearFiltro1 = new javax.swing.JButton();
        sepSearchIdBranch6 = new javax.swing.JSeparator();
        panList2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListSpecialPass = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panReport.setBackground(new java.awt.Color(249, 249, 249));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panInfo.setBackground(new java.awt.Color(249, 249, 249));
        panInfo.setPreferredSize(new java.awt.Dimension(0, 59));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Listado de Clientes frecuentes");
        lblTittle1.setToolTipText("");

        lblSucursalName1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName1.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName1.setText("Sucursal ");

        javax.swing.GroupLayout panInfoLayout = new javax.swing.GroupLayout(panInfo);
        panInfo.setLayout(panInfoLayout);
        panInfoLayout.setHorizontalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTittle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panInfoLayout.setVerticalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panContent.setLayout(new java.awt.CardLayout());

        panListClientsFrequent.setBackground(new java.awt.Color(249, 249, 249));

        panSearch.setBackground(new java.awt.Color(249, 249, 249));
        panSearch.setLayout(new java.awt.CardLayout());

        panSearchAdmin.setBackground(new java.awt.Color(249, 249, 249));

        dchdate1Client.setBackground(new java.awt.Color(249, 249, 249));
        dchdate1Client.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchdate1Client.setDateFormatString("yyyy-MM-dd");
        dchdate1Client.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchdate1Client.setOpaque(false);

        dchdate2Client.setBackground(new java.awt.Color(249, 249, 249));
        dchdate2Client.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchdate2Client.setDateFormatString("yyyy-MM-dd");
        dchdate2Client.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchdate2Client.setOpaque(false);

        sepSearchIdBranch1.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch1.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch2.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch2.setForeground(new java.awt.Color(75, 0, 145));

        btnSearchClient.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchClient.setToolTipText(" Buscar");
        btnSearchClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchClient.setContentAreaFilled(false);
        btnSearchClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchClient.setFocusPainted(false);
        btnSearchClient.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchClientMouseMoved(evt);
            }
        });
        btnSearchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchClientMouseExited(evt);
            }
        });

        btnClearFiltro.setBackground(new java.awt.Color(249, 249, 249));
        btnClearFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearFiltro.setToolTipText("Limpiar");
        btnClearFiltro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearFiltro.setContentAreaFilled(false);
        btnClearFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearFiltro.setFocusPainted(false);
        btnClearFiltro.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearFiltro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearFiltroMouseMoved(evt);
            }
        });
        btnClearFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearFiltroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panSearchAdminLayout = new javax.swing.GroupLayout(panSearchAdmin);
        panSearchAdmin.setLayout(panSearchAdminLayout);
        panSearchAdminLayout.setHorizontalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdminLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sepSearchIdBranch1)
                    .addComponent(dchdate1Client, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addComponent(dchdate2Client, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        panSearchAdminLayout.setVerticalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClearFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(btnSearchClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dchdate1Client, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dchdate2Client, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        panSearch.add(panSearchAdmin, "card2");

        tblListClientsFrequent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListClientsFrequent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Monto Gastado", "Iva", "Total", "Facturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListClientsFrequent);

        javax.swing.GroupLayout panListLayout = new javax.swing.GroupLayout(panList);
        panList.setLayout(panListLayout);
        panListLayout.setHorizontalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panListLayout.setVerticalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panListClientsFrequentLayout = new javax.swing.GroupLayout(panListClientsFrequent);
        panListClientsFrequent.setLayout(panListClientsFrequentLayout);
        panListClientsFrequentLayout.setHorizontalGroup(
            panListClientsFrequentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListClientsFrequentLayout.setVerticalGroup(
            panListClientsFrequentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListClientsFrequentLayout.createSequentialGroup()
                .addComponent(panSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListClientsFrequent, "card2");

        panListCandyExpenseClient.setBackground(new java.awt.Color(249, 249, 249));

        panSearch1.setBackground(new java.awt.Color(249, 249, 249));
        panSearch1.setLayout(new java.awt.CardLayout());

        panSearchAdmin1.setBackground(new java.awt.Color(249, 249, 249));

        cmbOrderMonto.setBackground(new java.awt.Color(249, 249, 249));
        cmbOrderMonto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbOrderMonto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "         - Seleccionar -", "Mayor a menor", "Menor a mayor" }));
        cmbOrderMonto.setBorder(null);
        cmbOrderMonto.setLightWeightPopupEnabled(false);

        cmbOrderCant.setBackground(new java.awt.Color(249, 249, 249));
        cmbOrderCant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbOrderCant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "         - Seleccionar -", "Mayor a menor", "Menor a mayor" }));
        cmbOrderCant.setBorder(null);
        cmbOrderCant.setLightWeightPopupEnabled(false);

        jLabel1.setText("Ordenar Monto Gastado de:");

        jLabel2.setText("Ordenar Cantidad de Compras de:");

        btnSearchClient2.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchClient2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchClient2.setToolTipText(" Buscar");
        btnSearchClient2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchClient2.setContentAreaFilled(false);
        btnSearchClient2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchClient2.setFocusPainted(false);
        btnSearchClient2.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchClient2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchClient2MouseMoved(evt);
            }
        });
        btnSearchClient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchClient2MouseExited(evt);
            }
        });

        btnClearFiltro2.setBackground(new java.awt.Color(249, 249, 249));
        btnClearFiltro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearFiltro2.setToolTipText("Limpiar");
        btnClearFiltro2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearFiltro2.setContentAreaFilled(false);
        btnClearFiltro2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearFiltro2.setFocusPainted(false);
        btnClearFiltro2.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearFiltro2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearFiltro2MouseMoved(evt);
            }
        });
        btnClearFiltro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearFiltro2MouseExited(evt);
            }
        });

        sepSearchIdBranch3.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch3.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch4.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch4.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panSearchAdmin1Layout = new javax.swing.GroupLayout(panSearchAdmin1);
        panSearchAdmin1.setLayout(panSearchAdmin1Layout);
        panSearchAdmin1Layout.setHorizontalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sepSearchIdBranch3)
                    .addComponent(cmbOrderMonto, 0, 202, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sepSearchIdBranch4)
                    .addComponent(cmbOrderCant, 0, 194, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchClient2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panSearchAdmin1Layout.setVerticalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdmin1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClient2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbOrderCant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cmbOrderMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdBranch3)
                            .addComponent(sepSearchIdBranch4))))
                .addGap(23, 23, 23))
        );

        panSearch1.add(panSearchAdmin1, "card2");

        panList1.setBackground(new java.awt.Color(249, 249, 249));

        tblListCandyExpenseClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Monto Gastado", "Cantidad de compras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListCandyExpenseClient);

        javax.swing.GroupLayout panList1Layout = new javax.swing.GroupLayout(panList1);
        panList1.setLayout(panList1Layout);
        panList1Layout.setHorizontalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panList1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        panList1Layout.setVerticalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panListCandyExpenseClientLayout = new javax.swing.GroupLayout(panListCandyExpenseClient);
        panListCandyExpenseClient.setLayout(panListCandyExpenseClientLayout);
        panListCandyExpenseClientLayout.setHorizontalGroup(
            panListCandyExpenseClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListCandyExpenseClientLayout.setVerticalGroup(
            panListCandyExpenseClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListCandyExpenseClientLayout.createSequentialGroup()
                .addComponent(panSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListCandyExpenseClient, "card3");

        panListSpecialPass.setBackground(new java.awt.Color(249, 249, 249));

        panSearch2.setBackground(new java.awt.Color(249, 249, 249));
        panSearch2.setLayout(new java.awt.CardLayout());

        panSearchAdmin2.setBackground(new java.awt.Color(249, 249, 249));

        cmbSelecMes.setBackground(new java.awt.Color(249, 249, 249));
        cmbSelecMes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSelecMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                - Seleccionar -", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbSelecMes.setBorder(null);
        cmbSelecMes.setLightWeightPopupEnabled(false);

        jLabel4.setText("Seleccione Mes:");

        btnSearchClient1.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchClient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchClient1.setToolTipText(" Buscar");
        btnSearchClient1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchClient1.setContentAreaFilled(false);
        btnSearchClient1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchClient1.setFocusPainted(false);
        btnSearchClient1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchClient1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchClient1MouseMoved(evt);
            }
        });
        btnSearchClient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchClient1MouseExited(evt);
            }
        });

        btnClearFiltro1.setBackground(new java.awt.Color(249, 249, 249));
        btnClearFiltro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearFiltro1.setToolTipText("Limpiar");
        btnClearFiltro1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearFiltro1.setContentAreaFilled(false);
        btnClearFiltro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearFiltro1.setFocusPainted(false);
        btnClearFiltro1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearFiltro1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearFiltro1MouseMoved(evt);
            }
        });
        btnClearFiltro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearFiltro1MouseExited(evt);
            }
        });

        sepSearchIdBranch6.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch6.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panSearchAdmin2Layout = new javax.swing.GroupLayout(panSearchAdmin2);
        panSearchAdmin2.setLayout(panSearchAdmin2Layout);
        panSearchAdmin2Layout.setHorizontalGroup(
            panSearchAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdmin2Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panSearchAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch6)
                    .addComponent(cmbSelecMes, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSearchClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panSearchAdmin2Layout.setVerticalGroup(
            panSearchAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdmin2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panSearchAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panSearchAdmin2Layout.createSequentialGroup()
                        .addGroup(panSearchAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSelecMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepSearchIdBranch6))
                    .addComponent(btnClearFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        panSearch2.add(panSearchAdmin2, "card2");

        panList2.setBackground(new java.awt.Color(249, 249, 249));

        tblListSpecialPass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblListSpecialPass);

        javax.swing.GroupLayout panList2Layout = new javax.swing.GroupLayout(panList2);
        panList2.setLayout(panList2Layout);
        panList2Layout.setHorizontalGroup(
            panList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panList2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        panList2Layout.setVerticalGroup(
            panList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panList2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panListSpecialPassLayout = new javax.swing.GroupLayout(panListSpecialPass);
        panListSpecialPass.setLayout(panListSpecialPassLayout);
        panListSpecialPassLayout.setHorizontalGroup(
            panListSpecialPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListSpecialPassLayout.setVerticalGroup(
            panListSpecialPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListSpecialPassLayout.createSequentialGroup()
                .addComponent(panSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListSpecialPass, "card3");

        javax.swing.GroupLayout panReportLayout = new javax.swing.GroupLayout(panReport);
        panReport.setLayout(panReportLayout);
        panReportLayout.setHorizontalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        panReportLayout.setVerticalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panContent, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        //  this.setLocation(x - xx, y - xy)
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        //    xx = evt.getX(); // Ubicación con respecto al eje X.
        //   xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void btnSearchClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClientMouseMoved
        btnSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchClientMouseMoved

    private void btnSearchClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClientMouseExited
        btnSearchClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchClientMouseExited

    private void btnClearFiltroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltroMouseMoved
        btnClearFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearFiltroMouseMoved

    private void btnClearFiltroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltroMouseExited
        btnClearFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearFiltroMouseExited

    private void btnSearchClient2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClient2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClient2MouseMoved

    private void btnSearchClient2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClient2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClient2MouseExited

    private void btnClearFiltro2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltro2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFiltro2MouseMoved

    private void btnClearFiltro2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltro2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFiltro2MouseExited

    private void btnSearchClient1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClient1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClient1MouseMoved

    private void btnSearchClient1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchClient1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchClient1MouseExited

    private void btnClearFiltro1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltro1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFiltro1MouseMoved

    private void btnClearFiltro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearFiltro1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFiltro1MouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClearFiltro;
    public javax.swing.JButton btnClearFiltro1;
    public javax.swing.JButton btnClearFiltro2;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnSearchClient;
    public javax.swing.JButton btnSearchClient1;
    public javax.swing.JButton btnSearchClient2;
    public javax.swing.JComboBox<String> cmbOrderCant;
    public javax.swing.JComboBox<String> cmbOrderMonto;
    public javax.swing.JComboBox<String> cmbSelecMes;
    public com.toedter.calendar.JDateChooser dchdate1Client;
    public com.toedter.calendar.JDateChooser dchdate2Client;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblSucursalName1;
    public javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panContent;
    public javax.swing.JPanel panInfo;
    private javax.swing.JPanel panList;
    private javax.swing.JPanel panList1;
    private javax.swing.JPanel panList2;
    public javax.swing.JPanel panListCandyExpenseClient;
    public javax.swing.JPanel panListClientsFrequent;
    public javax.swing.JPanel panListSpecialPass;
    private javax.swing.JPanel panReport;
    public javax.swing.JPanel panSearch;
    public javax.swing.JPanel panSearch1;
    public javax.swing.JPanel panSearch2;
    public javax.swing.JPanel panSearchAdmin;
    public javax.swing.JPanel panSearchAdmin1;
    public javax.swing.JPanel panSearchAdmin2;
    private javax.swing.JSeparator sepSearchIdBranch1;
    private javax.swing.JSeparator sepSearchIdBranch2;
    private javax.swing.JSeparator sepSearchIdBranch3;
    private javax.swing.JSeparator sepSearchIdBranch4;
    private javax.swing.JSeparator sepSearchIdBranch6;
    public javax.swing.JTable tblListCandyExpenseClient;
    public javax.swing.JTable tblListClientsFrequent;
    public javax.swing.JTable tblListSpecialPass;
    // End of variables declaration//GEN-END:variables
}
