/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;


import javax.swing.JTable;
import lib.SupportFunctions;
import views.tables.Table;
/**
 *  Materia: Laboratorio I
 *  Sección: 1
 *      Integrantes:
 *          @author Brizuela, Yurisbellys   C.I: 27.142.239
 *          @author Miranda, Marihec        C.I: 26.120.075
 *          @author Montero, Michael        C.I: 26.561.077
 *          @author Rivero, Gustavo         C.I: 26.772.857
 *          @author Torrealba, Luis         C.I: 26.121.249
 */
public class ListReportsEmployee extends javax.swing.JFrame {

     // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;    

    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();   

    /**
     * Constructor del gestor de empleados.
     */
    public ListReportsEmployee() {
        initComponents();                
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);        
        
        // Muestra el JFrame.
        setVisible(true); 
        
        
        // Se limpia la view inicial.
        clearListReportsEmployeeSearch();
        clearListReportsMonthlyEmployeeSearch();
                
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
        
    }
    
    //<editor-fold defaultstate="collapsed" desc=" Listado 1: empleados que vendieron golosinas por semanas">
   public JTable getTblListWeeklyCandySale()
   {       
        return tblListWeeklyCandySale;
    }
    public void setTblListClientsFrequent(JTable tblListWeeklyCandySale) {
        this.tblListWeeklyCandySale = tblListWeeklyCandySale;
    } 
    
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel del listado de empleados que vendieron golosinas por sememana.
     */
    public void clearListReportsEmployeeSearch(){
        
        dchStartDateWeek.setCalendar(null);
        lblEndDateWeek.setText(null);
        lblStartDateWeek.setText(null);
        
        
    }
  
    
     //</editor-fold>
    
  //<editor-fold defaultstate="collapsed" desc=" Listado 2: empleados que vendieron mas golosinas en un mes">
   public JTable getTblListMonthlyCandySale()
   {       
        return tblListMonthlyCandySale;
    }
    public void setTblListMonthlyCandySale(JTable tblListMonthlyCandySale) {
        this.tblListMonthlyCandySale = tblListMonthlyCandySale;
    } 
    
    /**
     * Método que retorna los valores iniciales de los componentes de 
     * JPanel del listado de empleados que vendieron mas golosinas en un mes.
     */
    public void clearListReportsMonthlyEmployeeSearch(){
        
        dchDateMonth.setCalendar(null);
        lblStartDateMonth.setText(null);
        lblEndDateMonth.setText(null);
        //lblEndDateWeek.setText(null);
        
        
    }
     //</editor-fold>
    
     //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search listado de venta golsoinas por semana
        btnSearchEmployee.addActionListener(evt);
        btnClearSearchEmployee.addActionListener(evt);
        
        // Search listado de venta golsoinas en un mes
        btnSearchEmployee1.addActionListener(evt);
        btnClearSearchEmployee1.addActionListener(evt);
        
        // CRUD        
    }
         //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panReport = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panInfo = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblSucursalName1 = new javax.swing.JLabel();
        panContent = new javax.swing.JPanel();
        panListWeeklyCandySale = new javax.swing.JPanel();
        panSearch = new javax.swing.JPanel();
        panSearchGerentte = new javax.swing.JPanel();
        dchBirthClient2 = new com.toedter.calendar.JDateChooser();
        dchBirthClient3 = new com.toedter.calendar.JDateChooser();
        cmbSearchCity1 = new javax.swing.JComboBox<String>();
        btnSearchBranch1 = new javax.swing.JButton();
        btnClearSearchBranch1 = new javax.swing.JButton();
        sepSearchIdBranch3 = new javax.swing.JSeparator();
        sepSearchIdBranch4 = new javax.swing.JSeparator();
        panSearchAdmin = new javax.swing.JPanel();
        dchStartDateWeek = new com.toedter.calendar.JDateChooser();
        sepSearchIdBranch = new javax.swing.JSeparator();
        sepSearchIdBranch1 = new javax.swing.JSeparator();
        sepSearchIdBranch2 = new javax.swing.JSeparator();
        btnSearchEmployee = new javax.swing.JButton();
        btnClearSearchEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEndDateWeek = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStartDateWeek = new javax.swing.JLabel();
        panList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListWeeklyCandySale = new javax.swing.JTable();
        panListMonthlyCandySale = new javax.swing.JPanel();
        panSearch1 = new javax.swing.JPanel();
        panSearchAdmin1 = new javax.swing.JPanel();
        dchDateMonth = new com.toedter.calendar.JDateChooser();
        sepSearchIdBranch5 = new javax.swing.JSeparator();
        sepSearchIdBranch6 = new javax.swing.JSeparator();
        sepSearchIdBranch7 = new javax.swing.JSeparator();
        btnSearchEmployee1 = new javax.swing.JButton();
        btnClearSearchEmployee1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStartDateMonth = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEndDateMonth = new javax.swing.JLabel();
        panSearchGerentte1 = new javax.swing.JPanel();
        dchBirthClient4 = new com.toedter.calendar.JDateChooser();
        dchBirthClient5 = new com.toedter.calendar.JDateChooser();
        cmbSearchCity2 = new javax.swing.JComboBox<String>();
        btnSearchBranch2 = new javax.swing.JButton();
        btnClearSearchBranch2 = new javax.swing.JButton();
        sepSearchIdBranch8 = new javax.swing.JSeparator();
        sepSearchIdBranch9 = new javax.swing.JSeparator();
        panList1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListMonthlyCandySale = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panReport.setBackground(new java.awt.Color(249, 249, 249));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panInfo.setBackground(new java.awt.Color(249, 249, 249));
        panInfo.setPreferredSize(new java.awt.Dimension(0, 59));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Listado de empleados");
        lblTittle1.setToolTipText("");

        lblSucursalName1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName1.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName1.setText("Sucursal ");

        javax.swing.GroupLayout panInfoLayout = new javax.swing.GroupLayout(panInfo);
        panInfo.setLayout(panInfoLayout);
        panInfoLayout.setHorizontalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTittle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panInfoLayout.setVerticalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panContent.setLayout(new java.awt.CardLayout());

        panListWeeklyCandySale.setBackground(new java.awt.Color(249, 249, 249));

        panSearch.setBackground(new java.awt.Color(249, 249, 249));
        panSearch.setLayout(new java.awt.CardLayout());

        panSearchGerentte.setBackground(new java.awt.Color(249, 249, 249));

        dchBirthClient2.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient2.setDateFormatString("yyyy-MM-dd");
        dchBirthClient2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient2.setOpaque(false);

        dchBirthClient3.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient3.setDateFormatString("yyyy-MM-dd");
        dchBirthClient3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient3.setOpaque(false);

        cmbSearchCity1.setBackground(new java.awt.Color(249, 249, 249));
        cmbSearchCity1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSearchCity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccionar una ciudad -", "Barquisimeto", "Caracas", "Maracaibo", "Punto Fijo", "Valencia" }));
        cmbSearchCity1.setBorder(null);
        cmbSearchCity1.setLightWeightPopupEnabled(false);

        btnSearchBranch1.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchBranch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchBranch1.setToolTipText(" Buscar");
        btnSearchBranch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchBranch1.setContentAreaFilled(false);
        btnSearchBranch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBranch1.setFocusPainted(false);
        btnSearchBranch1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchBranch1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchBranch1MouseMoved(evt);
            }
        });
        btnSearchBranch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchBranch1MouseExited(evt);
            }
        });
        btnSearchBranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBranch1ActionPerformed(evt);
            }
        });

        btnClearSearchBranch1.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchBranch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchBranch1.setToolTipText("Limpiar");
        btnClearSearchBranch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchBranch1.setContentAreaFilled(false);
        btnClearSearchBranch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchBranch1.setFocusPainted(false);
        btnClearSearchBranch1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchBranch1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch1MouseMoved(evt);
            }
        });
        btnClearSearchBranch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch1MouseExited(evt);
            }
        });

        sepSearchIdBranch3.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch3.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch4.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch4.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panSearchGerentteLayout = new javax.swing.GroupLayout(panSearchGerentte);
        panSearchGerentte.setLayout(panSearchGerentteLayout);
        panSearchGerentteLayout.setHorizontalGroup(
            panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearchCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnClearSearchBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panSearchGerentteLayout.setVerticalGroup(
            panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentteLayout.createSequentialGroup()
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchGerentteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSearchCity1)
                            .addComponent(dchBirthClient2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(dchBirthClient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdBranch3)
                            .addComponent(sepSearchIdBranch4)))
                    .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClearSearchBranch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addComponent(btnSearchBranch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSearch.add(panSearchGerentte, "card3");

        panSearchAdmin.setBackground(new java.awt.Color(249, 249, 249));

        dchStartDateWeek.setBackground(new java.awt.Color(249, 249, 249));
        dchStartDateWeek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchStartDateWeek.setDateFormatString("yyyy-MM-dd");
        dchStartDateWeek.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchStartDateWeek.setOpaque(false);

        sepSearchIdBranch.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch1.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch1.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch2.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch2.setForeground(new java.awt.Color(75, 0, 145));

        btnSearchEmployee.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchEmployee.setToolTipText(" Buscar");
        btnSearchEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchEmployee.setContentAreaFilled(false);
        btnSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEmployee.setFocusPainted(false);
        btnSearchEmployee.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchEmployeeMouseMoved(evt);
            }
        });
        btnSearchEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchEmployeeMouseExited(evt);
            }
        });

        btnClearSearchEmployee.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchEmployee.setToolTipText("Limpiar");
        btnClearSearchEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchEmployee.setContentAreaFilled(false);
        btnClearSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchEmployee.setFocusPainted(false);
        btnClearSearchEmployee.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployeeMouseMoved(evt);
            }
        });
        btnClearSearchEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployeeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Seleccionar fecha inicio semana:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Fecha fin semana:");

        lblEndDateWeek.setText("fecha fin");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Fecha inicio semana:");

        lblStartDateWeek.setText("fecha inicio");

        javax.swing.GroupLayout panSearchAdminLayout = new javax.swing.GroupLayout(panSearchAdmin);
        panSearchAdmin.setLayout(panSearchAdminLayout);
        panSearchAdminLayout.setHorizontalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addComponent(sepSearchIdBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sepSearchIdBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepSearchIdBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dchStartDateWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStartDateWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEndDateWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panSearchAdminLayout.setVerticalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdminLayout.createSequentialGroup()
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClearSearchEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(btnSearchEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panSearchAdminLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblStartDateWeek, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblEndDateWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panSearchAdminLayout.createSequentialGroup()
                                .addComponent(dchStartDateWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sepSearchIdBranch1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch2))
                .addGap(0, 0, 0))
        );

        panSearch.add(panSearchAdmin, "card2");

        tblListWeeklyCandySale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListWeeklyCandySale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Golosina", "Monto", "Iva", "Total vendido", "Fecha Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListWeeklyCandySale);

        javax.swing.GroupLayout panListLayout = new javax.swing.GroupLayout(panList);
        panList.setLayout(panListLayout);
        panListLayout.setHorizontalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panListLayout.setVerticalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panListWeeklyCandySaleLayout = new javax.swing.GroupLayout(panListWeeklyCandySale);
        panListWeeklyCandySale.setLayout(panListWeeklyCandySaleLayout);
        panListWeeklyCandySaleLayout.setHorizontalGroup(
            panListWeeklyCandySaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListWeeklyCandySaleLayout.setVerticalGroup(
            panListWeeklyCandySaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListWeeklyCandySaleLayout.createSequentialGroup()
                .addComponent(panSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListWeeklyCandySale, "card2");

        panListMonthlyCandySale.setBackground(new java.awt.Color(249, 249, 249));

        panSearch1.setBackground(new java.awt.Color(249, 249, 249));
        panSearch1.setLayout(new java.awt.CardLayout());

        panSearchAdmin1.setBackground(new java.awt.Color(249, 249, 249));

        dchDateMonth.setBackground(new java.awt.Color(249, 249, 249));
        dchDateMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchDateMonth.setDateFormatString("yyyy-MM-dd");
        dchDateMonth.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchDateMonth.setOpaque(false);

        sepSearchIdBranch5.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch5.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch6.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch6.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch7.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch7.setForeground(new java.awt.Color(75, 0, 145));

        btnSearchEmployee1.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchEmployee1.setToolTipText(" Buscar");
        btnSearchEmployee1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchEmployee1.setContentAreaFilled(false);
        btnSearchEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEmployee1.setFocusPainted(false);
        btnSearchEmployee1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchEmployee1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchEmployee1MouseMoved(evt);
            }
        });
        btnSearchEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchEmployee1MouseExited(evt);
            }
        });

        btnClearSearchEmployee1.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchEmployee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchEmployee1.setToolTipText("Limpiar");
        btnClearSearchEmployee1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchEmployee1.setContentAreaFilled(false);
        btnClearSearchEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchEmployee1.setFocusPainted(false);
        btnClearSearchEmployee1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchEmployee1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployee1MouseMoved(evt);
            }
        });
        btnClearSearchEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchEmployee1MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Seleccionar fecha:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Fecha inicio mes:");

        lblStartDateMonth.setText("fecha inicio");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Fecha fin mes:");

        lblEndDateMonth.setText("fecha fin");

        javax.swing.GroupLayout panSearchAdmin1Layout = new javax.swing.GroupLayout(panSearchAdmin1);
        panSearchAdmin1.setLayout(panSearchAdmin1Layout);
        panSearchAdmin1Layout.setHorizontalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addComponent(sepSearchIdBranch5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(sepSearchIdBranch6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepSearchIdBranch7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dchDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(lblStartDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblEndDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addComponent(btnSearchEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearSearchEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panSearchAdmin1Layout.setVerticalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdmin1Layout.createSequentialGroup()
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnClearSearchEmployee1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(btnSearchEmployee1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                                .addComponent(dchDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panSearchAdmin1Layout.createSequentialGroup()
                        .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStartDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sepSearchIdBranch6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch7))
                .addGap(0, 0, 0))
        );

        panSearch1.add(panSearchAdmin1, "card2");

        panSearchGerentte1.setBackground(new java.awt.Color(249, 249, 249));

        dchBirthClient4.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient4.setDateFormatString("yyyy-MM-dd");
        dchBirthClient4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient4.setOpaque(false);

        dchBirthClient5.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient5.setDateFormatString("yyyy-MM-dd");
        dchBirthClient5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient5.setOpaque(false);

        cmbSearchCity2.setBackground(new java.awt.Color(249, 249, 249));
        cmbSearchCity2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSearchCity2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Seleccionar una ciudad -", "Barquisimeto", "Caracas", "Maracaibo", "Punto Fijo", "Valencia" }));
        cmbSearchCity2.setBorder(null);
        cmbSearchCity2.setLightWeightPopupEnabled(false);

        btnSearchBranch2.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchBranch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchBranch2.setToolTipText(" Buscar");
        btnSearchBranch2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchBranch2.setContentAreaFilled(false);
        btnSearchBranch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBranch2.setFocusPainted(false);
        btnSearchBranch2.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchBranch2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchBranch2MouseMoved(evt);
            }
        });
        btnSearchBranch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchBranch2MouseExited(evt);
            }
        });
        btnSearchBranch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBranch2ActionPerformed(evt);
            }
        });

        btnClearSearchBranch2.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchBranch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchBranch2.setToolTipText("Limpiar");
        btnClearSearchBranch2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchBranch2.setContentAreaFilled(false);
        btnClearSearchBranch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchBranch2.setFocusPainted(false);
        btnClearSearchBranch2.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchBranch2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch2MouseMoved(evt);
            }
        });
        btnClearSearchBranch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch2MouseExited(evt);
            }
        });

        sepSearchIdBranch8.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch8.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch9.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch9.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panSearchGerentte1Layout = new javax.swing.GroupLayout(panSearchGerentte1);
        panSearchGerentte1.setLayout(panSearchGerentte1Layout);
        panSearchGerentte1Layout.setHorizontalGroup(
            panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentte1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient5, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearchCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnClearSearchBranch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panSearchGerentte1Layout.setVerticalGroup(
            panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentte1Layout.createSequentialGroup()
                .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchGerentte1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSearchCity2)
                            .addComponent(dchBirthClient4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(dchBirthClient5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdBranch8)
                            .addComponent(sepSearchIdBranch9)))
                    .addGroup(panSearchGerentte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClearSearchBranch2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addComponent(btnSearchBranch2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSearch1.add(panSearchGerentte1, "card3");

        tblListMonthlyCandySale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListMonthlyCandySale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Monto", "Iva", "Total vendido", "Facturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListMonthlyCandySale);

        javax.swing.GroupLayout panList1Layout = new javax.swing.GroupLayout(panList1);
        panList1.setLayout(panList1Layout);
        panList1Layout.setHorizontalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panList1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panList1Layout.setVerticalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panListMonthlyCandySaleLayout = new javax.swing.GroupLayout(panListMonthlyCandySale);
        panListMonthlyCandySale.setLayout(panListMonthlyCandySaleLayout);
        panListMonthlyCandySaleLayout.setHorizontalGroup(
            panListMonthlyCandySaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListMonthlyCandySaleLayout.setVerticalGroup(
            panListMonthlyCandySaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListMonthlyCandySaleLayout.createSequentialGroup()
                .addComponent(panSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListMonthlyCandySale, "card2");

        javax.swing.GroupLayout panReportLayout = new javax.swing.GroupLayout(panReport);
        panReport.setLayout(panReportLayout);
        panReportLayout.setHorizontalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        panReportLayout.setVerticalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        //  this.setLocation(x - xx, y - xy)
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        //    xx = evt.getX(); // Ubicación con respecto al eje X.
        //   xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void btnSearchEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployeeMouseMoved
        btnSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchEmployeeMouseMoved

    private void btnSearchEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployeeMouseExited
        btnSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchEmployeeMouseExited

    private void btnClearSearchEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployeeMouseMoved
        btnClearSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchEmployeeMouseMoved

    private void btnClearSearchEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployeeMouseExited
        btnClearSearchEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchEmployeeMouseExited

    private void btnSearchBranch1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1MouseMoved

    private void btnSearchBranch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1MouseExited

    private void btnSearchBranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBranch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1ActionPerformed

    private void btnClearSearchBranch1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch1MouseMoved

    private void btnClearSearchBranch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch1MouseExited

    private void btnSearchEmployee1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployee1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchEmployee1MouseMoved

    private void btnSearchEmployee1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchEmployee1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchEmployee1MouseExited

    private void btnClearSearchEmployee1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployee1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchEmployee1MouseMoved

    private void btnClearSearchEmployee1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchEmployee1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchEmployee1MouseExited

    private void btnSearchBranch2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch2MouseMoved

    private void btnSearchBranch2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch2MouseExited

    private void btnSearchBranch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBranch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch2ActionPerformed

    private void btnClearSearchBranch2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch2MouseMoved

    private void btnClearSearchBranch2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListReportsEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListReportsEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListReportsEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListReportsEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListReportsEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClearSearchBranch1;
    public javax.swing.JButton btnClearSearchBranch2;
    public javax.swing.JButton btnClearSearchEmployee;
    public javax.swing.JButton btnClearSearchEmployee1;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnSearchBranch1;
    public javax.swing.JButton btnSearchBranch2;
    public javax.swing.JButton btnSearchEmployee;
    public javax.swing.JButton btnSearchEmployee1;
    public javax.swing.JComboBox<String> cmbSearchCity1;
    public javax.swing.JComboBox<String> cmbSearchCity2;
    public com.toedter.calendar.JDateChooser dchBirthClient2;
    public com.toedter.calendar.JDateChooser dchBirthClient3;
    public com.toedter.calendar.JDateChooser dchBirthClient4;
    public com.toedter.calendar.JDateChooser dchBirthClient5;
    public com.toedter.calendar.JDateChooser dchDateMonth;
    public com.toedter.calendar.JDateChooser dchStartDateWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblEndDateMonth;
    public javax.swing.JLabel lblEndDateWeek;
    public javax.swing.JLabel lblStartDateMonth;
    public javax.swing.JLabel lblStartDateWeek;
    public javax.swing.JLabel lblSucursalName1;
    public javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    public javax.swing.JPanel panContent;
    public javax.swing.JPanel panInfo;
    private javax.swing.JPanel panList;
    private javax.swing.JPanel panList1;
    public javax.swing.JPanel panListMonthlyCandySale;
    public javax.swing.JPanel panListWeeklyCandySale;
    private javax.swing.JPanel panReport;
    public javax.swing.JPanel panSearch;
    public javax.swing.JPanel panSearch1;
    public javax.swing.JPanel panSearchAdmin;
    public javax.swing.JPanel panSearchAdmin1;
    private javax.swing.JPanel panSearchGerentte;
    private javax.swing.JPanel panSearchGerentte1;
    private javax.swing.JSeparator sepSearchIdBranch;
    private javax.swing.JSeparator sepSearchIdBranch1;
    private javax.swing.JSeparator sepSearchIdBranch2;
    private javax.swing.JSeparator sepSearchIdBranch3;
    private javax.swing.JSeparator sepSearchIdBranch4;
    private javax.swing.JSeparator sepSearchIdBranch5;
    private javax.swing.JSeparator sepSearchIdBranch6;
    private javax.swing.JSeparator sepSearchIdBranch7;
    private javax.swing.JSeparator sepSearchIdBranch8;
    private javax.swing.JSeparator sepSearchIdBranch9;
    public javax.swing.JTable tblListMonthlyCandySale;
    public javax.swing.JTable tblListWeeklyCandySale;
    // End of variables declaration//GEN-END:variables
}
