
package views;

import javax.swing.JTable;
import lib.SupportFunctions;
import views.tables.Table;


/**
 *
 * @author Michael Montero
 */
public class ListReports extends javax.swing.JFrame {

     // Se declaran e inicializan las variables a utilizar.
    int xx = 0, xy = 0, row = 0, column = 0;    

    // Se declaran e instancian las clases a utilizar.
    private SupportFunctions support;
    private Table table = new Table();   

    /**
     * Constructor del gestor de empleados.
     */
    public ListReports() {
initComponents();                
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);        
        
        // Muestra el JFrame.
        setVisible(true);        
                
        // Cambia el ícono del JFrame.
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());
        }

        //<editor-fold defaultstate="collapsed" desc=" Listado 1">
   public JTable getTblListClientsFrequent()
   {       
        return tblListClientsFrequent;
    }
    public void setTblListClientsFrequent(JTable tblListClientsFrequent) {
        this.tblListClientsFrequent = tblListClientsFrequent;
    } 
     //</editor-fold>
    
   //<editor-fold defaultstate="collapsed" desc=" Metodo de prueba">

   /* public void centrarColocarTamaño(JTable table,int i) 
    {
       // this.tblListClientsFrequent = tblListClientsFrequent;
    } */
     //</editor-fold>
    
        //<editor-fold defaultstate="collapsed" desc=" Listado 2">
   public JTable getTblCandyExpense()
   {       
        return tblListCandyExpenseClient;
    }
    public void setTblCandyExpense(JTable tblListCandyExpenseClient) {
        this.tblListCandyExpenseClient = tblListCandyExpenseClient;
    } 
     //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    /**
     * Método que se activa al realizar una acción (presionar click sobre algún 
     * botón) añadiendo este evento a una lista que será manejada con mayor pro-
     * fundidad en el Controlador correspondiente.
     * Este método hace uso de la clase abstracta ActionListener la cual está 
     * fuertemente vinculada a todas las acciones provocadas por botones.
     * @param evt 
     */
    public void addEvents(java.awt.event.ActionListener evt){
        
        // Top Bar
        btnExit.addActionListener(evt);
        btnMin.addActionListener(evt);
        
        // Search
        btnSearchBranch.addActionListener(evt);
        btnClearSearchBranch.addActionListener(evt);
        
        // CRUD        
    }
         //</editor-fold>

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panReport = new javax.swing.JPanel();
        panButtonsTopBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panInfo = new javax.swing.JPanel();
        lblTittle1 = new javax.swing.JLabel();
        lblSucursalName1 = new javax.swing.JLabel();
        panContent = new javax.swing.JPanel();
        panListClientsFrequent = new javax.swing.JPanel();
        panSearch = new javax.swing.JPanel();
        panSearchAdmin = new javax.swing.JPanel();
        txtSearchIdBranch = new javax.swing.JTextField();
        dchBirthClient = new com.toedter.calendar.JDateChooser();
        dchBirthClient1 = new com.toedter.calendar.JDateChooser();
        sepSearchIdBranch = new javax.swing.JSeparator();
        sepSearchIdBranch1 = new javax.swing.JSeparator();
        sepSearchIdBranch2 = new javax.swing.JSeparator();
        cmbSearchCity = new javax.swing.JComboBox<>();
        btnSearchBranch = new javax.swing.JButton();
        btnClearSearchBranch = new javax.swing.JButton();
        panSearchGerentte = new javax.swing.JPanel();
        dchBirthClient2 = new com.toedter.calendar.JDateChooser();
        dchBirthClient3 = new com.toedter.calendar.JDateChooser();
        cmbSearchCity1 = new javax.swing.JComboBox<>();
        btnSearchBranch1 = new javax.swing.JButton();
        btnClearSearchBranch1 = new javax.swing.JButton();
        sepSearchIdBranch3 = new javax.swing.JSeparator();
        sepSearchIdBranch4 = new javax.swing.JSeparator();
        panList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListClientsFrequent = new javax.swing.JTable();
        panListCandyExpenseClient = new javax.swing.JPanel();
        panSearch1 = new javax.swing.JPanel();
        panSearchAdmin1 = new javax.swing.JPanel();
        panList1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListCandyExpenseClient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panReport.setBackground(new java.awt.Color(249, 249, 249));

        panButtonsTopBar.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsTopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseDragged(evt);
            }
        });
        panButtonsTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panButtonsTopBarMouseReleased(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);

        btnExit.setBackground(new java.awt.Color(249, 249, 249));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonsTopBarLayout = new javax.swing.GroupLayout(panButtonsTopBar);
        panButtonsTopBar.setLayout(panButtonsTopBarLayout);
        panButtonsTopBarLayout.setHorizontalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonsTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panButtonsTopBarLayout.setVerticalGroup(
            panButtonsTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panInfo.setBackground(new java.awt.Color(249, 249, 249));
        panInfo.setPreferredSize(new java.awt.Dimension(0, 59));

        lblTittle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTittle1.setForeground(new java.awt.Color(28, 0, 63));
        lblTittle1.setText("Listado de Clientes frecuentes");
        lblTittle1.setToolTipText("");

        lblSucursalName1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSucursalName1.setForeground(new java.awt.Color(75, 0, 145));
        lblSucursalName1.setText("Sucursal ");

        javax.swing.GroupLayout panInfoLayout = new javax.swing.GroupLayout(panInfo);
        panInfo.setLayout(panInfoLayout);
        panInfoLayout.setHorizontalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTittle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panInfoLayout.setVerticalGroup(
            panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSucursalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panContent.setLayout(new java.awt.CardLayout());

        panListClientsFrequent.setBackground(new java.awt.Color(249, 249, 249));

        panSearch.setBackground(new java.awt.Color(249, 249, 249));
        panSearch.setLayout(new java.awt.CardLayout());

        panSearchAdmin.setBackground(new java.awt.Color(249, 249, 249));

        txtSearchIdBranch.setBackground(new java.awt.Color(249, 249, 249));
        txtSearchIdBranch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearchIdBranch.setText("Codigo de la sucursal");
        txtSearchIdBranch.setBorder(null);
        txtSearchIdBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchIdBranchMouseClicked(evt);
            }
        });
        txtSearchIdBranch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchIdBranchKeyTyped(evt);
            }
        });

        dchBirthClient.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient.setDateFormatString("yyyy-MM-dd");
        dchBirthClient.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient.setOpaque(false);

        dchBirthClient1.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient1.setDateFormatString("yyyy-MM-dd");
        dchBirthClient1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient1.setOpaque(false);

        sepSearchIdBranch.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch1.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch1.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch2.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch2.setForeground(new java.awt.Color(75, 0, 145));

        cmbSearchCity.setBackground(new java.awt.Color(249, 249, 249));
        cmbSearchCity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSearchCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar una ciudad -", "Barquisimeto", "Caracas", "Maracaibo", "Punto Fijo", "Valencia" }));
        cmbSearchCity.setBorder(null);
        cmbSearchCity.setLightWeightPopupEnabled(false);

        btnSearchBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchBranch.setToolTipText(" Buscar");
        btnSearchBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchBranch.setContentAreaFilled(false);
        btnSearchBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBranch.setFocusPainted(false);
        btnSearchBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchBranchMouseMoved(evt);
            }
        });
        btnSearchBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchBranchMouseExited(evt);
            }
        });

        btnClearSearchBranch.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchBranch.setToolTipText("Limpiar");
        btnClearSearchBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchBranch.setContentAreaFilled(false);
        btnClearSearchBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchBranch.setFocusPainted(false);
        btnClearSearchBranch.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchBranch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchBranchMouseMoved(evt);
            }
        });
        btnClearSearchBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchBranchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panSearchAdminLayout = new javax.swing.GroupLayout(panSearchAdmin);
        panSearchAdmin.setLayout(panSearchAdminLayout);
        panSearchAdminLayout.setHorizontalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearchIdBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepSearchIdBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addComponent(dchBirthClient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dchBirthClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panSearchAdminLayout.createSequentialGroup()
                        .addComponent(sepSearchIdBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepSearchIdBranch2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearSearchBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panSearchAdminLayout.setVerticalGroup(
            panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSearchAdminLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClearSearchBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dchBirthClient1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(dchBirthClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(cmbSearchCity)
                        .addComponent(txtSearchIdBranch))
                    .addComponent(btnSearchBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sepSearchIdBranch1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepSearchIdBranch2))
                .addGap(0, 0, 0))
        );

        panSearch.add(panSearchAdmin, "card2");

        panSearchGerentte.setBackground(new java.awt.Color(249, 249, 249));

        dchBirthClient2.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient2.setDateFormatString("yyyy-MM-dd");
        dchBirthClient2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient2.setOpaque(false);

        dchBirthClient3.setBackground(new java.awt.Color(249, 249, 249));
        dchBirthClient3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        dchBirthClient3.setDateFormatString("yyyy-MM-dd");
        dchBirthClient3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        dchBirthClient3.setOpaque(false);

        cmbSearchCity1.setBackground(new java.awt.Color(249, 249, 249));
        cmbSearchCity1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSearchCity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar una ciudad -", "Barquisimeto", "Caracas", "Maracaibo", "Punto Fijo", "Valencia" }));
        cmbSearchCity1.setBorder(null);
        cmbSearchCity1.setLightWeightPopupEnabled(false);

        btnSearchBranch1.setBackground(new java.awt.Color(249, 249, 249));
        btnSearchBranch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/findUserIcon.png"))); // NOI18N
        btnSearchBranch1.setToolTipText(" Buscar");
        btnSearchBranch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnSearchBranch1.setContentAreaFilled(false);
        btnSearchBranch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchBranch1.setFocusPainted(false);
        btnSearchBranch1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSearchBranch1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSearchBranch1MouseMoved(evt);
            }
        });
        btnSearchBranch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchBranch1MouseExited(evt);
            }
        });
        btnSearchBranch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBranch1ActionPerformed(evt);
            }
        });

        btnClearSearchBranch1.setBackground(new java.awt.Color(249, 249, 249));
        btnClearSearchBranch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/searchIcon.png"))); // NOI18N
        btnClearSearchBranch1.setToolTipText("Limpiar");
        btnClearSearchBranch1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 249, 249), 1, true));
        btnClearSearchBranch1.setContentAreaFilled(false);
        btnClearSearchBranch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSearchBranch1.setFocusPainted(false);
        btnClearSearchBranch1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnClearSearchBranch1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch1MouseMoved(evt);
            }
        });
        btnClearSearchBranch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearSearchBranch1MouseExited(evt);
            }
        });

        sepSearchIdBranch3.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch3.setForeground(new java.awt.Color(75, 0, 145));

        sepSearchIdBranch4.setBackground(new java.awt.Color(249, 249, 249));
        sepSearchIdBranch4.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panSearchGerentteLayout = new javax.swing.GroupLayout(panSearchGerentte);
        panSearchGerentte.setLayout(panSearchGerentteLayout);
        panSearchGerentteLayout.setHorizontalGroup(
            panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dchBirthClient3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(sepSearchIdBranch4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearchCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnClearSearchBranch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panSearchGerentteLayout.setVerticalGroup(
            panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSearchGerentteLayout.createSequentialGroup()
                .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSearchGerentteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSearchCity1)
                            .addComponent(dchBirthClient2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(dchBirthClient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sepSearchIdBranch3)
                            .addComponent(sepSearchIdBranch4)))
                    .addGroup(panSearchGerentteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClearSearchBranch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addComponent(btnSearchBranch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSearch.add(panSearchGerentte, "card3");

        tblListClientsFrequent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblListClientsFrequent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Monto Gastado", "Iva", "Total", "Facturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListClientsFrequent);

        javax.swing.GroupLayout panListLayout = new javax.swing.GroupLayout(panList);
        panList.setLayout(panListLayout);
        panListLayout.setHorizontalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panListLayout.setVerticalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panListClientsFrequentLayout = new javax.swing.GroupLayout(panListClientsFrequent);
        panListClientsFrequent.setLayout(panListClientsFrequentLayout);
        panListClientsFrequentLayout.setHorizontalGroup(
            panListClientsFrequentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListClientsFrequentLayout.setVerticalGroup(
            panListClientsFrequentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListClientsFrequentLayout.createSequentialGroup()
                .addComponent(panSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListClientsFrequent, "card2");

        panListCandyExpenseClient.setBackground(new java.awt.Color(249, 249, 249));

        panSearch1.setBackground(new java.awt.Color(249, 249, 249));
        panSearch1.setLayout(new java.awt.CardLayout());

        panSearchAdmin1.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout panSearchAdmin1Layout = new javax.swing.GroupLayout(panSearchAdmin1);
        panSearchAdmin1.setLayout(panSearchAdmin1Layout);
        panSearchAdmin1Layout.setHorizontalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        panSearchAdmin1Layout.setVerticalGroup(
            panSearchAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        panSearch1.add(panSearchAdmin1, "card2");

        panList1.setBackground(new java.awt.Color(249, 249, 249));

        tblListCandyExpenseClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblListCandyExpenseClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Monto Gastado", "Cantidad de compras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListCandyExpenseClient);

        javax.swing.GroupLayout panList1Layout = new javax.swing.GroupLayout(panList1);
        panList1.setLayout(panList1Layout);
        panList1Layout.setHorizontalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panList1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panList1Layout.setVerticalGroup(
            panList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panListCandyExpenseClientLayout = new javax.swing.GroupLayout(panListCandyExpenseClient);
        panListCandyExpenseClient.setLayout(panListCandyExpenseClientLayout);
        panListCandyExpenseClientLayout.setHorizontalGroup(
            panListCandyExpenseClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panListCandyExpenseClientLayout.setVerticalGroup(
            panListCandyExpenseClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListCandyExpenseClientLayout.createSequentialGroup()
                .addComponent(panSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panContent.add(panListCandyExpenseClient, "card3");

        javax.swing.GroupLayout panReportLayout = new javax.swing.GroupLayout(panReport);
        panReport.setLayout(panReportLayout);
        panReportLayout.setHorizontalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panButtonsTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        panReportLayout.setVerticalGroup(
            panReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportLayout.createSequentialGroup()
                .addComponent(panButtonsTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panContent, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        btnExit.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExitMouseMoved

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExitMouseExited

    private void panButtonsTopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseDragged
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método permite mover la aplicación por toda la pantalla del
        * computador del usuario.
        */

        // Se declaran las variables que obtienen la ubicación de la aplicación.
        //</editor-fold>
        int x = evt.getXOnScreen(); // Ubicación con respecto al eje X.
        int y = evt.getYOnScreen(); // Ubicación con respecto al eje Y.

        // Se ubica la aplicación en la nueva ubicación.
        //  this.setLocation(x - xx, y - xy)
    }//GEN-LAST:event_panButtonsTopBarMouseDragged

    private void panButtonsTopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMousePressed
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método posee dos características:
        *      1) La opacidad de la aplicación disminuye un 20%.
        *      2) Se obtiene la ubicación del Mouse en el momento.
        */

        // Se coloca la opacidad de la aplicación en 80%.
        //</editor-fold>
        setOpacity((float)0.8);

        // Se obtiene la ubicación del Mouse en el momento.
        //    xx = evt.getX(); // Ubicación con respecto al eje X.
        //   xy = evt.getY(); // Ubicación con respecto al eje Y.
    }//GEN-LAST:event_panButtonsTopBarMousePressed

    private void panButtonsTopBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panButtonsTopBarMouseReleased
        //<editor-fold defaultstate="collapsed" desc=" Explicación sobre el método ">
        /*
        * Este método devuelve la opacidad de la aplicación a su valor base.
        */

        // Se coloca la opacidad de la aplicación en 100%.
        //</editor-fold>
        setOpacity((float)1.0);
    }//GEN-LAST:event_panButtonsTopBarMouseReleased

    private void txtSearchIdBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchIdBranchMouseClicked
        txtSearchIdBranch.setText("");
    }//GEN-LAST:event_txtSearchIdBranchMouseClicked

    private void txtSearchIdBranchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIdBranchKeyTyped
        /*if(txtSearchIdEmployee.getText().length() < 10)
        support.integerPositiveKeyTyped(evt);
        else
        evt.consume();*/
    }//GEN-LAST:event_txtSearchIdBranchKeyTyped

    private void btnSearchBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranchMouseMoved
        btnSearchBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnSearchBranchMouseMoved

    private void btnSearchBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranchMouseExited
        btnSearchBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnSearchBranchMouseExited

    private void btnClearSearchBranchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranchMouseMoved
        btnClearSearchBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
    }//GEN-LAST:event_btnClearSearchBranchMouseMoved

    private void btnClearSearchBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranchMouseExited
        btnClearSearchBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
    }//GEN-LAST:event_btnClearSearchBranchMouseExited

    private void btnSearchBranch1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1MouseMoved

    private void btnSearchBranch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchBranch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1MouseExited

    private void btnSearchBranch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBranch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchBranch1ActionPerformed

    private void btnClearSearchBranch1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch1MouseMoved

    private void btnClearSearchBranch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearSearchBranch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearSearchBranch1MouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClearSearchBranch;
    public javax.swing.JButton btnClearSearchBranch1;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnExit1;
    public javax.swing.JButton btnMin;
    public javax.swing.JButton btnMin1;
    public javax.swing.JButton btnSearchBranch;
    public javax.swing.JButton btnSearchBranch1;
    public javax.swing.JComboBox<String> cmbSearchCity;
    public javax.swing.JComboBox<String> cmbSearchCity1;
    public com.toedter.calendar.JDateChooser dchBirthClient;
    public com.toedter.calendar.JDateChooser dchBirthClient1;
    public com.toedter.calendar.JDateChooser dchBirthClient2;
    public com.toedter.calendar.JDateChooser dchBirthClient3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblSucursalName1;
    public javax.swing.JLabel lblTittle1;
    private javax.swing.JPanel panButtonsTopBar;
    private javax.swing.JPanel panButtonsTopBar1;
    public javax.swing.JPanel panContent;
    public javax.swing.JPanel panInfo;
    private javax.swing.JPanel panList;
    private javax.swing.JPanel panList1;
    public javax.swing.JPanel panListCandyExpenseClient;
    public javax.swing.JPanel panListClientsFrequent;
    private javax.swing.JPanel panReport;
    private javax.swing.JPanel panReport1;
    public javax.swing.JPanel panSearch;
    public javax.swing.JPanel panSearch1;
    public javax.swing.JPanel panSearchAdmin;
    public javax.swing.JPanel panSearchAdmin1;
    private javax.swing.JPanel panSearchGerentte;
    private javax.swing.JSeparator sepSearchIdBranch;
    private javax.swing.JSeparator sepSearchIdBranch1;
    private javax.swing.JSeparator sepSearchIdBranch2;
    private javax.swing.JSeparator sepSearchIdBranch3;
    private javax.swing.JSeparator sepSearchIdBranch4;
    public javax.swing.JTable tblListCandyExpenseClient;
    public javax.swing.JTable tblListClientsFrequent;
    public javax.swing.JTextField txtSearchIdBranch;
    // End of variables declaration//GEN-END:variables
}
