/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import lib.SuportFunctions;

/**
 *
 * @author Marihec
 */
public class RegisterModify extends javax.swing.JFrame  {

    /**
     * Creates new form RegisterModify
     */
    
    // Luis instancia la clase de soporte. jajajaja
    private SuportFunctions suport;
    
    
    public RegisterModify() {
        
        
        initComponents();
        
        // Relaciona elementos y decide si es un contenedor modal o no.
        
        
        // Se instancia la clase de soporte.
        suport = new SuportFunctions();
        
        // Ubica el JFrame en el centro de la pantalla.
        setLocationRelativeTo(null);
        
        // Muestra el JFrame.
        setVisible(true);
        
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("images/CDV-icon.png")).getImage());

        // Iniciar
        
        
        
    }
    
    
    public void mensaje(String m){
       JOptionPane.showMessageDialog(this, m);
   }
    
    //<editor-fold defaultstate="collapsed" desc=" Listeners ">
    
    
        public void addEvents(java.awt.event.ActionListener evt){
            
        btnMin.addActionListener(evt);  // -> Minimizar
        btnExitt.addActionListener(evt); // -> cerrar
        btnRegisterEmployee.addActionListener(evt); // -> Registrar
            
        }
        
        
        
        
        //</editor-fold>
    
    public void modificarCampos(boolean estado){
    
    txtIdEmployee1.setEditable(estado);
    txtNameEmployee1.setEditable(estado);
    txtSurnameEmployee1.setEditable(estado);
    txtMailEmployee1.setEditable(estado);
    txtPhoneEmployee1.setEditable(estado);
    txtbranch_idEmploye1.setEditable(estado);
    txtposition_idEmployee1.setEditable(estado);
    txtDirectionEmployee1.setEditable(estado);
    txtbirth_dateEmployee1.setEditable(estado);
    txtAdmission_dateEmployee1.setEditable(estado);
    
}

    
    
    public boolean validarCampos(){
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
       String fecha ="";
       String fecha2 ="";
       try {
       fecha = sdf.format(jCalendarbirth_dateEmployee.getDate());
       fecha2 = sdf.format(jCalendarAdmission_dateEmployee1.getDate());
       } 
       catch (Exception e) 
       {
           mensaje("Ingresa una Fecha Valida");
           return false;
       }
       if(txtIdEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtNameEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtSurnameEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtbranch_idEmploye1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtposition_idEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtPhoneEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtDirectionEmployee1.getText().trim().isEmpty()){
           return false;
       }
       else if(txtMailEmployee1.getText().trim().isEmpty()){
           return false;
       }
      
       else{
           return true;
       }

   }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panRegisterModifyClient = new javax.swing.JPanel();
        panTopBarButtons = new javax.swing.JPanel();
        lblModifyRegistrer = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        panExitt = new javax.swing.JPanel();
        btnExitt = new javax.swing.JButton();
        btnMini = new javax.swing.JPanel();
        btnMin = new javax.swing.JButton();
        panButtonsModifyRegister = new javax.swing.JPanel();
        panButtonRegister = new javax.swing.JPanel();
        btnRegisterEmployee = new javax.swing.JButton();
        panButtonModify = new javax.swing.JPanel();
        btnModifyClient = new javax.swing.JButton();
        panData = new javax.swing.JPanel();
        panDataCinemaRoom = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        panDataEnterprise = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        panDataClient = new javax.swing.JPanel();
        lblIdClient = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblNameClient = new javax.swing.JLabel();
        txtNameClient = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblSurnameClient = new javax.swing.JLabel();
        txtSurnameClient = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblPhoneClient1 = new javax.swing.JLabel();
        txtPhoneClient = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblMailClient = new javax.swing.JLabel();
        txtMailClient = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDirectionClient = new javax.swing.JLabel();
        txtDirectionClient = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblBirthDate1 = new javax.swing.JLabel();
        lblBirthDate2 = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        panDataCandy = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        panDataEmployee = new javax.swing.JPanel();
        jSeparator44 = new javax.swing.JSeparator();
        lblIdEmploye1 = new javax.swing.JLabel();
        txtIdEmployee1 = new javax.swing.JTextField();
        jSeparator45 = new javax.swing.JSeparator();
        lblNameEmployee1 = new javax.swing.JLabel();
        txtNameEmployee1 = new javax.swing.JTextField();
        jSeparator49 = new javax.swing.JSeparator();
        lblSurnameEmployee1 = new javax.swing.JLabel();
        txtSurnameEmployee1 = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        lblMailEmploye1 = new javax.swing.JLabel();
        txtMailEmployee1 = new javax.swing.JTextField();
        jSeparator51 = new javax.swing.JSeparator();
        lblPhoneEmployee1 = new javax.swing.JLabel();
        txtPhoneEmployee1 = new javax.swing.JTextField();
        jSeparator52 = new javax.swing.JSeparator();
        lblbranch_idEmploye1 = new javax.swing.JLabel();
        txtbranch_idEmploye1 = new javax.swing.JTextField();
        jSeparator53 = new javax.swing.JSeparator();
        lblposition_idEmployee1 = new javax.swing.JLabel();
        txtposition_idEmployee1 = new javax.swing.JTextField();
        jSeparator54 = new javax.swing.JSeparator();
        lblDirectionEmployee1 = new javax.swing.JLabel();
        txtDirectionEmployee1 = new javax.swing.JTextField();
        jSeparator55 = new javax.swing.JSeparator();
        lblbirth_date2 = new javax.swing.JLabel();
        lblbirth_date3 = new javax.swing.JLabel();
        txtbirth_dateEmployee1 = new javax.swing.JTextField();
        jSeparator56 = new javax.swing.JSeparator();
        lblAdmission_date2 = new javax.swing.JLabel();
        lblAdmission_date3 = new javax.swing.JLabel();
        txtAdmission_dateEmployee1 = new javax.swing.JTextField();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jCalendarbirth_dateEmployee = new com.toedter.calendar.JDateChooser();
        jCalendarAdmission_dateEmployee1 = new com.toedter.calendar.JDateChooser();
        panDataFilm = new javax.swing.JPanel();
        jSeparator15 = new javax.swing.JSeparator();
        panDataBranch = new javax.swing.JPanel();
        jSeparator23 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panRegisterModifyClient.setBackground(new java.awt.Color(239, 232, 244));
        panRegisterModifyClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panTopBarButtons.setBackground(new java.awt.Color(238, 209, 255));

        lblModifyRegistrer.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblModifyRegistrer.setForeground(new java.awt.Color(75, 0, 145));
        lblModifyRegistrer.setText("@");
        lblModifyRegistrer.setToolTipText("");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/icono.png"))); // NOI18N
        lblIcono.setText("jLabel2");

        btnExitt.setBackground(new java.awt.Color(249, 249, 249));
        btnExitt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/multiply(Red)-32px.png"))); // NOI18N
        btnExitt.setToolTipText("Cerrar");
        btnExitt.setBorder(null);
        btnExitt.setBorderPainted(false);
        btnExitt.setContentAreaFilled(false);
        btnExitt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExitt.setFocusPainted(false);
        btnExitt.setOpaque(true);
        btnExitt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExittMouseMoved(evt);
            }
        });
        btnExitt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExittMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panExittLayout = new javax.swing.GroupLayout(panExitt);
        panExitt.setLayout(panExittLayout);
        panExittLayout.setHorizontalGroup(
            panExittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panExittLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panExittLayout.setVerticalGroup(
            panExittLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExittLayout.createSequentialGroup()
                .addComponent(btnExitt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnMin.setBackground(new java.awt.Color(249, 249, 249));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/images/expandArrow(Gray)-32px.png"))); // NOI18N
        btnMin.setToolTipText("Minimizar");
        btnMin.setBorder(null);
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMin.setFocusPainted(false);
        btnMin.setOpaque(true);
        btnMin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMinMouseMoved(evt);
            }
        });
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMiniLayout = new javax.swing.GroupLayout(btnMini);
        btnMini.setLayout(btnMiniLayout);
        btnMiniLayout.setHorizontalGroup(
            btnMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMiniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMiniLayout.setVerticalGroup(
            btnMiniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panTopBarButtonsLayout = new javax.swing.GroupLayout(panTopBarButtons);
        panTopBarButtons.setLayout(panTopBarButtonsLayout);
        panTopBarButtonsLayout.setHorizontalGroup(
            panTopBarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTopBarButtonsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModifyRegistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panExitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panTopBarButtonsLayout.setVerticalGroup(
            panTopBarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panTopBarButtonsLayout.createSequentialGroup()
                .addComponent(lblModifyRegistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panTopBarButtonsLayout.createSequentialGroup()
                .addGroup(panTopBarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panExitt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcono))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblIcono.getAccessibleContext().setAccessibleName("");

        panRegisterModifyClient.add(panTopBarButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 50));

        panButtonsModifyRegister.setBackground(new java.awt.Color(249, 249, 249));
        panButtonsModifyRegister.setLayout(new java.awt.CardLayout());

        panButtonRegister.setBackground(new java.awt.Color(249, 249, 249));
        panButtonRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        panButtonRegister.setForeground(new java.awt.Color(255, 255, 255));

        btnRegisterEmployee.setBackground(new java.awt.Color(245, 245, 245));
        btnRegisterEmployee.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterEmployee.setText("Registrar");
        btnRegisterEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegisterEmployee.setBorderPainted(false);
        btnRegisterEmployee.setContentAreaFilled(false);
        btnRegisterEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegisterEmployee.setFocusPainted(false);
        btnRegisterEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterEmployeeMouseMoved(evt);
            }
        });
        btnRegisterEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterEmployeeMouseExited(evt);
            }
        });
        btnRegisterEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panButtonRegisterLayout = new javax.swing.GroupLayout(panButtonRegister);
        panButtonRegister.setLayout(panButtonRegisterLayout);
        panButtonRegisterLayout.setHorizontalGroup(
            panButtonRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonRegisterLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnRegisterEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        panButtonRegisterLayout.setVerticalGroup(
            panButtonRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonRegisterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnRegisterEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panButtonsModifyRegister.add(panButtonRegister, "card2");

        panButtonModify.setBackground(new java.awt.Color(249, 249, 249));
        panButtonModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 249, 249)));
        panButtonModify.setForeground(new java.awt.Color(255, 255, 255));

        btnModifyClient.setBackground(new java.awt.Color(245, 245, 245));
        btnModifyClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnModifyClient.setForeground(new java.awt.Color(0, 0, 0));
        btnModifyClient.setText("Actualizar");
        btnModifyClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModifyClient.setBorderPainted(false);
        btnModifyClient.setContentAreaFilled(false);
        btnModifyClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModifyClient.setFocusPainted(false);
        btnModifyClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnModifyClientMouseMoved(evt);
            }
        });
        btnModifyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModifyClientMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panButtonModifyLayout = new javax.swing.GroupLayout(panButtonModify);
        panButtonModify.setLayout(panButtonModifyLayout);
        panButtonModifyLayout.setHorizontalGroup(
            panButtonModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonModifyLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        panButtonModifyLayout.setVerticalGroup(
            panButtonModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonModifyLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panButtonsModifyRegister.add(panButtonModify, "card2");

        panRegisterModifyClient.add(panButtonsModifyRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 660, 100));

        panData.setBackground(new java.awt.Color(249, 249, 249));
        panData.setLayout(new java.awt.CardLayout());

        panDataCinemaRoom.setBackground(new java.awt.Color(249, 249, 249));

        jSeparator10.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator10.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panDataCinemaRoomLayout = new javax.swing.GroupLayout(panDataCinemaRoom);
        panDataCinemaRoom.setLayout(panDataCinemaRoomLayout);
        panDataCinemaRoomLayout.setHorizontalGroup(
            panDataCinemaRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDataCinemaRoomLayout.createSequentialGroup()
                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        panDataCinemaRoomLayout.setVerticalGroup(
            panDataCinemaRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataCinemaRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        panData.add(panDataCinemaRoom, "card3");

        panDataEnterprise.setBackground(new java.awt.Color(249, 249, 249));

        jSeparator12.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator12.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panDataEnterpriseLayout = new javax.swing.GroupLayout(panDataEnterprise);
        panDataEnterprise.setLayout(panDataEnterpriseLayout);
        panDataEnterpriseLayout.setHorizontalGroup(
            panDataEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDataEnterpriseLayout.createSequentialGroup()
                .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        panDataEnterpriseLayout.setVerticalGroup(
            panDataEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataEnterpriseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        panData.add(panDataEnterprise, "card3");

        panDataClient.setBackground(new java.awt.Color(249, 249, 249));

        lblIdClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIdClient.setForeground(new java.awt.Color(75, 0, 145));
        lblIdClient.setText("Cédula:");

        txtIdClient.setBackground(new java.awt.Color(239, 232, 244));
        txtIdClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdClient.setBorder(null);
        txtIdClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdClientMouseClicked(evt);
            }
        });
        txtIdClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClientActionPerformed(evt);
            }
        });
        txtIdClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClientKeyTyped(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator2.setForeground(new java.awt.Color(75, 0, 145));

        lblNameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNameClient.setForeground(new java.awt.Color(75, 0, 145));
        lblNameClient.setText("Nombre:");

        txtNameClient.setBackground(new java.awt.Color(239, 232, 244));
        txtNameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNameClient.setAutoscrolls(false);
        txtNameClient.setBorder(null);
        txtNameClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameClientMouseClicked(evt);
            }
        });
        txtNameClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameClientKeyTyped(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator4.setForeground(new java.awt.Color(75, 0, 145));

        lblSurnameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSurnameClient.setForeground(new java.awt.Color(75, 0, 145));
        lblSurnameClient.setText("Apellido:");

        txtSurnameClient.setBackground(new java.awt.Color(239, 232, 244));
        txtSurnameClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSurnameClient.setForeground(new java.awt.Color(239, 232, 244));
        txtSurnameClient.setText("Cédula del cliente");
        txtSurnameClient.setBorder(null);
        txtSurnameClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSurnameClientMouseClicked(evt);
            }
        });
        txtSurnameClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameClientKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator5.setForeground(new java.awt.Color(75, 0, 145));

        lblPhoneClient1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPhoneClient1.setForeground(new java.awt.Color(75, 0, 145));
        lblPhoneClient1.setText("Teléfono:");

        txtPhoneClient.setBackground(new java.awt.Color(239, 232, 244));
        txtPhoneClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneClient.setBorder(null);
        txtPhoneClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneClientMouseClicked(evt);
            }
        });
        txtPhoneClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneClientKeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator7.setForeground(new java.awt.Color(75, 0, 145));

        lblMailClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMailClient.setForeground(new java.awt.Color(75, 0, 145));
        lblMailClient.setText("Correo:");

        txtMailClient.setBackground(new java.awt.Color(239, 232, 244));
        txtMailClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMailClient.setBorder(null);
        txtMailClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMailClientMouseClicked(evt);
            }
        });
        txtMailClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailClientKeyTyped(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator3.setForeground(new java.awt.Color(75, 0, 145));

        lblDirectionClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDirectionClient.setForeground(new java.awt.Color(75, 0, 145));
        lblDirectionClient.setText("Dirección:");

        txtDirectionClient.setBackground(new java.awt.Color(239, 232, 244));
        txtDirectionClient.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDirectionClient.setBorder(null);
        txtDirectionClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDirectionClientMouseClicked(evt);
            }
        });
        txtDirectionClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirectionClientKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator6.setForeground(new java.awt.Color(75, 0, 145));

        lblBirthDate1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBirthDate1.setForeground(new java.awt.Color(75, 0, 145));
        lblBirthDate1.setText("Fecha \n");

        lblBirthDate2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBirthDate2.setForeground(new java.awt.Color(75, 0, 145));
        lblBirthDate2.setText("Nacimiento:");

        txtBirthDate.setBackground(new java.awt.Color(239, 232, 244));
        txtBirthDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBirthDate.setBorder(null);
        txtBirthDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBirthDateMouseClicked(evt);
            }
        });
        txtBirthDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBirthDateKeyTyped(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator8.setForeground(new java.awt.Color(75, 0, 145));

        jSeparator9.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator9.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panDataClientLayout = new javax.swing.GroupLayout(panDataClient);
        panDataClient.setLayout(panDataClientLayout);
        panDataClientLayout.setHorizontalGroup(
            panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataClientLayout.createSequentialGroup()
                .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblPhoneClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtPhoneClient)))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSurnameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5)
                            .addComponent(txtSurnameClient, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panDataClientLayout.createSequentialGroup()
                                .addComponent(lblNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblMailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailClient, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jSeparator3)))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtDirectionClient)))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDataClientLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblBirthDate2))
                            .addGroup(panDataClientLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblBirthDate1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addComponent(txtBirthDate))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jSeparator9)
        );
        panDataClientLayout.setVerticalGroup(
            panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addComponent(lblBirthDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBirthDate2)
                        .addGap(20, 20, 20))
                    .addGroup(panDataClientLayout.createSequentialGroup()
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3))
                        .addGap(20, 20, 20)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panDataClientLayout.createSequentialGroup()
                                .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSurnameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSurnameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panDataClientLayout.createSequentialGroup()
                                .addComponent(txtDirectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDataClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panData.add(panDataClient, "card2");

        panDataCandy.setBackground(new java.awt.Color(249, 249, 249));
        panDataCandy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator14.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator14.setForeground(new java.awt.Color(75, 0, 145));
        panDataCandy.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 654, 10));

        panData.add(panDataCandy, "card3");

        panDataEmployee.setBackground(new java.awt.Color(249, 249, 249));
        panDataEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator44.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator44.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 660, 10));

        lblIdEmploye1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIdEmploye1.setForeground(new java.awt.Color(75, 0, 145));
        lblIdEmploye1.setText("Cédula:");
        panDataEmployee.add(lblIdEmploye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 71, 36));

        txtIdEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtIdEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdEmployee1.setBorder(null);
        txtIdEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdEmployee1MouseClicked(evt);
            }
        });
        txtIdEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmployee1ActionPerformed(evt);
            }
        });
        txtIdEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtIdEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 47, 198, 39));

        jSeparator45.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator45.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 92, 198, -1));

        lblNameEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNameEmployee1.setForeground(new java.awt.Color(75, 0, 145));
        lblNameEmployee1.setText("Nombre:");
        panDataEmployee.add(lblNameEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 101, 62, 36));

        txtNameEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtNameEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNameEmployee1.setAutoscrolls(false);
        txtNameEmployee1.setBorder(null);
        txtNameEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameEmployee1MouseClicked(evt);
            }
        });
        txtNameEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtNameEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 102, 200, 35));

        jSeparator49.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator49.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 143, 202, -1));

        lblSurnameEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSurnameEmployee1.setForeground(new java.awt.Color(75, 0, 145));
        lblSurnameEmployee1.setText("Apellido:");
        panDataEmployee.add(lblSurnameEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 157, 66, 36));

        txtSurnameEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtSurnameEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSurnameEmployee1.setForeground(new java.awt.Color(239, 232, 244));
        txtSurnameEmployee1.setText("Cédula del cliente");
        txtSurnameEmployee1.setBorder(null);
        txtSurnameEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSurnameEmployee1MouseClicked(evt);
            }
        });
        txtSurnameEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtSurnameEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 198, 36));

        jSeparator50.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator50.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 198, -1));

        lblMailEmploye1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMailEmploye1.setForeground(new java.awt.Color(75, 0, 145));
        lblMailEmploye1.setText("Correo:");
        panDataEmployee.add(lblMailEmploye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 206, 77, 36));

        txtMailEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtMailEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMailEmployee1.setBorder(null);
        txtMailEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMailEmployee1MouseClicked(evt);
            }
        });
        txtMailEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtMailEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 205, 199, 39));

        jSeparator51.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator51.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 199, -1));

        lblPhoneEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPhoneEmployee1.setForeground(new java.awt.Color(75, 0, 145));
        lblPhoneEmployee1.setText("Teléfono:");
        panDataEmployee.add(lblPhoneEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 265, 71, 36));

        txtPhoneEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtPhoneEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhoneEmployee1.setBorder(null);
        txtPhoneEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPhoneEmployee1MouseClicked(evt);
            }
        });
        txtPhoneEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtPhoneEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 264, 199, 39));

        jSeparator52.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator52.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 309, 199, 11));

        lblbranch_idEmploye1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbranch_idEmploye1.setForeground(new java.awt.Color(75, 0, 145));
        lblbranch_idEmploye1.setText("Sucursal");
        panDataEmployee.add(lblbranch_idEmploye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 71, 36));

        txtbranch_idEmploye1.setBackground(new java.awt.Color(239, 232, 244));
        txtbranch_idEmploye1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtbranch_idEmploye1.setAutoscrolls(false);
        txtbranch_idEmploye1.setBorder(null);
        txtbranch_idEmploye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbranch_idEmploye1MouseClicked(evt);
            }
        });
        txtbranch_idEmploye1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbranch_idEmploye1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtbranch_idEmploye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 200, 35));

        jSeparator53.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator53.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 200, 10));

        lblposition_idEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblposition_idEmployee1.setForeground(new java.awt.Color(75, 0, 145));
        lblposition_idEmployee1.setText("Cargo");
        panDataEmployee.add(lblposition_idEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 50, 36));

        txtposition_idEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtposition_idEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtposition_idEmployee1.setAutoscrolls(false);
        txtposition_idEmployee1.setBorder(null);
        txtposition_idEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtposition_idEmployee1MouseClicked(evt);
            }
        });
        txtposition_idEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtposition_idEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtposition_idEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 200, 35));

        jSeparator54.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator54.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 200, 10));

        lblDirectionEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDirectionEmployee1.setForeground(new java.awt.Color(75, 0, 145));
        lblDirectionEmployee1.setText("Dirección:");
        panDataEmployee.add(lblDirectionEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 76, 36));

        txtDirectionEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtDirectionEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDirectionEmployee1.setForeground(new java.awt.Color(239, 232, 244));
        txtDirectionEmployee1.setText("Cédula del cliente");
        txtDirectionEmployee1.setBorder(null);
        txtDirectionEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDirectionEmployee1MouseClicked(evt);
            }
        });
        txtDirectionEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirectionEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtDirectionEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 198, 36));

        jSeparator55.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator55.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 198, -1));

        lblbirth_date2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbirth_date2.setForeground(new java.awt.Color(75, 0, 145));
        lblbirth_date2.setText("Fecha");
        panDataEmployee.add(lblbirth_date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 20));

        lblbirth_date3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblbirth_date3.setForeground(new java.awt.Color(75, 0, 145));
        lblbirth_date3.setText("Nacimiento:");
        panDataEmployee.add(lblbirth_date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        txtbirth_dateEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtbirth_dateEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtbirth_dateEmployee1.setBorder(null);
        txtbirth_dateEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbirth_dateEmployee1MouseClicked(evt);
            }
        });
        txtbirth_dateEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbirth_dateEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtbirth_dateEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 60, 39));

        jSeparator56.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator56.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 190, 12));

        lblAdmission_date2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAdmission_date2.setForeground(new java.awt.Color(75, 0, 145));
        lblAdmission_date2.setText("Fecha \n");
        panDataEmployee.add(lblAdmission_date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        lblAdmission_date3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAdmission_date3.setForeground(new java.awt.Color(75, 0, 145));
        lblAdmission_date3.setText("Ingreso");
        panDataEmployee.add(lblAdmission_date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 20));

        txtAdmission_dateEmployee1.setBackground(new java.awt.Color(239, 232, 244));
        txtAdmission_dateEmployee1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAdmission_dateEmployee1.setBorder(null);
        txtAdmission_dateEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAdmission_dateEmployee1MouseClicked(evt);
            }
        });
        txtAdmission_dateEmployee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdmission_dateEmployee1KeyTyped(evt);
            }
        });
        panDataEmployee.add(txtAdmission_dateEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 39));

        jSeparator57.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator57.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 200, 12));

        jSeparator58.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator58.setForeground(new java.awt.Color(75, 0, 145));
        panDataEmployee.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, 654, 11));
        panDataEmployee.add(jCalendarbirth_dateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, -1));
        panDataEmployee.add(jCalendarAdmission_dateEmployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 190, -1));

        panData.add(panDataEmployee, "card3");

        panDataFilm.setBackground(new java.awt.Color(249, 249, 249));

        jSeparator15.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator15.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panDataFilmLayout = new javax.swing.GroupLayout(panDataFilm);
        panDataFilm.setLayout(panDataFilmLayout);
        panDataFilmLayout.setHorizontalGroup(
            panDataFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator15, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        panDataFilmLayout.setVerticalGroup(
            panDataFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        panData.add(panDataFilm, "card3");

        panDataBranch.setBackground(new java.awt.Color(249, 249, 249));

        jSeparator23.setBackground(new java.awt.Color(249, 249, 249));
        jSeparator23.setForeground(new java.awt.Color(75, 0, 145));

        javax.swing.GroupLayout panDataBranchLayout = new javax.swing.GroupLayout(panDataBranch);
        panDataBranch.setLayout(panDataBranchLayout);
        panDataBranchLayout.setHorizontalGroup(
            panDataBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator23, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        panDataBranchLayout.setVerticalGroup(
            panDataBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataBranchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        panData.add(panDataBranch, "card3");

        panRegisterModifyClient.add(panData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 660, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRegisterModifyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRegisterModifyClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExittMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExittMouseMoved
        btnExitt.setBackground(new java.awt.Color(255,183,183));
    }//GEN-LAST:event_btnExittMouseMoved

    private void btnExittMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExittMouseExited
        btnExitt.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnExittMouseExited

    private void btnMinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseMoved
        btnMin.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnMinMouseMoved

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(new java.awt.Color(249,249,249));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnRegisterEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterEmployeeMouseMoved
        panButtonRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75,0,145)));
        btnRegisterEmployee.setForeground(new java.awt.Color(255,255,255));
        panButtonRegister.setBackground(new java.awt.Color(66,0,124));
    }//GEN-LAST:event_btnRegisterEmployeeMouseMoved

    private void btnRegisterEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterEmployeeMouseExited
        panButtonRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249,249,249)));
        btnRegisterEmployee.setForeground(new java.awt.Color(0,0,0));
        panButtonRegister.setBackground(new java.awt.Color(239,232,244));
    }//GEN-LAST:event_btnRegisterEmployeeMouseExited

    private void btnRegisterEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterEmployeeActionPerformed

    private void btnModifyClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyClientMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyClientMouseMoved

    private void btnModifyClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyClientMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyClientMouseExited

    private void txtBirthDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBirthDateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateKeyTyped

    private void txtBirthDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBirthDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateMouseClicked

    private void txtDirectionClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirectionClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectionClientKeyTyped

    private void txtDirectionClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirectionClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectionClientMouseClicked

    private void txtMailClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailClientKeyTyped

    private void txtMailClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMailClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailClientMouseClicked

    private void txtPhoneClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneClientKeyTyped

    private void txtPhoneClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneClientMouseClicked

    private void txtSurnameClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameClientKeyTyped

    private void txtSurnameClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSurnameClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameClientMouseClicked

    private void txtNameClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameClientKeyTyped

    private void txtNameClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameClientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameClientMouseClicked

    private void txtIdClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClientKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClientKeyTyped

    private void txtIdClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClientActionPerformed

    private void txtIdClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdClientMouseClicked
        txtIdClient.setText("");
    }//GEN-LAST:event_txtIdClientMouseClicked

    private void txtIdEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmployee1MouseClicked

    private void txtIdEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmployee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmployee1ActionPerformed

    private void txtIdEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmployee1KeyTyped

    private void txtNameEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEmployee1MouseClicked

    private void txtNameEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEmployee1KeyTyped

    private void txtSurnameEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSurnameEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameEmployee1MouseClicked

    private void txtSurnameEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameEmployee1KeyTyped

    private void txtMailEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMailEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailEmployee1MouseClicked

    private void txtMailEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailEmployee1KeyTyped

    private void txtPhoneEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneEmployee1MouseClicked

    private void txtPhoneEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneEmployee1KeyTyped

    private void txtbranch_idEmploye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbranch_idEmploye1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbranch_idEmploye1MouseClicked

    private void txtbranch_idEmploye1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbranch_idEmploye1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbranch_idEmploye1KeyTyped

    private void txtposition_idEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtposition_idEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtposition_idEmployee1MouseClicked

    private void txtposition_idEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtposition_idEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtposition_idEmployee1KeyTyped

    private void txtDirectionEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirectionEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectionEmployee1MouseClicked

    private void txtDirectionEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirectionEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectionEmployee1KeyTyped

    private void txtbirth_dateEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbirth_dateEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirth_dateEmployee1MouseClicked

    private void txtbirth_dateEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbirth_dateEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbirth_dateEmployee1KeyTyped

    private void txtAdmission_dateEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdmission_dateEmployee1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmission_dateEmployee1MouseClicked

    private void txtAdmission_dateEmployee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdmission_dateEmployee1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmission_dateEmployee1KeyTyped

    private void jCalendarbirth_dateEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendarbirth_dateEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalendarbirth_dateEmployeeMouseClicked

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      /*  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterModify().setVisible(true);
            }
        });
    }*/


    
//<editor-fold defaultstate="collapsed" desc=" Metodos set y get de Componentes">
    
    public SuportFunctions getSuport() {
        return suport;
    }

    public void setSuport(SuportFunctions suport) {
        this.suport = suport;
    }

    public JButton getBtnExitt() {
        return btnExitt;
    }

    public void setBtnExitt(JButton btnExitt) {
        this.btnExitt = btnExitt;
    }

    public JButton getBtnMin() {
        return btnMin;
    }

    public void setBtnMin(JButton btnMin) {
        this.btnMin = btnMin;
    }

    public JPanel getBtnMini() {
        return btnMini;
    }

    public void setBtnMini(JPanel btnMini) {
        this.btnMini = btnMini;
    }

    public JButton getBtnModifyClient() {
        return btnModifyClient;
    }

    public void setBtnModifyClient(JButton btnModifyClient) {
        this.btnModifyClient = btnModifyClient;
    }

    public JButton getBtnRegisterEmployee() {
        return btnRegisterEmployee;
    }

    public void setBtnRegisterEmployee(JButton btnRegisterEmployee) {
        this.btnRegisterEmployee = btnRegisterEmployee;
    }

    public JSeparator getjSeparator10() {
        return jSeparator10;
    }

    public void setjSeparator10(JSeparator jSeparator10) {
        this.jSeparator10 = jSeparator10;
    }

    public JSeparator getjSeparator12() {
        return jSeparator12;
    }

    public void setjSeparator12(JSeparator jSeparator12) {
        this.jSeparator12 = jSeparator12;
    }

    public JSeparator getjSeparator14() {
        return jSeparator14;
    }

    public void setjSeparator14(JSeparator jSeparator14) {
        this.jSeparator14 = jSeparator14;
    }

    public JSeparator getjSeparator15() {
        return jSeparator15;
    }

    public void setjSeparator15(JSeparator jSeparator15) {
        this.jSeparator15 = jSeparator15;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JSeparator getjSeparator23() {
        return jSeparator23;
    }

    public void setjSeparator23(JSeparator jSeparator23) {
        this.jSeparator23 = jSeparator23;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JSeparator getjSeparator44() {
        return jSeparator44;
    }

    public void setjSeparator44(JSeparator jSeparator44) {
        this.jSeparator44 = jSeparator44;
    }

    public JSeparator getjSeparator45() {
        return jSeparator45;
    }

    public void setjSeparator45(JSeparator jSeparator45) {
        this.jSeparator45 = jSeparator45;
    }

    public JSeparator getjSeparator49() {
        return jSeparator49;
    }

    public void setjSeparator49(JSeparator jSeparator49) {
        this.jSeparator49 = jSeparator49;
    }

    public JSeparator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JSeparator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JSeparator getjSeparator50() {
        return jSeparator50;
    }

    public void setjSeparator50(JSeparator jSeparator50) {
        this.jSeparator50 = jSeparator50;
    }

    public JSeparator getjSeparator51() {
        return jSeparator51;
    }

    public void setjSeparator51(JSeparator jSeparator51) {
        this.jSeparator51 = jSeparator51;
    }

    public JSeparator getjSeparator52() {
        return jSeparator52;
    }

    public void setjSeparator52(JSeparator jSeparator52) {
        this.jSeparator52 = jSeparator52;
    }

    public JSeparator getjSeparator53() {
        return jSeparator53;
    }

    public void setjSeparator53(JSeparator jSeparator53) {
        this.jSeparator53 = jSeparator53;
    }

    public JSeparator getjSeparator54() {
        return jSeparator54;
    }

    public void setjSeparator54(JSeparator jSeparator54) {
        this.jSeparator54 = jSeparator54;
    }

    public JSeparator getjSeparator55() {
        return jSeparator55;
    }

    public void setjSeparator55(JSeparator jSeparator55) {
        this.jSeparator55 = jSeparator55;
    }

    public JSeparator getjSeparator56() {
        return jSeparator56;
    }

    public void setjSeparator56(JSeparator jSeparator56) {
        this.jSeparator56 = jSeparator56;
    }

    public JSeparator getjSeparator57() {
        return jSeparator57;
    }

    public void setjSeparator57(JSeparator jSeparator57) {
        this.jSeparator57 = jSeparator57;
    }

    public JSeparator getjSeparator58() {
        return jSeparator58;
    }

    public void setjSeparator58(JSeparator jSeparator58) {
        this.jSeparator58 = jSeparator58;
    }

    public JSeparator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JSeparator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JSeparator getjSeparator7() {
        return jSeparator7;
    }

    public void setjSeparator7(JSeparator jSeparator7) {
        this.jSeparator7 = jSeparator7;
    }

    public JSeparator getjSeparator8() {
        return jSeparator8;
    }

    public void setjSeparator8(JSeparator jSeparator8) {
        this.jSeparator8 = jSeparator8;
    }

    public JSeparator getjSeparator9() {
        return jSeparator9;
    }

    public void setjSeparator9(JSeparator jSeparator9) {
        this.jSeparator9 = jSeparator9;
    }

    public JLabel getLblAdmission_date2() {
        return lblAdmission_date2;
    }

    public void setLblAdmission_date2(JLabel lblAdmission_date2) {
        this.lblAdmission_date2 = lblAdmission_date2;
    }

    public JLabel getLblAdmission_date3() {
        return lblAdmission_date3;
    }

    public void setLblAdmission_date3(JLabel lblAdmission_date3) {
        this.lblAdmission_date3 = lblAdmission_date3;
    }

    public JLabel getLblBirthDate1() {
        return lblBirthDate1;
    }

    public void setLblBirthDate1(JLabel lblBirthDate1) {
        this.lblBirthDate1 = lblBirthDate1;
    }

    public JLabel getLblBirthDate2() {
        return lblBirthDate2;
    }

    public void setLblBirthDate2(JLabel lblBirthDate2) {
        this.lblBirthDate2 = lblBirthDate2;
    }

    public JLabel getLblDirectionClient() {
        return lblDirectionClient;
    }

    public void setLblDirectionClient(JLabel lblDirectionClient) {
        this.lblDirectionClient = lblDirectionClient;
    }

    public JLabel getLblDirectionEmployee1() {
        return lblDirectionEmployee1;
    }

    public void setLblDirectionEmployee1(JLabel lblDirectionEmployee1) {
        this.lblDirectionEmployee1 = lblDirectionEmployee1;
    }

    public JLabel getLblIcono() {
        return lblIcono;
    }

    public void setLblIcono(JLabel lblIcono) {
        this.lblIcono = lblIcono;
    }

    public JLabel getLblIdClient() {
        return lblIdClient;
    }

    public void setLblIdClient(JLabel lblIdClient) {
        this.lblIdClient = lblIdClient;
    }

    public JLabel getLblIdEmploye1() {
        return lblIdEmploye1;
    }

    public void setLblIdEmploye1(JLabel lblIdEmploye1) {
        this.lblIdEmploye1 = lblIdEmploye1;
    }

    public JLabel getLblMailClient() {
        return lblMailClient;
    }

    public void setLblMailClient(JLabel lblMailClient) {
        this.lblMailClient = lblMailClient;
    }

    public JLabel getLblMailEmploye1() {
        return lblMailEmploye1;
    }

    public void setLblMailEmploye1(JLabel lblMailEmploye1) {
        this.lblMailEmploye1 = lblMailEmploye1;
    }

    public JLabel getLblModifyRegistrer() {
        return lblModifyRegistrer;
    }

    public void setLblModifyRegistrer(JLabel lblModifyRegistrer) {
        this.lblModifyRegistrer = lblModifyRegistrer;
    }

    public JLabel getLblNameClient() {
        return lblNameClient;
    }

    public void setLblNameClient(JLabel lblNameClient) {
        this.lblNameClient = lblNameClient;
    }

    public JLabel getLblNameEmployee1() {
        return lblNameEmployee1;
    }

    public void setLblNameEmployee1(JLabel lblNameEmployee1) {
        this.lblNameEmployee1 = lblNameEmployee1;
    }

    public JLabel getLblPhoneClient1() {
        return lblPhoneClient1;
    }

    public void setLblPhoneClient1(JLabel lblPhoneClient1) {
        this.lblPhoneClient1 = lblPhoneClient1;
    }

    public JLabel getLblPhoneEmployee1() {
        return lblPhoneEmployee1;
    }

    public void setLblPhoneEmployee1(JLabel lblPhoneEmployee1) {
        this.lblPhoneEmployee1 = lblPhoneEmployee1;
    }

    public JLabel getLblSurnameClient() {
        return lblSurnameClient;
    }

    public void setLblSurnameClient(JLabel lblSurnameClient) {
        this.lblSurnameClient = lblSurnameClient;
    }

    public JLabel getLblSurnameEmployee1() {
        return lblSurnameEmployee1;
    }

    public void setLblSurnameEmployee1(JLabel lblSurnameEmployee1) {
        this.lblSurnameEmployee1 = lblSurnameEmployee1;
    }

    public JLabel getLblbirth_date2() {
        return lblbirth_date2;
    }

    public void setLblbirth_date2(JLabel lblbirth_date2) {
        this.lblbirth_date2 = lblbirth_date2;
    }

    public JLabel getLblbirth_date3() {
        return lblbirth_date3;
    }

    public void setLblbirth_date3(JLabel lblbirth_date3) {
        this.lblbirth_date3 = lblbirth_date3;
    }

    public JLabel getLblbranch_idEmploye1() {
        return lblbranch_idEmploye1;
    }

    public void setLblbranch_idEmploye1(JLabel lblbranch_idEmploye1) {
        this.lblbranch_idEmploye1 = lblbranch_idEmploye1;
    }

    public JLabel getLblposition_idEmployee1() {
        return lblposition_idEmployee1;
    }

    public void setLblposition_idEmployee1(JLabel lblposition_idEmployee1) {
        this.lblposition_idEmployee1 = lblposition_idEmployee1;
    }

    public JPanel getPanButtonModify() {
        return panButtonModify;
    }

    public void setPanButtonModify(JPanel panButtonModify) {
        this.panButtonModify = panButtonModify;
    }

    public JPanel getPanButtonRegister() {
        return panButtonRegister;
    }

    public void setPanButtonRegister(JPanel panButtonRegister) {
        this.panButtonRegister = panButtonRegister;
    }

    public JPanel getPanButtonsModifyRegister() {
        return panButtonsModifyRegister;
    }

    public void setPanButtonsModifyRegister(JPanel panButtonsModifyRegister) {
        this.panButtonsModifyRegister = panButtonsModifyRegister;
    }

    public JPanel getPanData() {
        return panData;
    }

    public void setPanData(JPanel panData) {
        this.panData = panData;
    }

    public JPanel getPanDataBranch() {
        return panDataBranch;
    }

    public void setPanDataBranch(JPanel panDataBranch) {
        this.panDataBranch = panDataBranch;
    }

    public JPanel getPanDataCandy() {
        return panDataCandy;
    }

    public void setPanDataCandy(JPanel panDataCandy) {
        this.panDataCandy = panDataCandy;
    }

    public JPanel getPanDataCinemaRoom() {
        return panDataCinemaRoom;
    }

    public void setPanDataCinemaRoom(JPanel panDataCinemaRoom) {
        this.panDataCinemaRoom = panDataCinemaRoom;
    }

    public JPanel getPanDataClient() {
        return panDataClient;
    }

    public void setPanDataClient(JPanel panDataClient) {
        this.panDataClient = panDataClient;
    }

    public JPanel getPanDataEmployee() {
        return panDataEmployee;
    }

    public void setPanDataEmployee(JPanel panDataEmployee) {
        this.panDataEmployee = panDataEmployee;
    }

    public JPanel getPanDataEnterprise() {
        return panDataEnterprise;
    }

    public void setPanDataEnterprise(JPanel panDataEnterprise) {
        this.panDataEnterprise = panDataEnterprise;
    }

    public JPanel getPanDataFilm() {
        return panDataFilm;
    }

    public void setPanDataFilm(JPanel panDataFilm) {
        this.panDataFilm = panDataFilm;
    }

    public JPanel getPanExitt() {
        return panExitt;
    }

    public void setPanExitt(JPanel panExitt) {
        this.panExitt = panExitt;
    }

    public JPanel getPanRegisterModifyClient() {
        return panRegisterModifyClient;
    }

    public void setPanRegisterModifyClient(JPanel panRegisterModifyClient) {
        this.panRegisterModifyClient = panRegisterModifyClient;
    }

    public JPanel getPanTopBarButtons() {
        return panTopBarButtons;
    }

    public void setPanTopBarButtons(JPanel panTopBarButtons) {
        this.panTopBarButtons = panTopBarButtons;
    }

    public JTextField getTxtAdmission_dateEmployee1() {
        return txtAdmission_dateEmployee1;
    }

    public void setTxtAdmission_dateEmployee1(JTextField txtAdmission_dateEmployee1) {
        this.txtAdmission_dateEmployee1 = txtAdmission_dateEmployee1;
    }

    public JTextField getTxtBirthDate() {
        return txtBirthDate;
    }

    public void setTxtBirthDate(JTextField txtBirthDate) {
        this.txtBirthDate = txtBirthDate;
    }

    public JTextField getTxtDirectionClient() {
        return txtDirectionClient;
    }

    public void setTxtDirectionClient(JTextField txtDirectionClient) {
        this.txtDirectionClient = txtDirectionClient;
    }

    public JTextField getTxtDirectionEmployee1() {
        return txtDirectionEmployee1;
    }

    public void setTxtDirectionEmployee1(JTextField txtDirectionEmployee1) {
        this.txtDirectionEmployee1 = txtDirectionEmployee1;
    }

    public JTextField getTxtIdClient() {
        return txtIdClient;
    }

    public void setTxtIdClient(JTextField txtIdClient) {
        this.txtIdClient = txtIdClient;
    }

    public JTextField getTxtIdEmployee1() {
        return txtIdEmployee1;
    }

    public void setTxtIdEmployee1(JTextField txtIdEmployee1) {
        this.txtIdEmployee1 = txtIdEmployee1;
    }

    public JTextField getTxtMailClient() {
        return txtMailClient;
    }

    public void setTxtMailClient(JTextField txtMailClient) {
        this.txtMailClient = txtMailClient;
    }

    public JTextField getTxtMailEmployee1() {
        return txtMailEmployee1;
    }

    public void setTxtMailEmployee1(JTextField txtMailEmployee1) {
        this.txtMailEmployee1 = txtMailEmployee1;
    }

    public JTextField getTxtNameClient() {
        return txtNameClient;
    }

    public void setTxtNameClient(JTextField txtNameClient) {
        this.txtNameClient = txtNameClient;
    }

    public JTextField getTxtNameEmployee1() {
        return txtNameEmployee1;
    }

    public void setTxtNameEmployee1(JTextField txtNameEmployee1) {
        this.txtNameEmployee1 = txtNameEmployee1;
    }

    public JTextField getTxtPhoneClient() {
        return txtPhoneClient;
    }

    public void setTxtPhoneClient(JTextField txtPhoneClient) {
        this.txtPhoneClient = txtPhoneClient;
    }

    public JTextField getTxtPhoneEmployee1() {
        return txtPhoneEmployee1;
    }

    public void setTxtPhoneEmployee1(JTextField txtPhoneEmployee1) {
        this.txtPhoneEmployee1 = txtPhoneEmployee1;
    }

    public JTextField getTxtSurnameClient() {
        return txtSurnameClient;
    }

    public void setTxtSurnameClient(JTextField txtSurnameClient) {
        this.txtSurnameClient = txtSurnameClient;
    }

    public JTextField getTxtSurnameEmployee1() {
        return txtSurnameEmployee1;
    }

    public void setTxtSurnameEmployee1(JTextField txtSurnameEmployee1) {
        this.txtSurnameEmployee1 = txtSurnameEmployee1;
    }

    public JTextField getTxtbirth_dateEmployee1() {
        return txtbirth_dateEmployee1;
    }

    public void setTxtbirth_dateEmployee1(JTextField txtbirth_dateEmployee1) {
        this.txtbirth_dateEmployee1 = txtbirth_dateEmployee1;
    }

    public JTextField getTxtbranch_idEmploye1() {
        return txtbranch_idEmploye1;
    }

    public void setTxtbranch_idEmploye1(JTextField txtbranch_idEmploye1) {
        this.txtbranch_idEmploye1 = txtbranch_idEmploye1;
    }

    public JTextField getTxtposition_idEmployee1() {
        return txtposition_idEmployee1;
    }

    public void setTxtposition_idEmployee1(JTextField txtposition_idEmployee1) {
        this.txtposition_idEmployee1 = txtposition_idEmployee1;
    }
//</editor-fold>
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExitt;
    public javax.swing.JButton btnMin;
    private javax.swing.JPanel btnMini;
    public javax.swing.JButton btnModifyClient;
    public javax.swing.JButton btnRegisterEmployee;
    public com.toedter.calendar.JDateChooser jCalendarAdmission_dateEmployee1;
    public com.toedter.calendar.JDateChooser jCalendarbirth_dateEmployee;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAdmission_date2;
    private javax.swing.JLabel lblAdmission_date3;
    private javax.swing.JLabel lblBirthDate1;
    private javax.swing.JLabel lblBirthDate2;
    private javax.swing.JLabel lblDirectionClient;
    private javax.swing.JLabel lblDirectionEmployee1;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIdClient;
    private javax.swing.JLabel lblIdEmploye1;
    private javax.swing.JLabel lblMailClient;
    private javax.swing.JLabel lblMailEmploye1;
    private javax.swing.JLabel lblModifyRegistrer;
    private javax.swing.JLabel lblNameClient;
    private javax.swing.JLabel lblNameEmployee1;
    private javax.swing.JLabel lblPhoneClient1;
    private javax.swing.JLabel lblPhoneEmployee1;
    private javax.swing.JLabel lblSurnameClient;
    private javax.swing.JLabel lblSurnameEmployee1;
    private javax.swing.JLabel lblbirth_date2;
    private javax.swing.JLabel lblbirth_date3;
    private javax.swing.JLabel lblbranch_idEmploye1;
    private javax.swing.JLabel lblposition_idEmployee1;
    private javax.swing.JPanel panButtonModify;
    private javax.swing.JPanel panButtonRegister;
    public javax.swing.JPanel panButtonsModifyRegister;
    public javax.swing.JPanel panData;
    private javax.swing.JPanel panDataBranch;
    private javax.swing.JPanel panDataCandy;
    private javax.swing.JPanel panDataCinemaRoom;
    private javax.swing.JPanel panDataClient;
    public javax.swing.JPanel panDataEmployee;
    private javax.swing.JPanel panDataEnterprise;
    private javax.swing.JPanel panDataFilm;
    private javax.swing.JPanel panExitt;
    public javax.swing.JPanel panRegisterModifyClient;
    public javax.swing.JPanel panTopBarButtons;
    public javax.swing.JTextField txtAdmission_dateEmployee1;
    public javax.swing.JTextField txtBirthDate;
    public javax.swing.JTextField txtDirectionClient;
    public javax.swing.JTextField txtDirectionEmployee1;
    public javax.swing.JTextField txtIdClient;
    public javax.swing.JTextField txtIdEmployee1;
    public javax.swing.JTextField txtMailClient;
    public javax.swing.JTextField txtMailEmployee1;
    public javax.swing.JTextField txtNameClient;
    public javax.swing.JTextField txtNameEmployee1;
    public javax.swing.JTextField txtPhoneClient;
    public javax.swing.JTextField txtPhoneEmployee1;
    public javax.swing.JTextField txtSurnameClient;
    public javax.swing.JTextField txtSurnameEmployee1;
    public javax.swing.JTextField txtbirth_dateEmployee1;
    public javax.swing.JTextField txtbranch_idEmploye1;
    public javax.swing.JTextField txtposition_idEmployee1;
    // End of variables declaration//GEN-END:variables
}
